var BenderlyZwickInfo ={
   "format" : "An annual multiple time series from 1952 to 1982 with 5 variables.",
   "description" : "Description\nTime series data, 1952&ndash;1982.",
   "title" : "Benderly and Zwick Data: Inflation, Growth and Stock Returns",
   "usage" : "data(\"BenderlyZwick\")",
   "reference" : "The first three columns of the data are from Table 1 in Benderly and Zwick (1985).\nThe remaining columns are taken from the online complements of Baltagi (2002).\nThe first column is identical in both sources, the other two variables differ\nin their numeric values and additionally the growth series seems to be lagged\ndifferently. Baltagi (2002) states Lott and Ray (1992) as the source for his\nversion of the data set.",
   "parameters" : {
      "growth" : "annual growth rate of output, measured by real GNP\n(from the given year to the next year).",
      "inflation2" : "inflation rate as given by Baltagi",
      "inflation" : "inflation rate, measured as growth of price\nrate (from December of the previous year to December of the present year).",
      "growth2" : "annual growth rate of real GNP as given by Baltagi.",
      "returns" : "real annual returns on stocks, measured using\nthe Ibbotson-Sinquefeld data base."
   }
}

var BenderlyZwick = [
   [
      "returns",
      "growth",
      "inflation",
      "growth2",
      "inflation2"
   ],
   [
      "",
      "",
      "",
      "3.9",
      "2.2"
   ],
   [
      "",
      "",
      "",
      "4",
      "2.1"
   ],
   [
      "53",
      "6.7",
      "-0.4",
      "-1.3",
      "0.6"
   ],
   [
      "31.2",
      "2.1",
      "0.4",
      "5.6",
      "1.3"
   ],
   [
      "3.7",
      "1.8",
      "2.9",
      "2.1",
      "1.9"
   ],
   [
      "-13.8",
      "-0.4",
      "3",
      "1.7",
      "3.2"
   ],
   [
      "41.7",
      "6",
      "1.7",
      "-0.8",
      "1.8"
   ],
   [
      "10.5",
      "2.1",
      "1.5",
      "5.8",
      "2.2"
   ],
   [
      "-1.3",
      "2.6",
      "1.8",
      "2.2",
      "1.9"
   ],
   [
      "26.1",
      "5.8",
      "0.8",
      "2.6",
      "1.2"
   ],
   [
      "-10.5",
      "4",
      "1.8",
      "5.3",
      "1.8"
   ],
   [
      "21.2",
      "5.3",
      "1.6",
      "4.1",
      "1.5"
   ],
   [
      "15.5",
      "6",
      "1",
      "5.3",
      "1.7"
   ],
   [
      "10.2",
      "6",
      "2.3",
      "5.8",
      "1.7"
   ],
   [
      "-13.3",
      "2.7",
      "3.2",
      "5.8",
      "3.1"
   ],
   [
      "21.3",
      "4.6",
      "2.7",
      "2.9",
      "2.5"
   ],
   [
      "6.8",
      "2.8",
      "4.3",
      "4.1",
      "4.5"
   ],
   [
      "-13.5",
      "-0.2",
      "5",
      "2.4",
      "4.3"
   ],
   [
      "-0.4",
      "3.4",
      "4.4",
      "-0.3",
      "4.6"
   ],
   [
      "10.5",
      "5.7",
      "3.8",
      "2.8",
      "4.7"
   ],
   [
      "15.4",
      "5.8",
      "3.6",
      "5",
      "4"
   ],
   [
      "-22.6",
      "-0.6",
      "7.9",
      "5.2",
      "6.2"
   ],
   [
      "-37.3",
      "-1.2",
      "10.8",
      "-0.5",
      "10.5"
   ],
   [
      "31.2",
      "5.4",
      "6",
      "-1.3",
      "8"
   ],
   [
      "19.1",
      "5.5",
      "4.7",
      "4.9",
      "5.7"
   ],
   [
      "-13.1",
      "5",
      "5.9",
      "4.7",
      "6.5"
   ],
   [
      "-1.3",
      "2.8",
      "7.9",
      "5.3",
      "7.3"
   ],
   [
      "8.6",
      "-0.3",
      "9.8",
      "2.5",
      "9.2"
   ],
   [
      "22.2",
      "2.6",
      "10.2",
      "-0.2",
      "10.7"
   ],
   [
      "-12.2",
      "-1.9",
      "7.3",
      "1.9",
      "9.2"
   ],
   [
      "",
      "",
      "",
      "-2.5",
      "5.7"
   ]
]
