var flowerInfo ={
   "usage" : "data(flower)",
   "title" : "Flower Characteristics",
   "format" : "A data frame with 18 observations on 8 variables:",
   "parameters" : {
      "V2" : "shadow, is binary and shows whether the plant needs to stand\nin the shadow.",
      "V8" : "distance, is interval scaled, the distance in centimeters that\nshould be left between the plants.",
      "V4" : "color, is nominal and specifies the flower's color (1 = white,\n2 = yellow, 3 = pink, 4 = red, 5 = blue).",
      "V1" : "winters, is binary and indicates whether the plant may be left\nin the garden when it freezes.",
      "V3" : "tubers, is asymmetric binary and distinguishes between plants\nwith tubers and plants that grow in any other way.",
      "V6" : "preference, is ordinal and gives someone's preference ranking\ngoing from 1 to 18.",
      "V7" : "height, is interval scaled, the plant's height in centimeters.",
      "V5" : "soil, is ordinal and indicates whether the plant grows in dry\n(1), normal (2), or wet (3) soil."
   },
   "description" : "Description\n8 characteristics for 18 popular flowers."
}

var flower = [
   [
      "V1",
      "V2",
      "V3",
      "V4",
      "V5",
      "V6",
      "V7",
      "V8"
   ],
   [
      "0",
      "1",
      "1",
      "4",
      "3",
      "15",
      "25",
      "15"
   ],
   [
      "1",
      "0",
      "0",
      "2",
      "1",
      "3",
      "150",
      "50"
   ],
   [
      "0",
      "1",
      "0",
      "3",
      "3",
      "1",
      "150",
      "50"
   ],
   [
      "0",
      "0",
      "1",
      "4",
      "2",
      "16",
      "125",
      "50"
   ],
   [
      "0",
      "1",
      "0",
      "5",
      "2",
      "2",
      "20",
      "15"
   ],
   [
      "0",
      "1",
      "0",
      "4",
      "3",
      "12",
      "50",
      "40"
   ],
   [
      "0",
      "0",
      "0",
      "4",
      "3",
      "13",
      "40",
      "20"
   ],
   [
      "0",
      "0",
      "1",
      "2",
      "2",
      "7",
      "100",
      "15"
   ],
   [
      "1",
      "1",
      "0",
      "3",
      "1",
      "4",
      "25",
      "15"
   ],
   [
      "1",
      "1",
      "0",
      "5",
      "2",
      "14",
      "100",
      "60"
   ],
   [
      "1",
      "1",
      "1",
      "5",
      "3",
      "8",
      "45",
      "10"
   ],
   [
      "1",
      "1",
      "1",
      "1",
      "2",
      "9",
      "90",
      "25"
   ],
   [
      "1",
      "1",
      "0",
      "1",
      "2",
      "6",
      "20",
      "10"
   ],
   [
      "1",
      "1",
      "1",
      "4",
      "2",
      "11",
      "80",
      "30"
   ],
   [
      "1",
      "0",
      "0",
      "3",
      "2",
      "10",
      "40",
      "20"
   ],
   [
      "1",
      "0",
      "0",
      "4",
      "2",
      "18",
      "200",
      "60"
   ],
   [
      "1",
      "0",
      "0",
      "2",
      "2",
      "17",
      "150",
      "60"
   ],
   [
      "0",
      "0",
      "1",
      "2",
      "1",
      "5",
      "25",
      "10"
   ]
]
