var OverdoseInfo ={
   "usage" : "data(\"Overdose\")",
   "description" : "Description\nData on overdoses of the drug amitriptyline.\nAmitriptyline is a drug prescribed by physicians as an antidepressant. However, there are also \nconjectured side effects that seem to be related to the use of the drug: irregular heart beat,\nabnormal blood pressure and irregular waves on the electrocardiogram (ECG).\nThis dataset (originally from Rudorfer, 1982) gives data on 17 patients admitted to hospital after an overdose \nof amitriptyline.\nThe two response variables are: TCAD and AMI. The other variables are predictors.",
   "title" : "Overdose of Amitriptyline",
   "format" : "A data frame with 17 observations on the following 7 variables.",
   "reference" : "Johnson & Wichern (2005), Applied Multivariate Statistical Analysis,\nExercise 7.25, p. 426.",
   "parameters" : {
      "ECG_QRS" : "ECG QRS wave measurement, a numeric vector",
      "TCAD" : "total TCAD plasma level, a numeric vector",
      "BP" : "diastolic blood pressure, a numeric vector",
      "AMI" : "amount of amitriptyline present in the TCAD plasma level, a numeric vector",
      "Gender" : "a factor with levels Male Female",
      "ECG_PR" : "ECG PR wave measurement, a numeric vector",
      "amount" : "amount of drug taken at time of overdose, a numeric vector"
   }
}

var Overdose = [
   [
      "TCAD",
      "AMI",
      "Gender",
      "amount",
      "BP",
      "ECG_PR",
      "ECG_QRS"
   ],
   [
      "3389",
      "3149",
      "Female",
      "7500",
      "0",
      "220",
      "140"
   ],
   [
      "1101",
      "653",
      "Female",
      "1975",
      "0",
      "200",
      "100"
   ],
   [
      "1131",
      "810",
      "Male",
      "3600",
      "60",
      "205",
      "111"
   ],
   [
      "596",
      "448",
      "Female",
      "675",
      "60",
      "160",
      "120"
   ],
   [
      "896",
      "844",
      "Female",
      "750",
      "70",
      "185",
      "83"
   ],
   [
      "1767",
      "1450",
      "Female",
      "2500",
      "60",
      "180",
      "80"
   ],
   [
      "807",
      "493",
      "Female",
      "350",
      "80",
      "154",
      "98"
   ],
   [
      "1111",
      "941",
      "Male",
      "1500",
      "70",
      "200",
      "93"
   ],
   [
      "645",
      "547",
      "Female",
      "375",
      "60",
      "137",
      "105"
   ],
   [
      "628",
      "392",
      "Female",
      "1050",
      "60",
      "167",
      "74"
   ],
   [
      "1360",
      "1283",
      "Female",
      "3000",
      "60",
      "180",
      "80"
   ],
   [
      "652",
      "458",
      "Female",
      "450",
      "64",
      "160",
      "60"
   ],
   [
      "860",
      "722",
      "Female",
      "1750",
      "90",
      "135",
      "79"
   ],
   [
      "500",
      "384",
      "Male",
      "2000",
      "60",
      "160",
      "80"
   ],
   [
      "781",
      "501",
      "Male",
      "4500",
      "0",
      "180",
      "100"
   ],
   [
      "1070",
      "405",
      "Male",
      "1500",
      "90",
      "170",
      "120"
   ],
   [
      "1754",
      "1520",
      "Female",
      "3000",
      "0",
      "180",
      "129"
   ]
]
