var PlasticInfo ={
   "title" : "Plastic Film Data",
   "description" : "Description\nAn experiment was conducted to determine the optimum conditions for\nextruding plastic film.  Three responses were measured in relation to two\nfactors, rate of extrusion and amount of an additive.",
   "reference" : "Johnson, R.A. & Wichern, D.W. (1992). Applied Multivariate\nStatistical Analysis, 3rd ed., Prentice-Hall. Example 6.12 (p. 266).",
   "usage" : "A data frame with 20 observations on the following 5 variables.",
   "parameters" : {
      "rate" : "a factor representing change in the rate of extrusion with levels Low (-10%), High (10%)",
      "opacity" : "a numeric vector: film opacity",
      "tear" : "a numeric vector: tear resistance",
      "gloss" : "a numeric vector: film gloss",
      "additive" : "a factor with levels Low (1.0%), High (1.5%)"
   }
}

var Plastic = [
   [
      "tear",
      "gloss",
      "opacity",
      "rate",
      "additive"
   ],
   [
      "6.5",
      "9.5",
      "4.4",
      "Low",
      "Low"
   ],
   [
      "6.2",
      "9.9",
      "6.4",
      "Low",
      "Low"
   ],
   [
      "5.8",
      "9.6",
      "3",
      "Low",
      "Low"
   ],
   [
      "6.5",
      "9.6",
      "4.1",
      "Low",
      "Low"
   ],
   [
      "6.5",
      "9.2",
      "0.8",
      "Low",
      "Low"
   ],
   [
      "6.9",
      "9.1",
      "5.7",
      "Low",
      "High"
   ],
   [
      "7.2",
      "10",
      "2",
      "Low",
      "High"
   ],
   [
      "6.9",
      "9.9",
      "3.9",
      "Low",
      "High"
   ],
   [
      "6.1",
      "9.5",
      "1.9",
      "Low",
      "High"
   ],
   [
      "6.3",
      "9.4",
      "5.7",
      "Low",
      "High"
   ],
   [
      "6.7",
      "9.1",
      "2.8",
      "High",
      "Low"
   ],
   [
      "6.6",
      "9.3",
      "4.1",
      "High",
      "Low"
   ],
   [
      "7.2",
      "8.3",
      "3.8",
      "High",
      "Low"
   ],
   [
      "7.1",
      "8.4",
      "1.6",
      "High",
      "Low"
   ],
   [
      "6.8",
      "8.5",
      "3.4",
      "High",
      "Low"
   ],
   [
      "7.1",
      "9.2",
      "8.4",
      "High",
      "High"
   ],
   [
      "7",
      "8.8",
      "5.2",
      "High",
      "High"
   ],
   [
      "7.2",
      "9.7",
      "6.9",
      "High",
      "High"
   ],
   [
      "7.5",
      "10.1",
      "2.7",
      "High",
      "High"
   ],
   [
      "7.6",
      "9.2",
      "1.9",
      "High",
      "High"
   ]
]
