var Probe2Info ={
   "title" : "Response Speed in a Probe Experiment",
   "reference" : "Procedure: Subjects listened to tape-recorded sentences.  Each sentence was\nfollowed by a \"probe word\" from one of 5 positions within the sentence.  The\nsubject had to respond with the word which immediately followed the probe\nword in the sentence.  The dependent measure is response speed =\nk(1/reaction time).",
   "usage" : "Probe1: A data frame with 11 observations on the following 5 variables.",
   "parameters" : {
      "p2" : "speed at position 2",
      "p3" : "speed at position 3",
      "p4" : "speed at position 4",
      "p5" : "speed at position 5",
      "p1" : "speed at position 1"
   },
   "description" : "Description\nData from a probe experiment testing whether immediate memory for sentences\nis influenced by the phrase structure of the sentence.  The data sets come\nfrom Timm (1975), Ex. 3.14 and Ex. 3.16 (p.244)"
}

var Probe2 = [
   [
      "stm",
      "p1",
      "p2",
      "p3",
      "p4",
      "p5"
   ],
   [
      "Low",
      "20",
      "21",
      "42",
      "32",
      "32"
   ],
   [
      "Low",
      "67",
      "29",
      "56",
      "39",
      "41"
   ],
   [
      "Low",
      "37",
      "25",
      "28",
      "31",
      "34"
   ],
   [
      "Low",
      "42",
      "38",
      "36",
      "19",
      "35"
   ],
   [
      "Low",
      "57",
      "32",
      "21",
      "30",
      "29"
   ],
   [
      "Low",
      "39",
      "38",
      "54",
      "31",
      "28"
   ],
   [
      "Low",
      "43",
      "20",
      "46",
      "42",
      "31"
   ],
   [
      "Low",
      "35",
      "34",
      "43",
      "35",
      "42"
   ],
   [
      "Low",
      "41",
      "23",
      "51",
      "27",
      "30"
   ],
   [
      "Low",
      "39",
      "24",
      "35",
      "26",
      "32"
   ],
   [
      "High",
      "47",
      "25",
      "36",
      "21",
      "27"
   ],
   [
      "High",
      "53",
      "32",
      "48",
      "46",
      "54"
   ],
   [
      "High",
      "38",
      "33",
      "42",
      "48",
      "49"
   ],
   [
      "High",
      "60",
      "41",
      "67",
      "53",
      "50"
   ],
   [
      "High",
      "37",
      "35",
      "45",
      "34",
      "46"
   ],
   [
      "High",
      "59",
      "37",
      "52",
      "36",
      "52"
   ],
   [
      "High",
      "67",
      "33",
      "61",
      "31",
      "50"
   ],
   [
      "High",
      "43",
      "27",
      "36",
      "33",
      "32"
   ],
   [
      "High",
      "64",
      "53",
      "62",
      "40",
      "43"
   ],
   [
      "High",
      "41",
      "34",
      "47",
      "37",
      "46"
   ]
]
