var Dyestuff2Info ={
   "reference" : "The Dyestuff data are described in Davies and\nGoldsmith (1972) as coming from &ldquo;an investigation\nto find out how much the variation from batch to batch in\nthe quality of an intermediate product (H-acid)\ncontributes to the variation in the yield of the dyestuff\n(Naphthalene Black 12B) made from it.  In the experiment\nsix samples of the intermediate, representing different\nbatches of works manufacture, were obtained, and five\npreparations of the dyestuff were made in the laboratory\nfrom each sample. The equivalent yield of each\npreparation as grams of standard colour was determined by\ndye-trial.&rdquo;",
   "usage" : "Data frames, each with 30 observations on the following 2 variables.",
   "title" : "Yield of dyestuff by batch",
   "description" : "Description\nThe Dyestuff data frame provides the yield of\ndyestuff (Naphthalene Black 12B) from 5 different\npreparations from each of 6 different batchs of an\nintermediate product (H-acid).  The Dyestuff2 data\nwere generated data in the same structure but with a\nlarge residual variance relative to the batch variance.",
   "parameters" : {
      "Batch" : "a factor indicating the batch of the\nintermediate product from which the preparation was created.",
      "Yield" : "the yield of dyestuff from the preparation\n(grams of standard color)."
   }
}

var Dyestuff2 = [
   [
      "Batch",
      "Yield"
   ],
   [
      "A",
      "7.298"
   ],
   [
      "A",
      "3.846"
   ],
   [
      "A",
      "2.434"
   ],
   [
      "A",
      "9.566"
   ],
   [
      "A",
      "7.99"
   ],
   [
      "B",
      "5.22"
   ],
   [
      "B",
      "6.556"
   ],
   [
      "B",
      "0.608"
   ],
   [
      "B",
      "11.788"
   ],
   [
      "B",
      "-0.892"
   ],
   [
      "C",
      "0.11"
   ],
   [
      "C",
      "10.386"
   ],
   [
      "C",
      "13.434"
   ],
   [
      "C",
      "5.51"
   ],
   [
      "C",
      "8.166"
   ],
   [
      "D",
      "2.212"
   ],
   [
      "D",
      "4.852"
   ],
   [
      "D",
      "7.092"
   ],
   [
      "D",
      "9.288"
   ],
   [
      "D",
      "4.98"
   ],
   [
      "E",
      "0.282"
   ],
   [
      "E",
      "9.014"
   ],
   [
      "E",
      "4.458"
   ],
   [
      "E",
      "9.446"
   ],
   [
      "E",
      "7.198"
   ],
   [
      "F",
      "1.722"
   ],
   [
      "F",
      "4.782"
   ],
   [
      "F",
      "8.106"
   ],
   [
      "F",
      "0.758"
   ],
   [
      "F",
      "3.758"
   ]
]
