var amlInfo ={
   "usage" : "aml",
   "description" : "Description\nThe aml data frame has 23 rows and 3 columns.\nA clinical trial to evaluate the efficacy of maintenance chemotherapy for\nacute myelogenous leukaemia was \nconducted by Embury et al. (1977) at Stanford University.  After reaching a\nstage of remission through treatment by chemotherapy, patients were randomized\ninto two groups. The first group received maintenance chemotherapy and the \nsecond group did not.  The aim of the study was to see if maintenance \nchemotherapy increased the length of the remission.  The data here formed a\npreliminary analysis which was conducted in October 1974.",
   "format" : "This data frame contains the following columns:",
   "title" : "Remission Times for Acute Myelogenous Leukaemia",
   "reference" : "Package survival also has a dataset aml. It is the same\ndata with different names and with group replaced by a factor\nx.",
   "parameters" : {
      "group" : "The group into which the patient was randomized.  Group 1 received\nmaintenance chemotherapy, group 2 did not.",
      "cens" : "An indicator of right censoring.  1 indicates that the patient had a relapse\nand so time is the length of the remission. 0 indicates that the patient\nhad left the study or was still in remission in October 1974, that is the\nlength of remission is right-censored.",
      "time" : "The length of the complete remission (in weeks)."
   }
}

var aml = [
   [
      "time",
      "cens",
      "group"
   ],
   [
      "9",
      "1",
      "1"
   ],
   [
      "13",
      "1",
      "1"
   ],
   [
      "13",
      "0",
      "1"
   ],
   [
      "18",
      "1",
      "1"
   ],
   [
      "23",
      "1",
      "1"
   ],
   [
      "28",
      "0",
      "1"
   ],
   [
      "31",
      "1",
      "1"
   ],
   [
      "34",
      "1",
      "1"
   ],
   [
      "45",
      "0",
      "1"
   ],
   [
      "48",
      "1",
      "1"
   ],
   [
      "161",
      "0",
      "1"
   ],
   [
      "5",
      "1",
      "2"
   ],
   [
      "5",
      "1",
      "2"
   ],
   [
      "8",
      "1",
      "2"
   ],
   [
      "8",
      "1",
      "2"
   ],
   [
      "12",
      "1",
      "2"
   ],
   [
      "16",
      "0",
      "2"
   ],
   [
      "23",
      "1",
      "2"
   ],
   [
      "27",
      "1",
      "2"
   ],
   [
      "30",
      "1",
      "2"
   ],
   [
      "33",
      "1",
      "2"
   ],
   [
      "43",
      "1",
      "2"
   ],
   [
      "45",
      "1",
      "2"
   ]
]
