var salinityInfo ={
   "format" : "This data frame contains the following columns:",
   "parameters" : {
      "trend" : "A factor indicating in which of the 6 biweekly periods between March and May,\nthe observations were taken. The levels of the factor are from 0 to 5 with\n0 being the first two weeks in March.",
      "sal" : "The average salinity of the water over two weeks.",
      "lag" : "The average salinity of the water lagged two weeks.  Since only spring is used,\nthe value of lag is not always equal to the previous value of sal.",
      "dis" : "The amount of river discharge during the two weeks for which sal is the\naverage salinity."
   },
   "description" : "Description\nThe salinity data frame has 28 rows and 4 columns.\nBiweekly averages of the water salinity and river discharge in Pamlico\nSound, North Carolina were recorded between the years 1972 and 1977.\nThe data in this set consists only of those measurements in March, April\nand May.",
   "title" : "Water Salinity and River Discharge",
   "reference" : "The data were obtained from",
   "usage" : "salinity"
}

var salinity = [
   [
      "sal",
      "lag",
      "trend",
      "dis"
   ],
   [
      "7.6",
      "8.2",
      "4",
      "23.01"
   ],
   [
      "7.7",
      "7.6",
      "5",
      "22.87"
   ],
   [
      "4.3",
      "4.6",
      "0",
      "26.42"
   ],
   [
      "5.9",
      "4.3",
      "1",
      "24.87"
   ],
   [
      "5",
      "5.9",
      "2",
      "29.9"
   ],
   [
      "6.5",
      "5",
      "3",
      "24.2"
   ],
   [
      "8.3",
      "6.5",
      "4",
      "23.22"
   ],
   [
      "8.2",
      "8.3",
      "5",
      "22.86"
   ],
   [
      "13.2",
      "10.1",
      "0",
      "22.27"
   ],
   [
      "12.6",
      "13.2",
      "1",
      "23.83"
   ],
   [
      "10.4",
      "12.6",
      "2",
      "25.14"
   ],
   [
      "10.8",
      "10.4",
      "3",
      "22.43"
   ],
   [
      "13.1",
      "10.8",
      "4",
      "21.79"
   ],
   [
      "12.3",
      "13.1",
      "5",
      "22.38"
   ],
   [
      "10.4",
      "13.3",
      "0",
      "23.93"
   ],
   [
      "10.5",
      "10.4",
      "1",
      "33.44"
   ],
   [
      "7.7",
      "10.5",
      "2",
      "24.86"
   ],
   [
      "9.5",
      "7.7",
      "3",
      "22.69"
   ],
   [
      "12",
      "10",
      "0",
      "21.79"
   ],
   [
      "12.6",
      "12",
      "1",
      "22.04"
   ],
   [
      "13.6",
      "12.1",
      "4",
      "21.03"
   ],
   [
      "14.1",
      "13.6",
      "5",
      "21.01"
   ],
   [
      "13.5",
      "15",
      "0",
      "25.87"
   ],
   [
      "11.5",
      "13.5",
      "1",
      "26.29"
   ],
   [
      "12",
      "11.5",
      "2",
      "22.93"
   ],
   [
      "13",
      "12",
      "3",
      "21.31"
   ],
   [
      "14.1",
      "13",
      "4",
      "20.77"
   ],
   [
      "15.1",
      "14.1",
      "5",
      "21.39"
   ]
]
