var tauInfo ={
   "description" : "Description\nThe tau data frame has 60 rows and 2 columns.\nThe tau particle is a heavy electron-like particle discovered in the 1970's\nby Martin Perl at the Stanford Linear Accelerator Center.  Soon after its\nproduction the tau particle decays into various collections of more stable\nparticles.  About 86% of the time the decay involves just one charged particle.\nThis rate has been measured independently 13 times.\nThe one-charged-particle event is made up of four major modes of decay as well\nas a collection of other events.  The four main types of decay are denoted\nrho, pi, e and mu.  These rates have been measured independently 6, 7, 14 and\n19 times respectively.  Due to physical constraints each experiment can only\nestimate the composite one-charged-particle decay rate or the rate of one of\nthe major modes of decay.\nEach experiment consists of a major research project involving many years work.\nOne of the goals of the experiments was to estimate the rate of decay due to \nevents other than the four main modes of decay.  These are uncertain events and\nso cannot themselves be observed directly.",
   "title" : "Tau Particle Decay Modes",
   "reference" : "The data were obtained from",
   "usage" : "tau",
   "parameters" : {
      "rate" : "The decay rate expressed as a percentage.",
      "decay" : "The type of decay measured in the experiment.  It is a factor with levels\n1, rho, pi, e and mu."
   },
   "format" : "This data frame contains the following columns:"
}

var tau = [
   [
      "rate",
      "decay"
   ],
   [
      "84",
      "1"
   ],
   [
      "84.7",
      "1"
   ],
   [
      "84.7",
      "1"
   ],
   [
      "85.1",
      "1"
   ],
   [
      "85.2",
      "1"
   ],
   [
      "85.2",
      "1"
   ],
   [
      "86",
      "1"
   ],
   [
      "86.1",
      "1"
   ],
   [
      "86.7",
      "1"
   ],
   [
      "86.9",
      "1"
   ],
   [
      "87.2",
      "1"
   ],
   [
      "87.8",
      "1"
   ],
   [
      "87.9",
      "1"
   ],
   [
      "20.5",
      "rho"
   ],
   [
      "22.1",
      "rho"
   ],
   [
      "22.3",
      "rho"
   ],
   [
      "22.3",
      "rho"
   ],
   [
      "22.6",
      "rho"
   ],
   [
      "24",
      "rho"
   ],
   [
      "8",
      "pi"
   ],
   [
      "9",
      "pi"
   ],
   [
      "9.9",
      "pi"
   ],
   [
      "10",
      "pi"
   ],
   [
      "10.7",
      "pi"
   ],
   [
      "11.7",
      "pi"
   ],
   [
      "11.8",
      "pi"
   ],
   [
      "13",
      "e"
   ],
   [
      "16",
      "e"
   ],
   [
      "17",
      "e"
   ],
   [
      "17.4",
      "e"
   ],
   [
      "17.6",
      "e"
   ],
   [
      "18.2",
      "e"
   ],
   [
      "18.2",
      "e"
   ],
   [
      "18.3",
      "e"
   ],
   [
      "18.4",
      "e"
   ],
   [
      "18.9",
      "e"
   ],
   [
      "19",
      "e"
   ],
   [
      "19.1",
      "e"
   ],
   [
      "20.4",
      "e"
   ],
   [
      "22.4",
      "e"
   ],
   [
      "12.9",
      "mu"
   ],
   [
      "15",
      "mu"
   ],
   [
      "17.1",
      "mu"
   ],
   [
      "17.4",
      "mu"
   ],
   [
      "17.5",
      "mu"
   ],
   [
      "17.6",
      "mu"
   ],
   [
      "17.7",
      "mu"
   ],
   [
      "17.7",
      "mu"
   ],
   [
      "17.8",
      "mu"
   ],
   [
      "18",
      "mu"
   ],
   [
      "18.2",
      "mu"
   ],
   [
      "18.3",
      "mu"
   ],
   [
      "18.3",
      "mu"
   ],
   [
      "18.8",
      "mu"
   ],
   [
      "19.4",
      "mu"
   ],
   [
      "21",
      "mu"
   ],
   [
      "22",
      "mu"
   ],
   [
      "22",
      "mu"
   ],
   [
      "22.4",
      "mu"
   ],
   [
      "35",
      "mu"
   ]
]
