var AccidentInfo ={
   "usage" : "data(Accident)",
   "description" : "Description\nBertin (1983) used these data to illustrate the cross-classification of \ndata by numerous variables, each of which could have various types\nand could be assigned to various visual attributes.\nFor modeling and visualization purposes, the data can be treated as a\n4-way table using loglinear models and mosaic displays, or as a \nfrequency-weighted data frame using a binomial response for\nresult (\"Died\" vs. \"Injured\") and plots of\npredicted probabilities.",
   "format" : "A data frame in frequency form (comprising a 5 x 2 x 4 x 2 table)\nwith 80 observations on the following 5 variables.",
   "title" : "Traffic Accident Victims in France in 1958",
   "reference" : "age is an ordered factor, but arguably, mode should be treated as ordered, with levels\nPedestrian < Bicycle < Motorcycle < 4-Wheeled \nas Bertin does.  This affects the parameterization in models, so we don't do this directly in the\ndata frame.",
   "parameters" : {
      "Freq" : "a numeric vector",
      "age" : "an ordered factor with levels 0-9 < 10-19 < 20-29 < 30-49 < 50+",
      "mode" : "mode of transportation,\na factor with levels 4-Wheeled Bicycle Motorcycle Pedestrian",
      "result" : "a factor with levels Died Injured",
      "gender" : "a factor with levels Female Male"
   }
}

var Accident = [
   [
      "age",
      "result",
      "mode",
      "gender",
      "Freq"
   ],
   [
      "50+",
      "Died",
      "Pedestrian",
      "Male",
      "704"
   ],
   [
      "50+",
      "Died",
      "Pedestrian",
      "Female",
      "378"
   ],
   [
      "50+",
      "Died",
      "Bicycle",
      "Male",
      "396"
   ],
   [
      "50+",
      "Died",
      "Bicycle",
      "Female",
      "56"
   ],
   [
      "50+",
      "Died",
      "Motorcycle",
      "Male",
      "742"
   ],
   [
      "50+",
      "Died",
      "Motorcycle",
      "Female",
      "78"
   ],
   [
      "50+",
      "Died",
      "4-Wheeled",
      "Male",
      "513"
   ],
   [
      "50+",
      "Died",
      "4-Wheeled",
      "Female",
      "253"
   ],
   [
      "50+",
      "Injured",
      "Pedestrian",
      "Male",
      "5206"
   ],
   [
      "50+",
      "Injured",
      "Pedestrian",
      "Female",
      "5449"
   ],
   [
      "50+",
      "Injured",
      "Bicycle",
      "Male",
      "3863"
   ],
   [
      "50+",
      "Injured",
      "Bicycle",
      "Female",
      "1030"
   ],
   [
      "50+",
      "Injured",
      "Motorcycle",
      "Male",
      "8597"
   ],
   [
      "50+",
      "Injured",
      "Motorcycle",
      "Female",
      "1387"
   ],
   [
      "50+",
      "Injured",
      "4-Wheeled",
      "Male",
      "7423"
   ],
   [
      "50+",
      "Injured",
      "4-Wheeled",
      "Female",
      "5552"
   ],
   [
      "30-49",
      "Died",
      "Pedestrian",
      "Male",
      "223"
   ],
   [
      "30-49",
      "Died",
      "Pedestrian",
      "Female",
      "49"
   ],
   [
      "30-49",
      "Died",
      "Bicycle",
      "Male",
      "146"
   ],
   [
      "30-49",
      "Died",
      "Bicycle",
      "Female",
      "24"
   ],
   [
      "30-49",
      "Died",
      "Motorcycle",
      "Male",
      "889"
   ],
   [
      "30-49",
      "Died",
      "Motorcycle",
      "Female",
      "98"
   ],
   [
      "30-49",
      "Died",
      "4-Wheeled",
      "Male",
      "720"
   ],
   [
      "30-49",
      "Died",
      "4-Wheeled",
      "Female",
      "199"
   ],
   [
      "30-49",
      "Injured",
      "Pedestrian",
      "Male",
      "3178"
   ],
   [
      "30-49",
      "Injured",
      "Pedestrian",
      "Female",
      "1814"
   ],
   [
      "30-49",
      "Injured",
      "Bicycle",
      "Male",
      "3024"
   ],
   [
      "30-49",
      "Injured",
      "Bicycle",
      "Female",
      "1118"
   ],
   [
      "30-49",
      "Injured",
      "Motorcycle",
      "Male",
      "18909"
   ],
   [
      "30-49",
      "Injured",
      "Motorcycle",
      "Female",
      "3664"
   ],
   [
      "30-49",
      "Injured",
      "4-Wheeled",
      "Male",
      "15086"
   ],
   [
      "30-49",
      "Injured",
      "4-Wheeled",
      "Female",
      "7712"
   ],
   [
      "20-29",
      "Died",
      "Pedestrian",
      "Male",
      "78"
   ],
   [
      "20-29",
      "Died",
      "Pedestrian",
      "Female",
      "24"
   ],
   [
      "20-29",
      "Died",
      "Bicycle",
      "Male",
      "55"
   ],
   [
      "20-29",
      "Died",
      "Bicycle",
      "Female",
      "10"
   ],
   [
      "20-29",
      "Died",
      "Motorcycle",
      "Male",
      "660"
   ],
   [
      "20-29",
      "Died",
      "Motorcycle",
      "Female",
      "82"
   ],
   [
      "20-29",
      "Died",
      "4-Wheeled",
      "Male",
      "353"
   ],
   [
      "20-29",
      "Died",
      "4-Wheeled",
      "Female",
      "107"
   ],
   [
      "20-29",
      "Injured",
      "Pedestrian",
      "Male",
      "1521"
   ],
   [
      "20-29",
      "Injured",
      "Pedestrian",
      "Female",
      "864"
   ],
   [
      "20-29",
      "Injured",
      "Bicycle",
      "Male",
      "1565"
   ],
   [
      "20-29",
      "Injured",
      "Bicycle",
      "Female",
      "609"
   ],
   [
      "20-29",
      "Injured",
      "Motorcycle",
      "Male",
      "18558"
   ],
   [
      "20-29",
      "Injured",
      "Motorcycle",
      "Female",
      "4010"
   ],
   [
      "20-29",
      "Injured",
      "4-Wheeled",
      "Male",
      "9084"
   ],
   [
      "20-29",
      "Injured",
      "4-Wheeled",
      "Female",
      "4361"
   ],
   [
      "10-19",
      "Died",
      "Pedestrian",
      "Male",
      "70"
   ],
   [
      "10-19",
      "Died",
      "Pedestrian",
      "Female",
      "28"
   ],
   [
      "10-19",
      "Died",
      "Bicycle",
      "Male",
      "76"
   ],
   [
      "10-19",
      "Died",
      "Bicycle",
      "Female",
      "31"
   ],
   [
      "10-19",
      "Died",
      "Motorcycle",
      "Male",
      "362"
   ],
   [
      "10-19",
      "Died",
      "Motorcycle",
      "Female",
      "54"
   ],
   [
      "10-19",
      "Died",
      "4-Wheeled",
      "Male",
      "150"
   ],
   [
      "10-19",
      "Died",
      "4-Wheeled",
      "Female",
      "61"
   ],
   [
      "10-19",
      "Injured",
      "Pedestrian",
      "Male",
      "1827"
   ],
   [
      "10-19",
      "Injured",
      "Pedestrian",
      "Female",
      "1495"
   ],
   [
      "10-19",
      "Injured",
      "Bicycle",
      "Male",
      "3407"
   ],
   [
      "10-19",
      "Injured",
      "Bicycle",
      "Female",
      "7218"
   ],
   [
      "10-19",
      "Injured",
      "Motorcycle",
      "Male",
      "12311"
   ],
   [
      "10-19",
      "Injured",
      "Motorcycle",
      "Female",
      "3587"
   ],
   [
      "10-19",
      "Injured",
      "4-Wheeled",
      "Male",
      "3543"
   ],
   [
      "10-19",
      "Injured",
      "4-Wheeled",
      "Female",
      "2593"
   ],
   [
      "0-9",
      "Died",
      "Pedestrian",
      "Male",
      "150"
   ],
   [
      "0-9",
      "Died",
      "Pedestrian",
      "Female",
      "89"
   ],
   [
      "0-9",
      "Died",
      "Bicycle",
      "Male",
      "26"
   ],
   [
      "0-9",
      "Died",
      "Bicycle",
      "Female",
      "5"
   ],
   [
      "0-9",
      "Died",
      "Motorcycle",
      "Male",
      "6"
   ],
   [
      "0-9",
      "Died",
      "Motorcycle",
      "Female",
      "6"
   ],
   [
      "0-9",
      "Died",
      "4-Wheeled",
      "Male",
      "70"
   ],
   [
      "0-9",
      "Died",
      "4-Wheeled",
      "Female",
      "65"
   ],
   [
      "0-9",
      "Injured",
      "Pedestrian",
      "Male",
      "3341"
   ],
   [
      "0-9",
      "Injured",
      "Pedestrian",
      "Female",
      "1967"
   ],
   [
      "0-9",
      "Injured",
      "Bicycle",
      "Male",
      "378"
   ],
   [
      "0-9",
      "Injured",
      "Bicycle",
      "Female",
      "126"
   ],
   [
      "0-9",
      "Injured",
      "Motorcycle",
      "Male",
      "181"
   ],
   [
      "0-9",
      "Injured",
      "Motorcycle",
      "Female",
      "131"
   ],
   [
      "0-9",
      "Injured",
      "4-Wheeled",
      "Male",
      "1593"
   ],
   [
      "0-9",
      "Injured",
      "4-Wheeled",
      "Female",
      "1362"
   ]
]
