var BurtInfo ={
   "description" : "Description\nCyril Burt (1950) gave these data, on a sample of 100 people from Liverpool,\nto illustrate the application of a method of factor analysis (later\ncalled multiple correspondence analysis) applied to \ncategorical data.\nHe presented these data initially in the form that has come to be called a \"Burt table\",\ngiving the univariate and bivariate frequencies for an n-way frequency table.",
   "title" : "Burt (1950) Data on Hair, Eyes, Head and Stature",
   "reference" : "Burt says: \"In all, 217 individuals were examined, about two-thirds of them males.\nBut, partly to simplify the calculations and partly because the later observations were rather more trustworthy, \nI shall here restrict my analysis to the data obtained from the last hundred males in the series.\"",
   "usage" : "data(\"Burt\")",
   "parameters" : {
      "Freq" : "a numeric vector",
      "Eyes" : "eye color, a factor with levels Light Mixed Dark",
      "Stature" : "height, a factor with levels Tall Short",
      "Hair" : "hair color, a factor with levels Fair Red Dark",
      "Head" : "head shape, a factor with levels Narrow Wide"
   },
   "format" : "A frequency data frame (representing a 3 x 3 x 2 x 2 frequency table) with 36 cells on the following 5 variables."
}

var Burt = [
   [
      "Hair",
      "Eyes",
      "Head",
      "Stature",
      "Freq"
   ],
   [
      "Fair",
      "Light",
      "Narrow",
      "Tall",
      "8"
   ],
   [
      "Fair",
      "Light",
      "Narrow",
      "Short",
      "4"
   ],
   [
      "Fair",
      "Light",
      "Wide",
      "Tall",
      "2"
   ],
   [
      "Fair",
      "Light",
      "Wide",
      "Short",
      "0"
   ],
   [
      "Fair",
      "Mixed",
      "Narrow",
      "Tall",
      "1"
   ],
   [
      "Fair",
      "Mixed",
      "Narrow",
      "Short",
      "1"
   ],
   [
      "Fair",
      "Mixed",
      "Wide",
      "Tall",
      "2"
   ],
   [
      "Fair",
      "Mixed",
      "Wide",
      "Short",
      "2"
   ],
   [
      "Fair",
      "Dark",
      "Narrow",
      "Tall",
      "0"
   ],
   [
      "Fair",
      "Dark",
      "Narrow",
      "Short",
      "0"
   ],
   [
      "Fair",
      "Dark",
      "Wide",
      "Tall",
      "0"
   ],
   [
      "Fair",
      "Dark",
      "Wide",
      "Short",
      "2"
   ],
   [
      "Red",
      "Light",
      "Narrow",
      "Tall",
      "6"
   ],
   [
      "Red",
      "Light",
      "Narrow",
      "Short",
      "0"
   ],
   [
      "Red",
      "Light",
      "Wide",
      "Tall",
      "2"
   ],
   [
      "Red",
      "Light",
      "Wide",
      "Short",
      "0"
   ],
   [
      "Red",
      "Mixed",
      "Narrow",
      "Tall",
      "2"
   ],
   [
      "Red",
      "Mixed",
      "Narrow",
      "Short",
      "1"
   ],
   [
      "Red",
      "Mixed",
      "Wide",
      "Tall",
      "0"
   ],
   [
      "Red",
      "Mixed",
      "Wide",
      "Short",
      "2"
   ],
   [
      "Red",
      "Dark",
      "Narrow",
      "Tall",
      "0"
   ],
   [
      "Red",
      "Dark",
      "Narrow",
      "Short",
      "2"
   ],
   [
      "Red",
      "Dark",
      "Wide",
      "Tall",
      "0"
   ],
   [
      "Red",
      "Dark",
      "Wide",
      "Short",
      "0"
   ],
   [
      "Dark",
      "Light",
      "Narrow",
      "Tall",
      "9"
   ],
   [
      "Dark",
      "Light",
      "Narrow",
      "Short",
      "0"
   ],
   [
      "Dark",
      "Light",
      "Wide",
      "Tall",
      "2"
   ],
   [
      "Dark",
      "Light",
      "Wide",
      "Short",
      "0"
   ],
   [
      "Dark",
      "Mixed",
      "Narrow",
      "Tall",
      "3"
   ],
   [
      "Dark",
      "Mixed",
      "Narrow",
      "Short",
      "12"
   ],
   [
      "Dark",
      "Mixed",
      "Wide",
      "Tall",
      "2"
   ],
   [
      "Dark",
      "Mixed",
      "Wide",
      "Short",
      "8"
   ],
   [
      "Dark",
      "Dark",
      "Narrow",
      "Tall",
      "1"
   ],
   [
      "Dark",
      "Dark",
      "Narrow",
      "Short",
      "19"
   ],
   [
      "Dark",
      "Dark",
      "Wide",
      "Tall",
      "3"
   ],
   [
      "Dark",
      "Dark",
      "Wide",
      "Short",
      "4"
   ]
]
