var GlassInfo ={
   "format" : "A frequency data frame with 25 observations on the following 3 variables representing a 5 x 5 table with 3500 cases.",
   "parameters" : {
      "Freq" : "a numeric vector",
      "son" : "a factor with levels Managerial Professional Skilled Supervisory Unskilled",
      "father" : "a factor with levels Managerial Professional Skilled Supervisory Unskilled"
   },
   "usage" : "data(\"Glass\")",
   "reference" : "The occupational categories in order of status are:\n(1) Professional & High Administrative\n(2) Managerial, Executive & High Supervisory\n(3) Low Inspectional & Supervisory\n(4) Routine Nonmanual & Skilled Manual\n(5) Semi- & Unskilled Manual",
   "description" : "Description\nGlass(1954) gave this 5 x 5 table on the occupations of 3500 British fathers and their sons.",
   "title" : "British Social Mobility from Glass(1954)"
}

var Glass = [
   [
      "father",
      "son",
      "Freq"
   ],
   [
      "Professional",
      "Professional",
      "50"
   ],
   [
      "Professional",
      "Managerial",
      "45"
   ],
   [
      "Professional",
      "Supervisory",
      "8"
   ],
   [
      "Professional",
      "Skilled",
      "18"
   ],
   [
      "Professional",
      "Unskilled",
      "8"
   ],
   [
      "Managerial",
      "Professional",
      "28"
   ],
   [
      "Managerial",
      "Managerial",
      "174"
   ],
   [
      "Managerial",
      "Supervisory",
      "84"
   ],
   [
      "Managerial",
      "Skilled",
      "154"
   ],
   [
      "Managerial",
      "Unskilled",
      "55"
   ],
   [
      "Supervisory",
      "Professional",
      "11"
   ],
   [
      "Supervisory",
      "Managerial",
      "78"
   ],
   [
      "Supervisory",
      "Supervisory",
      "110"
   ],
   [
      "Supervisory",
      "Skilled",
      "223"
   ],
   [
      "Supervisory",
      "Unskilled",
      "96"
   ],
   [
      "Skilled",
      "Professional",
      "14"
   ],
   [
      "Skilled",
      "Managerial",
      "150"
   ],
   [
      "Skilled",
      "Supervisory",
      "185"
   ],
   [
      "Skilled",
      "Skilled",
      "714"
   ],
   [
      "Skilled",
      "Unskilled",
      "447"
   ],
   [
      "Unskilled",
      "Professional",
      "3"
   ],
   [
      "Unskilled",
      "Managerial",
      "42"
   ],
   [
      "Unskilled",
      "Supervisory",
      "72"
   ],
   [
      "Unskilled",
      "Skilled",
      "320"
   ],
   [
      "Unskilled",
      "Unskilled",
      "411"
   ]
]
