var Hauser79Info ={
   "usage" : "data(Hauser79)",
   "description" : "Description\nHauser (1979) presented this two-way frequency table,\ncross-classifying occupational categories of sons and fathers\nin the United States.\nIt is a good example for exploring a variety of models for square tables:\nquasi-independence, quasi-symmetry, row/column effects, uniform association, etc.,\nusing the facilities of the gnm.",
   "reference" : "Hauser's data was first presented in 1979, and then published in 1980. The name of the\ndataset reflects the earliest use.",
   "format" : "A frequency data frame with 25 observations on the following 3 variables, representing the\ncross-classification of 19912 individuals by father's occupation and son's first occupation.",
   "title" : "Hauser (1979) Data on Social Mobility",
   "parameters" : {
      "Freq" : "a numeric vector",
      "Father" : "a factor with levels UpNM LoNM UpM LoM Farm",
      "Son" : "a factor with levels UpNM LoNM UpM LoM Farm"
   }
}

var Hauser79 = [
   [
      "Son",
      "Father",
      "Freq"
   ],
   [
      "UpNM",
      "UpNM",
      "1414"
   ],
   [
      "LoNM",
      "UpNM",
      "521"
   ],
   [
      "UpM",
      "UpNM",
      "302"
   ],
   [
      "LoM",
      "UpNM",
      "643"
   ],
   [
      "Farm",
      "UpNM",
      "40"
   ],
   [
      "UpNM",
      "LoNM",
      "724"
   ],
   [
      "LoNM",
      "LoNM",
      "524"
   ],
   [
      "UpM",
      "LoNM",
      "254"
   ],
   [
      "LoM",
      "LoNM",
      "703"
   ],
   [
      "Farm",
      "LoNM",
      "48"
   ],
   [
      "UpNM",
      "UpM",
      "798"
   ],
   [
      "LoNM",
      "UpM",
      "648"
   ],
   [
      "UpM",
      "UpM",
      "856"
   ],
   [
      "LoM",
      "UpM",
      "1676"
   ],
   [
      "Farm",
      "UpM",
      "108"
   ],
   [
      "UpNM",
      "LoM",
      "756"
   ],
   [
      "LoNM",
      "LoM",
      "914"
   ],
   [
      "UpM",
      "LoM",
      "771"
   ],
   [
      "LoM",
      "LoM",
      "3325"
   ],
   [
      "Farm",
      "LoM",
      "237"
   ],
   [
      "UpNM",
      "Farm",
      "409"
   ],
   [
      "LoNM",
      "Farm",
      "357"
   ],
   [
      "UpM",
      "Farm",
      "441"
   ],
   [
      "LoM",
      "Farm",
      "1611"
   ],
   [
      "Farm",
      "Farm",
      "1832"
   ]
]
