var HeartInfo ={
   "format" : "A 3-dimensional array resulting from cross-tabulating 3 variables for 21522 observations. The variable names and their levels are:",
   "title" : "Sex, Occupation and Heart Disease",
   "description" : "Description\nClassification of individuals by gender, occupational category and occurrence of heart disease",
   "usage" : "data(Heart)"
}

var Heart = [
   [
      "Disease",
      "Gender",
      "Occup",
      "Freq"
   ],
   [
      "Disease",
      "Male",
      "Unempl",
      "254"
   ],
   [
      "None",
      "Male",
      "Unempl",
      "759"
   ],
   [
      "Disease",
      "Female",
      "Unempl",
      "431"
   ],
   [
      "None",
      "Female",
      "Unempl",
      "10283"
   ],
   [
      "Disease",
      "Male",
      "WhiteCol",
      "158"
   ],
   [
      "None",
      "Male",
      "WhiteCol",
      "3155"
   ],
   [
      "Disease",
      "Female",
      "WhiteCol",
      "52"
   ],
   [
      "None",
      "Female",
      "WhiteCol",
      "3082"
   ],
   [
      "Disease",
      "Male",
      "BlueCol",
      "87"
   ],
   [
      "None",
      "Male",
      "BlueCol",
      "2829"
   ],
   [
      "Disease",
      "Female",
      "BlueCol",
      "16"
   ],
   [
      "None",
      "Female",
      "BlueCol",
      "416"
   ]
]
