var MentalInfo ={
   "usage" : "data(Mental)",
   "description" : "Description\nA 6 x 4 contingency table representing the cross-classification of\nmental health status (mental) of 1660 young New York residents by\ntheir parents' socioeconomic status (ses).",
   "reference" : "Both ses and mental can be treated as ordered factors or\ninteger scores.  For ses, 1=\"High\" and 6=\"Low\".",
   "format" : "A data frame frequency table with 24 observations on the following 3 variables.",
   "title" : "Mental Impairment and Parents SES",
   "parameters" : {
      "mental" : "an ordered factor with levels Well < Mild < Moderate < Impaired",
      "ses" : "an ordered factor with levels 1 < 2 < 3 < 4 < 5 < 6",
      "Freq" : "cell frequency: a numeric vector"
   }
}

var Mental = [
   [
      "ses",
      "mental",
      "Freq"
   ],
   [
      "1",
      "Well",
      "64"
   ],
   [
      "1",
      "Mild",
      "94"
   ],
   [
      "1",
      "Moderate",
      "58"
   ],
   [
      "1",
      "Impaired",
      "46"
   ],
   [
      "2",
      "Well",
      "57"
   ],
   [
      "2",
      "Mild",
      "94"
   ],
   [
      "2",
      "Moderate",
      "54"
   ],
   [
      "2",
      "Impaired",
      "40"
   ],
   [
      "3",
      "Well",
      "57"
   ],
   [
      "3",
      "Mild",
      "105"
   ],
   [
      "3",
      "Moderate",
      "65"
   ],
   [
      "3",
      "Impaired",
      "60"
   ],
   [
      "4",
      "Well",
      "72"
   ],
   [
      "4",
      "Mild",
      "141"
   ],
   [
      "4",
      "Moderate",
      "77"
   ],
   [
      "4",
      "Impaired",
      "94"
   ],
   [
      "5",
      "Well",
      "36"
   ],
   [
      "5",
      "Mild",
      "97"
   ],
   [
      "5",
      "Moderate",
      "54"
   ],
   [
      "5",
      "Impaired",
      "78"
   ],
   [
      "6",
      "Well",
      "21"
   ],
   [
      "6",
      "Mild",
      "71"
   ],
   [
      "6",
      "Moderate",
      "54"
   ],
   [
      "6",
      "Impaired",
      "71"
   ]
]
