var Vote1980Info ={
   "usage" : "data(Vote1980)",
   "description" : "Description\nData from the 1982 General Social Survey on votes in the 1980 U.S.\npresidential election in relation to race and political \nconservatism.",
   "format" : "A frequency data frame representing a 2 x 7 x 2 table, with 28 observations on the following 4 variables.",
   "reference" : "The data contains a number of sampling zeros in the frequencies of\nNonWhites voting for Ronald Reagan.",
   "title" : "Race and Politics in the 1980 Presidential Vote",
   "parameters" : {
      "votefor" : "a factor with levels Carter Reagan; Carter \nrepresents Jimmy Carter or other.",
      "race" : "a factor with levels NonWhite White",
      "conservatism" : "a factor with levels 1 2 3 4 5 6 7,\n1=most liberal, 7=most conservative",
      "Freq" : "a numeric vector"
   }
}

var Vote1980 = [
   [
      "race",
      "conservatism",
      "votefor",
      "Freq"
   ],
   [
      "White",
      "1",
      "Reagan",
      "1"
   ],
   [
      "White",
      "1",
      "Carter",
      "12"
   ],
   [
      "White",
      "2",
      "Reagan",
      "13"
   ],
   [
      "White",
      "2",
      "Carter",
      "57"
   ],
   [
      "White",
      "3",
      "Reagan",
      "44"
   ],
   [
      "White",
      "3",
      "Carter",
      "71"
   ],
   [
      "White",
      "4",
      "Reagan",
      "155"
   ],
   [
      "White",
      "4",
      "Carter",
      "146"
   ],
   [
      "White",
      "5",
      "Reagan",
      "92"
   ],
   [
      "White",
      "5",
      "Carter",
      "61"
   ],
   [
      "White",
      "6",
      "Reagan",
      "100"
   ],
   [
      "White",
      "6",
      "Carter",
      "41"
   ],
   [
      "White",
      "7",
      "Reagan",
      "18"
   ],
   [
      "White",
      "7",
      "Carter",
      "8"
   ],
   [
      "NonWhite",
      "1",
      "Reagan",
      "0"
   ],
   [
      "NonWhite",
      "1",
      "Carter",
      "6"
   ],
   [
      "NonWhite",
      "2",
      "Reagan",
      "0"
   ],
   [
      "NonWhite",
      "2",
      "Carter",
      "16"
   ],
   [
      "NonWhite",
      "3",
      "Reagan",
      "2"
   ],
   [
      "NonWhite",
      "3",
      "Carter",
      "23"
   ],
   [
      "NonWhite",
      "4",
      "Reagan",
      "1"
   ],
   [
      "NonWhite",
      "4",
      "Carter",
      "31"
   ],
   [
      "NonWhite",
      "5",
      "Reagan",
      "0"
   ],
   [
      "NonWhite",
      "5",
      "Carter",
      "8"
   ],
   [
      "NonWhite",
      "6",
      "Reagan",
      "2"
   ],
   [
      "NonWhite",
      "6",
      "Carter",
      "7"
   ],
   [
      "NonWhite",
      "7",
      "Reagan",
      "0"
   ],
   [
      "NonWhite",
      "7",
      "Carter",
      "4"
   ]
]
