var capacitorInfo ={
   "parameters" : {
      "Data set genfan" : " Time to failure of 70 diesel engine fans.\n\n\n\n hours",
      "cracks" : " Data on the time until the development of cracks\nin a set of 167 identical turbine parts.\nThe parts were inspected at 8 selected times.\n\n\n\n day",
      "Data set turbine" : "\nEach of 432 turbine wheels was inspected\nonce to determine whether a crack had developed in the wheel or not.\n\n\n\n hours",
      "Data set imotor" : " Breakdown of motor insulation as a function of\ntemperature.\n\n\n\n temp",
      "capacitor" : "\nData from a factorial experiment on the life of glass capacitors as a\nfunction of voltage and operating temperature.  There were 8 capacitors\nat each combination of temperature and voltage.\nTesting at each combination was terminated after the fourth failure.\n\n\n\n temperature",
      "Data set valveSeat" : "\nTime to replacement of valve seats for 41 diesel engines.  More than\none seat may be replaced at a particular service, leading to duplicate\ntimes in the data set.  The final inspection time for each engine will\nhave status=0.\n\n\n\n id"
   },
   "description" : "Description\nA set of data for simple reliablility analyses, taken from the book by\nMeeker and Escobar.",
   "title" : "Reliability data sets",
   "format" : "capacitor:\nData from a factorial experiment on the life of glass capacitors as a\nfunction of voltage and operating temperature.  There were 8 capacitors\nat each combination of temperature and voltage.\nTesting at each combination was terminated after the fourth failure.\n\n\n\n temperature: temperature in degrees celcius\n\n\n voltage: applied voltage\n\n\n time: time to failure\n\n\n status: 1=failed, 0=censored\n\n\n\n\n cracks: Data on the time until the development of cracks\nin a set of 167 identical turbine parts.\nThe parts were inspected at 8 selected times.\n\n\n\n day: time of inspection\n\n\n fail: number of fans found to have cracks, at this inspection\n\n\n\n\n Data set genfan: Time to failure of 70 diesel engine fans.\n\n\n\n hours: hours of service\n\n\n status: 1=failure, 0=censored\n\n\n\nData set ifluid:\nA data frame with two variables describing the time to electrical\nbreakdown of an insulating fluid.\n\n\n\n time: hours to breakdown\n\n\n voltage: test voltage in kV\n\n\n\n\n Data set imotor: Breakdown of motor insulation as a function of\ntemperature.\n\n\n\n temp: temperature of the test\n\n\n time: time to failure or censoring\n\n\n status: 0=censored, 1=failed\n\n\n\n\n Data set turbine:\nEach of 432 turbine wheels was inspected\nonce to determine whether a crack had developed in the wheel or not.\n\n\n\n hours: time of inspection (100s of hours)\n\n\n inspected: number that were inspected\n\n\n failed: number that failed\n\n\n\n\n Data set valveSeat:\nTime to replacement of valve seats for 41 diesel engines.  More than\none seat may be replaced at a particular service, leading to duplicate\ntimes in the data set.  The final inspection time for each engine will\nhave status=0.\n\n\n\n id: engine identifier\n\n\n time: time of the inspection, in days\n\n\n status: 1=replacement occured, 0= not",
   "usage" : "data(reliability, package=\"survival\")"
}

var capacitor = [
   [
      "temperature",
      "voltage",
      "fail",
      "time",
      "status"
   ],
   [
      "170",
      "200",
      "",
      "439",
      "1"
   ],
   [
      "170",
      "200",
      "",
      "904",
      "1"
   ],
   [
      "170",
      "200",
      "",
      "1092",
      "1"
   ],
   [
      "170",
      "200",
      "",
      "1105",
      "1"
   ],
   [
      "170",
      "250",
      "",
      "572",
      "1"
   ],
   [
      "170",
      "250",
      "",
      "690",
      "1"
   ],
   [
      "170",
      "250",
      "",
      "904",
      "1"
   ],
   [
      "170",
      "250",
      "",
      "1090",
      "1"
   ],
   [
      "170",
      "300",
      "",
      "315",
      "1"
   ],
   [
      "170",
      "300",
      "",
      "315",
      "1"
   ],
   [
      "170",
      "300",
      "",
      "439",
      "1"
   ],
   [
      "170",
      "300",
      "",
      "628",
      "1"
   ],
   [
      "170",
      "350",
      "",
      "258",
      "1"
   ],
   [
      "170",
      "350",
      "",
      "258",
      "1"
   ],
   [
      "170",
      "350",
      "",
      "347",
      "1"
   ],
   [
      "170",
      "350",
      "",
      "588",
      "1"
   ],
   [
      "180",
      "200",
      "",
      "959",
      "1"
   ],
   [
      "180",
      "200",
      "",
      "1065",
      "1"
   ],
   [
      "180",
      "200",
      "",
      "1065",
      "1"
   ],
   [
      "180",
      "200",
      "",
      "1087",
      "1"
   ],
   [
      "180",
      "250",
      "",
      "216",
      "1"
   ],
   [
      "180",
      "250",
      "",
      "315",
      "1"
   ],
   [
      "180",
      "250",
      "",
      "455",
      "1"
   ],
   [
      "180",
      "250",
      "",
      "473",
      "1"
   ],
   [
      "180",
      "300",
      "",
      "241",
      "1"
   ],
   [
      "180",
      "300",
      "",
      "315",
      "1"
   ],
   [
      "180",
      "300",
      "",
      "332",
      "1"
   ],
   [
      "180",
      "300",
      "",
      "380",
      "1"
   ],
   [
      "180",
      "350",
      "",
      "241",
      "1"
   ],
   [
      "180",
      "350",
      "",
      "241",
      "1"
   ],
   [
      "180",
      "350",
      "",
      "435",
      "1"
   ],
   [
      "180",
      "350",
      "",
      "455",
      "1"
   ],
   [
      "170",
      "200",
      "",
      "1105",
      "0"
   ],
   [
      "170",
      "200",
      "",
      "1105",
      "0"
   ],
   [
      "170",
      "200",
      "",
      "1105",
      "0"
   ],
   [
      "170",
      "200",
      "",
      "1105",
      "0"
   ],
   [
      "170",
      "250",
      "",
      "1090",
      "0"
   ],
   [
      "170",
      "250",
      "",
      "1090",
      "0"
   ],
   [
      "170",
      "250",
      "",
      "1090",
      "0"
   ],
   [
      "170",
      "250",
      "",
      "1090",
      "0"
   ],
   [
      "170",
      "300",
      "",
      "628",
      "0"
   ],
   [
      "170",
      "300",
      "",
      "628",
      "0"
   ],
   [
      "170",
      "300",
      "",
      "628",
      "0"
   ],
   [
      "170",
      "300",
      "",
      "628",
      "0"
   ],
   [
      "170",
      "350",
      "",
      "588",
      "0"
   ],
   [
      "170",
      "350",
      "",
      "588",
      "0"
   ],
   [
      "170",
      "350",
      "",
      "588",
      "0"
   ],
   [
      "170",
      "350",
      "",
      "588",
      "0"
   ],
   [
      "180",
      "200",
      "",
      "1087",
      "0"
   ],
   [
      "180",
      "200",
      "",
      "1087",
      "0"
   ],
   [
      "180",
      "200",
      "",
      "1087",
      "0"
   ],
   [
      "180",
      "200",
      "",
      "1087",
      "0"
   ],
   [
      "180",
      "250",
      "",
      "473",
      "0"
   ],
   [
      "180",
      "250",
      "",
      "473",
      "0"
   ],
   [
      "180",
      "250",
      "",
      "473",
      "0"
   ],
   [
      "180",
      "250",
      "",
      "473",
      "0"
   ],
   [
      "180",
      "300",
      "",
      "380",
      "0"
   ],
   [
      "180",
      "300",
      "",
      "380",
      "0"
   ],
   [
      "180",
      "300",
      "",
      "380",
      "0"
   ],
   [
      "180",
      "300",
      "",
      "380",
      "0"
   ],
   [
      "180",
      "350",
      "",
      "455",
      "0"
   ],
   [
      "180",
      "350",
      "",
      "455",
      "0"
   ],
   [
      "180",
      "350",
      "",
      "455",
      "0"
   ],
   [
      "180",
      "350",
      "",
      "455",
      "0"
   ]
]
