var ifluidInfo ={
   "description" : "Description\nA set of data for simple reliablility analyses, taken from the book by\nMeeker and Escobar.",
   "parameters" : {
      "capacitor" : "\nData from a factorial experiment on the life of glass capacitors as a\nfunction of voltage and operating temperature.  There were 8 capacitors\nat each combination of temperature and voltage.\nTesting at each combination was terminated after the fourth failure.\n\n\n\n temperature",
      "Data set valveSeat" : "\nTime to replacement of valve seats for 41 diesel engines.  More than\none seat may be replaced at a particular service, leading to duplicate\ntimes in the data set.  The final inspection time for each engine will\nhave status=0.\n\n\n\n id",
      "cracks" : " Data on the time until the development of cracks\nin a set of 167 identical turbine parts.\nThe parts were inspected at 8 selected times.\n\n\n\n day",
      "Data set genfan" : " Time to failure of 70 diesel engine fans.\n\n\n\n hours",
      "Data set turbine" : "\nEach of 432 turbine wheels was inspected\nonce to determine whether a crack had developed in the wheel or not.\n\n\n\n hours",
      "Data set imotor" : " Breakdown of motor insulation as a function of\ntemperature.\n\n\n\n temp"
   },
   "title" : "Reliability data sets",
   "format" : "capacitor:\nData from a factorial experiment on the life of glass capacitors as a\nfunction of voltage and operating temperature.  There were 8 capacitors\nat each combination of temperature and voltage.\nTesting at each combination was terminated after the fourth failure.\n\n\n\n temperature: temperature in degrees celcius\n\n\n voltage: applied voltage\n\n\n time: time to failure\n\n\n status: 1=failed, 0=censored\n\n\n\n\n cracks: Data on the time until the development of cracks\nin a set of 167 identical turbine parts.\nThe parts were inspected at 8 selected times.\n\n\n\n day: time of inspection\n\n\n fail: number of fans found to have cracks, at this inspection\n\n\n\n\n Data set genfan: Time to failure of 70 diesel engine fans.\n\n\n\n hours: hours of service\n\n\n status: 1=failure, 0=censored\n\n\n\nData set ifluid:\nA data frame with two variables describing the time to electrical\nbreakdown of an insulating fluid.\n\n\n\n time: hours to breakdown\n\n\n voltage: test voltage in kV\n\n\n\n\n Data set imotor: Breakdown of motor insulation as a function of\ntemperature.\n\n\n\n temp: temperature of the test\n\n\n time: time to failure or censoring\n\n\n status: 0=censored, 1=failed\n\n\n\n\n Data set turbine:\nEach of 432 turbine wheels was inspected\nonce to determine whether a crack had developed in the wheel or not.\n\n\n\n hours: time of inspection (100s of hours)\n\n\n inspected: number that were inspected\n\n\n failed: number that failed\n\n\n\n\n Data set valveSeat:\nTime to replacement of valve seats for 41 diesel engines.  More than\none seat may be replaced at a particular service, leading to duplicate\ntimes in the data set.  The final inspection time for each engine will\nhave status=0.\n\n\n\n id: engine identifier\n\n\n time: time of the inspection, in days\n\n\n status: 1=replacement occured, 0= not",
   "usage" : "data(reliability, package=\"survival\")"
}

var ifluid = [
   [
      "time",
      "voltage"
   ],
   [
      "5.79",
      "26"
   ],
   [
      "1579.52",
      "26"
   ],
   [
      "2323.7",
      "26"
   ],
   [
      "7.74",
      "30"
   ],
   [
      "17.05",
      "30"
   ],
   [
      "20.46",
      "30"
   ],
   [
      "21.02",
      "30"
   ],
   [
      "22.66",
      "30"
   ],
   [
      "43.4",
      "30"
   ],
   [
      "47.3",
      "30"
   ],
   [
      "139.07",
      "30"
   ],
   [
      "144.12",
      "30"
   ],
   [
      "175.88",
      "30"
   ],
   [
      "194.9",
      "30"
   ],
   [
      "0.19",
      "34"
   ],
   [
      "0.78",
      "34"
   ],
   [
      "0.96",
      "34"
   ],
   [
      "1.31",
      "34"
   ],
   [
      "2.78",
      "34"
   ],
   [
      "3.16",
      "34"
   ],
   [
      "4.15",
      "34"
   ],
   [
      "4.67",
      "34"
   ],
   [
      "4.85",
      "34"
   ],
   [
      "6.5",
      "34"
   ],
   [
      "7.35",
      "34"
   ],
   [
      "8.01",
      "34"
   ],
   [
      "8.27",
      "34"
   ],
   [
      "12.06",
      "34"
   ],
   [
      "31.75",
      "34"
   ],
   [
      "32.52",
      "34"
   ],
   [
      "33.91",
      "34"
   ],
   [
      "36.71",
      "34"
   ],
   [
      "72.89",
      "34"
   ],
   [
      "0.09",
      "38"
   ],
   [
      "0.39",
      "38"
   ],
   [
      "0.47",
      "38"
   ],
   [
      "0.73",
      "38"
   ],
   [
      "0.74",
      "38"
   ],
   [
      "1.13",
      "38"
   ],
   [
      "1.4",
      "38"
   ],
   [
      "2.38",
      "38"
   ]
]
