var leukemiaInfo ={
   "description" : "Description\nSurvival in patients with Acute Myelogenous Leukemia.\nThe question at the time was whether the standard course of\nchemotherapy should be extended ('maintainance') for additional\ncycles.",
   "title" : "Acute Myelogenous Leukemia survival data",
   "format" : "time: survival or censoring time\n\n\n \n    status: censoring status\n\n\n \n    x:  maintenance chemotherapy given? (factor)",
   "usage" : "aml\nleukemia\ndata(cancer, package=\"survival\")"
}

var leukemia = [
   [
      "time",
      "status",
      "x"
   ],
   [
      "9",
      "1",
      "Maintained"
   ],
   [
      "13",
      "1",
      "Maintained"
   ],
   [
      "13",
      "0",
      "Maintained"
   ],
   [
      "18",
      "1",
      "Maintained"
   ],
   [
      "23",
      "1",
      "Maintained"
   ],
   [
      "28",
      "0",
      "Maintained"
   ],
   [
      "31",
      "1",
      "Maintained"
   ],
   [
      "34",
      "1",
      "Maintained"
   ],
   [
      "45",
      "0",
      "Maintained"
   ],
   [
      "48",
      "1",
      "Maintained"
   ],
   [
      "161",
      "0",
      "Maintained"
   ],
   [
      "5",
      "1",
      "Nonmaintained"
   ],
   [
      "5",
      "1",
      "Nonmaintained"
   ],
   [
      "8",
      "1",
      "Nonmaintained"
   ],
   [
      "8",
      "1",
      "Nonmaintained"
   ],
   [
      "12",
      "1",
      "Nonmaintained"
   ],
   [
      "16",
      "0",
      "Nonmaintained"
   ],
   [
      "23",
      "1",
      "Nonmaintained"
   ],
   [
      "27",
      "1",
      "Nonmaintained"
   ],
   [
      "30",
      "1",
      "Nonmaintained"
   ],
   [
      "33",
      "1",
      "Nonmaintained"
   ],
   [
      "43",
      "1",
      "Nonmaintained"
   ],
   [
      "45",
      "1",
      "Nonmaintained"
   ]
]
