var lungInfo ={
   "format" : "inst: Institution code\n\n\n \n    time: Survival time in days\n\n\n \n    status: censoring status 1=censored, 2=dead\n\n\n \n    age: Age in years\n\n\n \n    sex:  Male=1 Female=2\n\n\n \n    ph.ecog: ECOG performance score as rated by the physician.\n    0=asymptomatic, 1= symptomatic but completely ambulatory, 2= in bed\n    <50% of the day, 3= in bed > 50% of the day but not bedbound, 4 =\n    bedbound\n\n\n \n    ph.karno: Karnofsky performance score (bad=0-good=100) rated by physician\n\n\n \n    pat.karno: Karnofsky performance score as rated by patient\n\n\n \n    meal.cal: Calories consumed at meals\n\n\n \n    wt.loss: Weight loss in last six months (pounds)",
   "description" : "Description\nSurvival in patients with advanced lung cancer from the North\nCentral Cancer Treatment Group.  Performance\nscores rate how well the patient can perform usual daily activities.",
   "title" : "NCCTG Lung Cancer Data",
   "usage" : "lung\ndata(cancer, package=\"survival\")"
}

var lung = [
   [
      "dat",
      "Row"
   ],
   [
      "605",
      1
   ],
   [
      "436",
      2
   ],
   [
      "380",
      3
   ],
   [
      "493.9",
      4
   ],
   [
      "",
      5
   ],
   [
      "550",
      6
   ],
   [
      "470",
      7
   ],
   [
      "592.5",
      8
   ],
   [
      "605",
      9
   ],
   [
      "799.9",
      10
   ],
   [
      "995",
      11
   ],
   [
      "785",
      12
   ],
   [
      "910",
      13
   ],
   [
      "1115",
      14
   ],
   [
      "1142.6",
      15
   ],
   [
      "1465",
      16
   ],
   [
      "1250",
      17
   ],
   [
      "1580",
      18
   ],
   [
      "2000",
      19
   ],
   [
      "1474.4",
      20
   ],
   [
      "",
      21
   ],
   [
      "1220",
      22
   ],
   [
      "1790",
      23
   ],
   [
      "1510",
      24
   ],
   [
      "",
      25
   ],
   [
      "",
      26
   ],
   [
      "2735",
      27
   ],
   [
      "",
      28
   ],
   [
      "2380",
      29
   ],
   [
      "",
      30
   ]
]
