var valveSeatInfo ={
   "parameters" : {
      "Data set valveSeat" : "\nTime to replacement of valve seats for 41 diesel engines.  More than\none seat may be replaced at a particular service, leading to duplicate\ntimes in the data set.  The final inspection time for each engine will\nhave status=0.\n\n\n\n id",
      "Data set imotor" : " Breakdown of motor insulation as a function of\ntemperature.\n\n\n\n temp",
      "cracks" : " Data on the time until the development of cracks\nin a set of 167 identical turbine parts.\nThe parts were inspected at 8 selected times.\n\n\n\n day",
      "capacitor" : "\nData from a factorial experiment on the life of glass capacitors as a\nfunction of voltage and operating temperature.  There were 8 capacitors\nat each combination of temperature and voltage.\nTesting at each combination was terminated after the fourth failure.\n\n\n\n temperature",
      "Data set turbine" : "\nEach of 432 turbine wheels was inspected\nonce to determine whether a crack had developed in the wheel or not.\n\n\n\n hours",
      "Data set genfan" : " Time to failure of 70 diesel engine fans.\n\n\n\n hours"
   },
   "usage" : "data(reliability, package=\"survival\")",
   "title" : "Reliability data sets",
   "description" : "Description\nA set of data for simple reliablility analyses, taken from the book by\nMeeker and Escobar.",
   "format" : "capacitor:\nData from a factorial experiment on the life of glass capacitors as a\nfunction of voltage and operating temperature.  There were 8 capacitors\nat each combination of temperature and voltage.\nTesting at each combination was terminated after the fourth failure.\n\n\n\n temperature: temperature in degrees celcius\n\n\n voltage: applied voltage\n\n\n time: time to failure\n\n\n status: 1=failed, 0=censored\n\n\n\n\n cracks: Data on the time until the development of cracks\nin a set of 167 identical turbine parts.\nThe parts were inspected at 8 selected times.\n\n\n\n day: time of inspection\n\n\n fail: number of fans found to have cracks, at this inspection\n\n\n\n\n Data set genfan: Time to failure of 70 diesel engine fans.\n\n\n\n hours: hours of service\n\n\n status: 1=failure, 0=censored\n\n\n\nData set ifluid:\nA data frame with two variables describing the time to electrical\nbreakdown of an insulating fluid.\n\n\n\n time: hours to breakdown\n\n\n voltage: test voltage in kV\n\n\n\n\n Data set imotor: Breakdown of motor insulation as a function of\ntemperature.\n\n\n\n temp: temperature of the test\n\n\n time: time to failure or censoring\n\n\n status: 0=censored, 1=failed\n\n\n\n\n Data set turbine:\nEach of 432 turbine wheels was inspected\nonce to determine whether a crack had developed in the wheel or not.\n\n\n\n hours: time of inspection (100s of hours)\n\n\n inspected: number that were inspected\n\n\n failed: number that failed\n\n\n\n\n Data set valveSeat:\nTime to replacement of valve seats for 41 diesel engines.  More than\none seat may be replaced at a particular service, leading to duplicate\ntimes in the data set.  The final inspection time for each engine will\nhave status=0.\n\n\n\n id: engine identifier\n\n\n time: time of the inspection, in days\n\n\n status: 1=replacement occured, 0= not"
}

var valveSeat = [
   [
      "id",
      "time",
      "status"
   ],
   [
      "251",
      "761",
      "0"
   ],
   [
      "252",
      "759",
      "0"
   ],
   [
      "327",
      "98",
      "1"
   ],
   [
      "327",
      "667",
      "0"
   ],
   [
      "328",
      "326",
      "1"
   ],
   [
      "328",
      "653",
      "1"
   ],
   [
      "328",
      "653",
      "1"
   ],
   [
      "328",
      "667",
      "0"
   ],
   [
      "329",
      "665",
      "0"
   ],
   [
      "330",
      "84",
      "1"
   ],
   [
      "330",
      "667",
      "0"
   ],
   [
      "331",
      "87",
      "1"
   ],
   [
      "331",
      "663",
      "0"
   ],
   [
      "389",
      "646",
      "1"
   ],
   [
      "389",
      "653",
      "0"
   ],
   [
      "390",
      "92",
      "1"
   ],
   [
      "390",
      "653",
      "0"
   ],
   [
      "391",
      "651",
      "0"
   ],
   [
      "392",
      "258",
      "1"
   ],
   [
      "392",
      "328",
      "1"
   ],
   [
      "392",
      "377",
      "1"
   ],
   [
      "392",
      "621",
      "1"
   ],
   [
      "392",
      "650",
      "0"
   ],
   [
      "393",
      "61",
      "1"
   ],
   [
      "393",
      "539",
      "1"
   ],
   [
      "393",
      "648",
      "0"
   ],
   [
      "394",
      "254",
      "1"
   ],
   [
      "394",
      "276",
      "1"
   ],
   [
      "394",
      "298",
      "1"
   ],
   [
      "394",
      "640",
      "1"
   ],
   [
      "394",
      "644",
      "0"
   ],
   [
      "395",
      "76",
      "1"
   ],
   [
      "395",
      "538",
      "1"
   ],
   [
      "395",
      "642",
      "0"
   ],
   [
      "396",
      "635",
      "1"
   ],
   [
      "396",
      "641",
      "0"
   ],
   [
      "397",
      "349",
      "1"
   ],
   [
      "397",
      "404",
      "1"
   ],
   [
      "397",
      "561",
      "1"
   ],
   [
      "397",
      "649",
      "0"
   ],
   [
      "398",
      "631",
      "0"
   ],
   [
      "399",
      "596",
      "0"
   ],
   [
      "400",
      "120",
      "1"
   ],
   [
      "400",
      "479",
      "1"
   ],
   [
      "400",
      "614",
      "0"
   ],
   [
      "401",
      "323",
      "1"
   ],
   [
      "401",
      "449",
      "1"
   ],
   [
      "401",
      "582",
      "0"
   ],
   [
      "402",
      "139",
      "1"
   ],
   [
      "402",
      "139",
      "1"
   ],
   [
      "402",
      "589",
      "0"
   ],
   [
      "403",
      "593",
      "0"
   ],
   [
      "404",
      "573",
      "1"
   ],
   [
      "404",
      "589",
      "0"
   ],
   [
      "405",
      "165",
      "1"
   ],
   [
      "405",
      "408",
      "1"
   ],
   [
      "405",
      "604",
      "1"
   ],
   [
      "405",
      "606",
      "0"
   ],
   [
      "406",
      "249",
      "1"
   ],
   [
      "406",
      "594",
      "0"
   ],
   [
      "407",
      "344",
      "1"
   ],
   [
      "407",
      "497",
      "1"
   ],
   [
      "407",
      "613",
      "0"
   ],
   [
      "408",
      "265",
      "1"
   ],
   [
      "408",
      "586",
      "1"
   ],
   [
      "408",
      "595",
      "0"
   ],
   [
      "409",
      "166",
      "1"
   ],
   [
      "409",
      "206",
      "1"
   ],
   [
      "409",
      "348",
      "1"
   ],
   [
      "409",
      "389",
      "0"
   ],
   [
      "410",
      "601",
      "0"
   ],
   [
      "411",
      "410",
      "1"
   ],
   [
      "411",
      "581",
      "1"
   ],
   [
      "411",
      "601",
      "0"
   ],
   [
      "412",
      "611",
      "0"
   ],
   [
      "413",
      "608",
      "0"
   ],
   [
      "414",
      "587",
      "0"
   ],
   [
      "415",
      "367",
      "1"
   ],
   [
      "415",
      "603",
      "0"
   ],
   [
      "416",
      "202",
      "1"
   ],
   [
      "416",
      "563",
      "1"
   ],
   [
      "416",
      "570",
      "1"
   ],
   [
      "416",
      "585",
      "0"
   ],
   [
      "417",
      "587",
      "0"
   ],
   [
      "418",
      "578",
      "0"
   ],
   [
      "419",
      "578",
      "0"
   ],
   [
      "420",
      "586",
      "0"
   ],
   [
      "421",
      "585",
      "0"
   ],
   [
      "422",
      "582",
      "0"
   ]
]
