var polypsInfo ={
   "parameters" : {
      "age" : "age in years; type: numeric",
      "number12m" : "number of colonic polyps at 12 months; type: numeric",
      "baseline" : "number of colonic polyps at baseline; type: numeric",
      "sex" : "participant sex, levels: female, male; type: factor",
      "treatment" : "treatment assignment, levels: sulindac, placebo; type: factor",
      "participant_id" : "id number for each participant; type: character",
      "number3m" : "number of colonic polyps at 3 months; type: numeric"
   },
   "reference" : "FAP is an inherited condition caused by mutations in the APC  (Adenomatous Polyposis Coli) gene that leads to early and frequent formation of precancerous polyps of the colon at a young age, and invariably leads to the development of colon cancer at a young age.  \nEarly, frequent surveillance colonoscopy and polyp removal is helpful, but this study examined whether there is a beneficial effect of preventive medical therapy with the nonsteroidal pain reliever, sulindac, versus placebo in a RCT vs placebo in 22 participants, with polyp number measured (via colonoscopy) at baseline, 3 months, and 12 months after starting the study drug. Note that one subject did not return for the 12 month colonoscopy.",
   "usage" : "polyps",
   "description" : "Description\nResults of a randomized, placebo-controlled trial of sulindac in the reduction of colonic polyps in Familial Adenomatous Polyposis  (FAP) (more details available below the variable definitions).",
   "title" : "RCT of Sulindac for Polyp Prevention in Familial Adenomatous Polyposis",
   "format" : "A data frame with 22 observations and 7 variables"
}

var polyps = [
   [
      "participant_id",
      "sex",
      "age",
      "baseline",
      "treatment",
      "number3m",
      "number12m"
   ],
   [
      "001",
      "female",
      "17",
      "7",
      "sulindac",
      "6",
      ""
   ],
   [
      "002",
      "female",
      "20",
      "77",
      "placebo",
      "67",
      "63"
   ],
   [
      "003",
      "male",
      "16",
      "7",
      "sulindac",
      "4",
      "2"
   ],
   [
      "004",
      "female",
      "18",
      "5",
      "placebo",
      "5",
      "28"
   ],
   [
      "005",
      "male",
      "22",
      "23",
      "sulindac",
      "16",
      "17"
   ],
   [
      "006",
      "female",
      "13",
      "35",
      "placebo",
      "31",
      "61"
   ],
   [
      "007",
      "female",
      "23",
      "11",
      "sulindac",
      "6",
      "1"
   ],
   [
      "008",
      "male",
      "34",
      "12",
      "placebo",
      "20",
      "7"
   ],
   [
      "009",
      "male",
      "50",
      "7",
      "placebo",
      "7",
      "15"
   ],
   [
      "010",
      "male",
      "19",
      "318",
      "placebo",
      "347",
      "44"
   ],
   [
      "011",
      "male",
      "17",
      "160",
      "sulindac",
      "142",
      "25"
   ],
   [
      "012",
      "female",
      "23",
      "8",
      "sulindac",
      "1",
      "3"
   ],
   [
      "013",
      "male",
      "22",
      "20",
      "placebo",
      "16",
      "28"
   ],
   [
      "014",
      "male",
      "30",
      "11",
      "placebo",
      "20",
      "10"
   ],
   [
      "015",
      "male",
      "27",
      "24",
      "placebo",
      "26",
      "40"
   ],
   [
      "016",
      "male",
      "23",
      "34",
      "sulindac",
      "27",
      "33"
   ],
   [
      "017",
      "female",
      "22",
      "54",
      "placebo",
      "45",
      "46"
   ],
   [
      "018",
      "male",
      "13",
      "16",
      "sulindac",
      "10",
      ""
   ],
   [
      "019",
      "male",
      "34",
      "30",
      "placebo",
      "30",
      "50"
   ],
   [
      "020",
      "female",
      "23",
      "10",
      "sulindac",
      "6",
      "3"
   ],
   [
      "021",
      "female",
      "22",
      "20",
      "sulindac",
      "5",
      "1"
   ],
   [
      "022",
      "male",
      "42",
      "12",
      "sulindac",
      "8",
      "4"
   ]
]
