var series_rawInfo ={
   "parameters" : {
      "finale" : "A date denoting original airdate of series finale episode in\nthe UK.",
      "winner" : "A character string denoting name of series winner.",
      "avg_uk_viewers" : "Average UK viewers in millions. Also see\nratings.",
      "timeslot" : "time of day that series' episodes aired in UK (24-hour\nclock).",
      "day_of_week" : "A character string denoting weekday that series'\nepisodes aired in UK.",
      "runner_up_2" : "A character string denoting the name of one of the\nbakers who was a series runner-up. The number is not meaningful.",
      "runner_up_1" : "A character string denoting the name of one of the\nbakers who was a series runner-up. The number is not meaningful.",
      "channel" : "A character string denoting channel that series aired on:\none of &#8288;BBC One&#8288;, &#8288;BBC Two&#8288;, or &#8288;Channel 4&#8288;.",
      "series" : "A factor denoting UK series (1-10).",
      "premiere" : "A date denoting original airdate of series premiere episode\nin the UK.",
      "episodes" : "An integer denoting total number of episodes within\nseries."
   },
   "reference" : "See\nhttps://en.wikipedia.org/wiki/The_Great_British_Bake_Off#Series_overview",
   "usage" : "series_raw",
   "title" : "Data about each series aired in the UK (raw)",
   "description" : "Description\nThis dataset has one row per series aired in the UK as 'The Great British\nBake Off'. When did a series premiere in the UK? When was the finale episode?\nHow many viewers on average  did a series have?",
   "format" : "A data frame with 10 rows representing individual series and 11 variables:"
}

var series_raw = [
   [
      "series",
      "episodes",
      "premiere",
      "finale",
      "winner",
      "avg_uk_viewers",
      "day_of_week",
      "timeslot",
      "channel",
      "runner_up_1",
      "runner_up_2"
   ],
   [
      "1",
      "6",
      "2010-08-17",
      "2010-09-21",
      "Edd Kimber",
      "2.77",
      "Tuesday",
      "8:00pm",
      "BBC Two",
      "Miranda Gore Browne",
      "Ruth Clemens"
   ],
   [
      "2",
      "8",
      "2011-08-14",
      "2011-10-04",
      "Joanne Wheatley",
      "4",
      "Tuesday",
      "8:00pm",
      "BBC Two",
      "Holly Bell",
      "Mary-Anne Boermans"
   ],
   [
      "3",
      "10",
      "2012-08-14",
      "2012-10-16",
      "John Whaite",
      "5",
      "Tuesday",
      "8:00pm",
      "BBC Two",
      "Brendan Lynch",
      "James Morton"
   ],
   [
      "4",
      "10",
      "2013-08-20",
      "2013-10-22",
      "Frances Quinn",
      "7.35",
      "Tuesday",
      "8:00pm",
      "BBC Two",
      "Kimberley Wilson",
      "Ruby Tandoh"
   ],
   [
      "5",
      "10",
      "2014-08-06",
      "2014-10-08",
      "Nancy Birtwhistle",
      "10.04",
      "Wednesday",
      "8:00pm",
      "BBC One",
      "Luis Troyano",
      "Richard Burr"
   ],
   [
      "6",
      "10",
      "2015-08-05",
      "2015-10-07",
      "Nadiya Hussain",
      "12.5",
      "Wednesday",
      "8:00pm",
      "BBC One",
      "Ian Cumming",
      "Tamal Ray"
   ],
   [
      "7",
      "10",
      "2016-08-24",
      "2016-10-26",
      "Candice Brown",
      "13.85",
      "Wednesday",
      "8:00pm",
      "BBC One",
      "Andrew Smyth",
      "Jane Beedle"
   ],
   [
      "8",
      "10",
      "2017-08-29",
      "2017-10-31",
      "Sophie Faldo",
      "9.29",
      "Tuesday",
      "8:00pm",
      "Channel 4",
      "Kate Lyon",
      "Steven Carter-Bailey"
   ],
   [
      "9",
      "10",
      "2018-08-28",
      "2018-10-30",
      "Rahul Mandal",
      "9.3",
      "Tuesday",
      "8:00pm",
      "Channel 4",
      "Kim-Joy Hewlett",
      "Ruby Bhogal"
   ],
   [
      "10",
      "10",
      "2019-08-27",
      "2019-10-29",
      "David Atherton",
      "9.24",
      "Tuesday",
      "8:00pm",
      "Channel 4",
      "Alice Fevronia",
      "Steph Blackwell"
   ]
]
