var ArmadaInfo ={
   "usage" : "data(\"Armada\")",
   "description" : "Description\nThe Spanish Armada (Spanish: Grande y Felicisima Armada, literally \"Great and Most Fortunate Navy\") was a Spanish fleet of 130 ships \nthat sailed from La Coruna in August 1588.\nDuring its preparation, several accounts of its formidable strength\nwere circulated to reassure allied powers of Spain or to intimidate its enemies.\nOne such account was given by Paz Salas et Alvarez (1588).\nThe intent was bring the forces of Spain to invade England, overthrow\nQueen Elizabeth I, and re-establish Spanish control of the Netherlands.\nHowever the Armada\nwas not as fortunate as hoped: it was all destroyed in one week's fighting.\nde Falguerolles (2008) reports the table given here as Armada\nas an early example of data to which multivariate methods might be applied.",
   "reference" : "Note that men = soldiers + sailors",
   "format" : "A data frame with 10 observations on the following 11 variables.",
   "title" : "La Felicisima Armada",
   "parameters" : {
      "lead" : "a numeric vector",
      "tons" : "total tons, a numeric vector",
      "Armada" : "designation of the fleet, a factor with levels Andalucia Castilla Galeras Guipuscua Napoles Pataches Portugal Uantiscas Vizca Vrcas",
      "balls" : "a numeric vector",
      "gunpowder" : "a numeric vector",
      "ships" : "number of ships, a numeric vector",
      "men" : "total of soldiers plus sailors, a numeric vector",
      "artillery" : "a numeric vector",
      "sailors" : "number of sailors, a numeric vector",
      "rope" : "a numeric vector",
      "soldiers" : "number of soldiers, a numeric vector"
   }
}

var Armada = [
   [
      "Armada",
      "ships",
      "tons",
      "soldiers",
      "sailors",
      "men",
      "artillery",
      "balls",
      "gunpowder",
      "lead",
      "rope"
   ],
   [
      "Portugal",
      "12",
      "7737",
      "3330",
      "1293",
      "4623",
      "347",
      "18450",
      "789",
      "186",
      "150"
   ],
   [
      "Vizca",
      "14",
      "6567",
      "1937",
      "863",
      "2800",
      "238",
      "11900",
      "477",
      "140",
      "87"
   ],
   [
      "Castilla",
      "16",
      "8714",
      "2458",
      "1719",
      "4171",
      "384",
      "23040",
      "710",
      "290",
      "309"
   ],
   [
      "Andalucia",
      "11",
      "8762",
      "2325",
      "780",
      "3105",
      "240",
      "10200",
      "415",
      "63",
      "119"
   ],
   [
      "Guipuscua",
      "14",
      "6991",
      "1992",
      "616",
      "2608",
      "247",
      "12150",
      "518",
      "139",
      "109"
   ],
   [
      "Uantiscas",
      "10",
      "7705",
      "2780",
      "767",
      "3523",
      "280",
      "14000",
      "584",
      "177",
      "141"
   ],
   [
      "Vrcas",
      "23",
      "10271",
      "3121",
      "608",
      "3729",
      "384",
      "19200",
      "258",
      "142",
      "215"
   ],
   [
      "Pataches",
      "22",
      "1221",
      "479",
      "574",
      "1093",
      "91",
      "4550",
      "66",
      "20",
      "13"
   ],
   [
      "Napoles",
      "4",
      "0",
      "873",
      "468",
      "1341",
      "200",
      "10000",
      "498",
      "61",
      "88"
   ],
   [
      "Galeras",
      "4",
      "0",
      "0",
      "362",
      "362",
      "20",
      "1200",
      "60",
      "20",
      "20"
   ]
]
