var CavendishInfo ={
   "format" : "A data frame with 29 observations on the following 3 variables.",
   "description" : "Description\nHenry Cavendish carried out a series of experiments in 1798 to determine the\nmean density of the earth, as an indirect means to calculate the\ngravitational constant, G, in Newton's formula for the force (f) of\ngravitational attraction,\nf = G m M / r^2\nbetween two bodies of mass m and M.\nStigler (1977) used these data to illustrate properties of robust estimators\nwith real, historical data.  For these data sets, he found that trimmed means\nperformed as well or better than more elaborate robust estimators.",
   "title" : "Cavendish's Determinations of the Density of the Earth",
   "usage" : "data(Cavendish)",
   "reference" : "Density values (D) of the earth are given as relative to that of water.  If the earth is\nregarded as a sphere of radius R, Newton's law can be expressed as\nG D = 3 g / (4 \\pi R), where g=9.806 m/s^2 is the acceleration due to gravity; so G is proportional to 1/D.",
   "parameters" : {
      "density" : "Cavendish's 29 determinations of the mean density of the earth",
      "density3" : "same as density, omitting the the first 6 observations",
      "density2" : "same as density, with the third value (4.88) replaced by 5.88"
   }
}

var Cavendish = [
   [
      "density",
      "density2",
      "density3"
   ],
   [
      "5.5",
      "5.5",
      ""
   ],
   [
      "5.61",
      "5.61",
      ""
   ],
   [
      "4.88",
      "5.88",
      ""
   ],
   [
      "5.07",
      "5.07",
      ""
   ],
   [
      "5.26",
      "5.26",
      ""
   ],
   [
      "5.55",
      "5.55",
      ""
   ],
   [
      "5.36",
      "5.36",
      "5.36"
   ],
   [
      "5.29",
      "5.29",
      "5.29"
   ],
   [
      "5.58",
      "5.58",
      "5.58"
   ],
   [
      "5.65",
      "5.65",
      "5.65"
   ],
   [
      "5.57",
      "5.57",
      "5.57"
   ],
   [
      "5.53",
      "5.53",
      "5.53"
   ],
   [
      "5.62",
      "5.62",
      "5.62"
   ],
   [
      "5.29",
      "5.29",
      "5.29"
   ],
   [
      "5.44",
      "5.44",
      "5.44"
   ],
   [
      "5.34",
      "5.34",
      "5.34"
   ],
   [
      "5.79",
      "5.79",
      "5.79"
   ],
   [
      "5.1",
      "5.1",
      "5.1"
   ],
   [
      "5.27",
      "5.27",
      "5.27"
   ],
   [
      "5.39",
      "5.39",
      "5.39"
   ],
   [
      "5.42",
      "5.42",
      "5.42"
   ],
   [
      "5.47",
      "5.47",
      "5.47"
   ],
   [
      "5.63",
      "5.63",
      "5.63"
   ],
   [
      "5.34",
      "5.34",
      "5.34"
   ],
   [
      "5.46",
      "5.46",
      "5.46"
   ],
   [
      "5.3",
      "5.3",
      "5.3"
   ],
   [
      "5.75",
      "5.75",
      "5.75"
   ],
   [
      "5.68",
      "5.68",
      "5.68"
   ],
   [
      "5.85",
      "5.85",
      "5.85"
   ]
]
