var EdgeworthDeathsInfo ={
   "format" : "A data frame with 42 observations on the following 3 variables.",
   "parameters" : {
      "Freq" : "a numeric vector, death rate per 1000 population",
      "County" : "a factor with levels Berks Herts Bucks Oxford Bedford Cambridge",
      "year" : "an ordered factor with levels 1876 < 1877 < 1878 < 1879 < 1880 < 1881 < 1882"
   },
   "usage" : "data(\"EdgeworthDeaths\")",
   "reference" : "Edgeworth's data came from the Registrar General's report for the final year, 1883.\nThe Freq variable represents death rates per 1000 population in the six counties listed.",
   "description" : "Description\nIn 1885, Francis Edgeworth published a paper, On methods of ascertaining variations in the rate of births, deaths and marriages.\nIt contained among the first examples of two-way tables, analyzed to show variation among row and column factors,\nin a way that Fisher would later formulate as the Analysis of Variance.\nAlthough the data are rates per 1000, they provide a good example of a two-way ANOVA with n=1 per cell,\nwhere an additive model fits reasonably well.\nTreated as frequencies, the data is also a good example of a case where the independence model fits\nreasonably well.",
   "title" : "Edgeworth's Data on Death Rates in British Counties"
}

var EdgeworthDeaths = [
   [
      "County",
      "year",
      "Freq"
   ],
   [
      "Berks",
      "1876",
      "175"
   ],
   [
      "Herts",
      "1876",
      "174"
   ],
   [
      "Bucks",
      "1876",
      "182"
   ],
   [
      "Oxford",
      "1876",
      "179"
   ],
   [
      "Bedford",
      "1876",
      "196"
   ],
   [
      "Cambridge",
      "1876",
      "173"
   ],
   [
      "Berks",
      "1877",
      "172"
   ],
   [
      "Herts",
      "1877",
      "165"
   ],
   [
      "Bucks",
      "1877",
      "171"
   ],
   [
      "Oxford",
      "1877",
      "182"
   ],
   [
      "Bedford",
      "1877",
      "174"
   ],
   [
      "Cambridge",
      "1877",
      "177"
   ],
   [
      "Berks",
      "1878",
      "187"
   ],
   [
      "Herts",
      "1878",
      "185"
   ],
   [
      "Bucks",
      "1878",
      "186"
   ],
   [
      "Oxford",
      "1878",
      "194"
   ],
   [
      "Bedford",
      "1878",
      "203"
   ],
   [
      "Cambridge",
      "1878",
      "190"
   ],
   [
      "Berks",
      "1879",
      "186"
   ],
   [
      "Herts",
      "1879",
      "184"
   ],
   [
      "Bucks",
      "1879",
      "195"
   ],
   [
      "Oxford",
      "1879",
      "183"
   ],
   [
      "Bedford",
      "1879",
      "195"
   ],
   [
      "Cambridge",
      "1879",
      "191"
   ],
   [
      "Berks",
      "1880",
      "181"
   ],
   [
      "Herts",
      "1880",
      "176"
   ],
   [
      "Bucks",
      "1880",
      "179"
   ],
   [
      "Oxford",
      "1880",
      "180"
   ],
   [
      "Bedford",
      "1880",
      "198"
   ],
   [
      "Cambridge",
      "1880",
      "187"
   ],
   [
      "Berks",
      "1881",
      "153"
   ],
   [
      "Herts",
      "1881",
      "166"
   ],
   [
      "Bucks",
      "1881",
      "162"
   ],
   [
      "Oxford",
      "1881",
      "169"
   ],
   [
      "Bedford",
      "1881",
      "171"
   ],
   [
      "Cambridge",
      "1881",
      "165"
   ],
   [
      "Berks",
      "1882",
      "169"
   ],
   [
      "Herts",
      "1882",
      "163"
   ],
   [
      "Bucks",
      "1882",
      "177"
   ],
   [
      "Oxford",
      "1882",
      "167"
   ],
   [
      "Bedford",
      "1882",
      "181"
   ],
   [
      "Cambridge",
      "1882",
      "171"
   ]
]
