var FingerprintsInfo ={
   "description" : "Description\nWaite (1915) was interested in analyzing the association of patterns in fingerprints,\nand produced a table of counts for 2000 right hands, classified by the number of fingers\ndescribable as a \"whorl\", a \"small loop\" (or neither).\nBecause each hand contributes five fingers, the number of Whorls + Loops cannot exceed 5,\nso the contingency table is necessarily triangular.\nKarl Pearson (1904) introduced the test for independence in contingency tables, and by 1913\nhad developed methods for \"restricted contingency tables,\" such as the triangular table\nanalyzed by Waite.  The general formulation of such tests for association in restricted\ntables is now referred to as models for quasi-independence.",
   "usage" : "data(Fingerprints)",
   "parameters" : {
      "Whorls" : "Number of whorls, an ordered factor with levels 0 < 1 < 2 < 3 < 4 < 5",
      "count" : "Number of hands",
      "Loops" : "Number of small loops, an ordered factor with levels 0 < 1 < 2 < 3 < 4 < 5"
   },
   "format" : "A frequency data frame with 36 observations on the following 3 variables, \nrepresenting a 6 x 6 table giving\nthe cross-classification of the fingers on 2000 right hands as a whorl, small loop\nor neither.",
   "title" : "Waite's data on Patterns in Fingerprints",
   "reference" : "Cells for which Whorls + Loops>5 have NA for count"
}

var Fingerprints = [
   [
      "Whorls",
      "Loops",
      "count"
   ],
   [
      "0",
      "0",
      "78"
   ],
   [
      "1",
      "0",
      "106"
   ],
   [
      "2",
      "0",
      "130"
   ],
   [
      "3",
      "0",
      "125"
   ],
   [
      "4",
      "0",
      "104"
   ],
   [
      "5",
      "0",
      "50"
   ],
   [
      "0",
      "1",
      "144"
   ],
   [
      "1",
      "1",
      "153"
   ],
   [
      "2",
      "1",
      "92"
   ],
   [
      "3",
      "1",
      "38"
   ],
   [
      "4",
      "1",
      "26"
   ],
   [
      "5",
      "1",
      ""
   ],
   [
      "0",
      "2",
      "204"
   ],
   [
      "1",
      "2",
      "126"
   ],
   [
      "2",
      "2",
      "55"
   ],
   [
      "3",
      "2",
      "7"
   ],
   [
      "4",
      "2",
      ""
   ],
   [
      "5",
      "2",
      ""
   ],
   [
      "0",
      "3",
      "211"
   ],
   [
      "1",
      "3",
      "80"
   ],
   [
      "2",
      "3",
      "15"
   ],
   [
      "3",
      "3",
      ""
   ],
   [
      "4",
      "3",
      ""
   ],
   [
      "5",
      "3",
      ""
   ],
   [
      "0",
      "4",
      "179"
   ],
   [
      "1",
      "4",
      "32"
   ],
   [
      "2",
      "4",
      ""
   ],
   [
      "3",
      "4",
      ""
   ],
   [
      "4",
      "4",
      ""
   ],
   [
      "5",
      "4",
      ""
   ],
   [
      "0",
      "5",
      "45"
   ],
   [
      "1",
      "5",
      ""
   ],
   [
      "2",
      "5",
      ""
   ],
   [
      "3",
      "5",
      ""
   ],
   [
      "4",
      "5",
      ""
   ],
   [
      "5",
      "5",
      ""
   ]
]
