var Langren.allInfo ={
   "format" : "Langren1644: A data frame with 12 observations on the following 9 variables,\ngiving determinations of the distance in longitude between Toledo and Rome, from the 1644 graph.",
   "reference" : "In all the graphs, Toledo is implicitly at the origin and Rome is located relatively at the value of Longitude  \nTo judge correspondence with an actual map, the positions in (lat, long) are",
   "usage" : "data(Langren1644)\n\tdata(Langren.all)",
   "description" : "Description\nMichael Florent van Langren (1598-1675) was a Dutch mathematician and astronomer, who served\nas a royal mathematician to King Phillip IV of Spain, and who worked on one of the most significant\nproblems of his time&mdash; the accurate determination of longitude, particularly for navigation at sea.\nIn order to convince the Spanish court of the seriousness of the problem (often resulting in\ngreat losses through ship wrecks), he prepared a 1-dimensional line graph, showing all the \navailable estimates of the distance in longitude between Toledo and Rome, which showed\nlarge errors, for even this modest distance.  This 1D line graph, from Langren (1644), is believed\nto be the first known graph of statistical data (Friendly etal., 2010).\nIt provides a compelling example of the notions of statistical variability and bias.\nThe data frame Langren1644 gives the estimates and other information derived from the\npreviously known 1644 graph.  \nIt turns out that van Langren produced other versions of this graph, as early as 1628.\nThe data frame Langren.all gives the estimates derived\nfrom all known versions of this graph.",
   "title" : "van Langren's Data on Longitude Distance between Toledo and Rome",
   "parameters" : {
      "Country" : "The country where this person worked; a factor with levels Belgium Denmark Egypt Flanders France Germany Italy Italy",
      "City" : "The principal city where this person worked; a factor with levels Alexandria Amsterdam Bamberg Bologna Frankfurt Hven Leuven Middelburg Nuremberg Padua Paris Rome",
      "Longitude" : "Estimated value of the longitude distance between Toledo and Rome",
      "Latitude" : "Latitude of this City; a numeric vector",
      "Source" : "Likely source for this determination of Longitude; a factor with levels Astron Map",
      "Longname" : "A longer version of the Name, where appropriate; a factor with levels Andrea Argoli Christoph Clavius  Tycho Brahe",
      "Year" : "Year associated with this determination",
      "Name" : "The name of the person giving a determination, a factor with levels A. Argelius ... T. Brahe",
      "Gap" : "A numeric vector indicating whether the Longitude value is below or above the median"
   }
}

var Langren.all = [
   [
      "Author",
      "Year",
      "Name",
      "Longitude"
   ],
   [
      "Langren",
      "1628",
      "Langren",
      "17.6907"
   ],
   [
      "Langren",
      "1628",
      "Mercator",
      "19.6701"
   ],
   [
      "Langren",
      "1628",
      "Schonerus",
      "20.7835"
   ],
   [
      "Langren",
      "1628",
      "Orontius",
      "24.2474"
   ],
   [
      "Langren",
      "1628",
      "Regiomontanus",
      "25.5464"
   ],
   [
      "Langren",
      "1628",
      "Clavius",
      "26.5361"
   ],
   [
      "Langren",
      "1628",
      "Ptolomeus",
      "27.7732"
   ],
   [
      "Langren",
      "1632",
      "Algunos1",
      "17.6744"
   ],
   [
      "Langren",
      "1632",
      "Maginus",
      "18.206"
   ],
   [
      "Langren",
      "1632",
      "Ortelius",
      "19.1694"
   ],
   [
      "Langren",
      "1632",
      "Bertius",
      "19.402"
   ],
   [
      "Langren",
      "1632",
      "Mercator",
      "19.701"
   ],
   [
      "Langren",
      "1632",
      "Algunos2",
      "20.3654"
   ],
   [
      "Langren",
      "1632",
      "Schonerus",
      "20.7641"
   ],
   [
      "Langren",
      "1632",
      "Brahe",
      "21.495"
   ],
   [
      "Langren",
      "1632",
      "Regiomontanus",
      "25.5482"
   ],
   [
      "Langren",
      "1632",
      "Ptolomeus",
      "26.2126"
   ],
   [
      "Langren",
      "1632",
      "Orontius",
      "26.2126"
   ],
   [
      "Langren",
      "1632",
      "Clavius",
      "26.711"
   ],
   [
      "Langren",
      "1632",
      "Apianus",
      "27.3754"
   ],
   [
      "Langren",
      "1632",
      "Leonitrus",
      "27.7076"
   ],
   [
      "Langren",
      "1632",
      "Origanus",
      "27.7076"
   ],
   [
      "Langren",
      "1633",
      "Algunos1",
      "17.3727"
   ],
   [
      "Langren",
      "1633",
      "Maginus",
      "17.8909"
   ],
   [
      "Langren",
      "1633",
      "Ortelius",
      "18.7909"
   ],
   [
      "Langren",
      "1633",
      "Bertius",
      "19.0636"
   ],
   [
      "Langren",
      "1633",
      "Mercator",
      "19.4182"
   ],
   [
      "Langren",
      "1633",
      "Algunos2",
      "20.1545"
   ],
   [
      "Langren",
      "1633",
      "Schonerus",
      "20.6727"
   ],
   [
      "Langren",
      "1633",
      "Brahe",
      "21.3273"
   ],
   [
      "Langren",
      "1633",
      "Regiomontanus",
      "25.1182"
   ],
   [
      "Langren",
      "1633",
      "Ptolomeus",
      "26.0182"
   ],
   [
      "Langren",
      "1633",
      "Orontius",
      "26.0182"
   ],
   [
      "Langren",
      "1633",
      "Clavius",
      "26.5364"
   ],
   [
      "Langren",
      "1633",
      "Apianus",
      "27.0545"
   ],
   [
      "Langren",
      "1633",
      "Leonitrus",
      "27.4636"
   ],
   [
      "Langren",
      "1633",
      "Origanus",
      "27.4636"
   ],
   [
      "Langren",
      "1644",
      "Iansonius",
      "17.6197"
   ],
   [
      "Langren",
      "1644",
      "Mercator",
      "19.6478"
   ],
   [
      "Langren",
      "1644",
      "Schonerus",
      "20.7514"
   ],
   [
      "Langren",
      "1644",
      "Lantsbergius",
      "21.1326"
   ],
   [
      "Langren",
      "1644",
      "Brahe",
      "21.4135"
   ],
   [
      "Langren",
      "1644",
      "Regiomontanus",
      "25.467"
   ],
   [
      "Langren",
      "1644",
      "Orontius",
      "26.0473"
   ],
   [
      "Langren",
      "1644",
      "Clavius",
      "26.5083"
   ],
   [
      "Langren",
      "1644",
      "Ptolomeus",
      "27.6514"
   ],
   [
      "Langren",
      "1644",
      "Argelius",
      "28.0538"
   ],
   [
      "Langren",
      "1644",
      "Maginus",
      "29.7988"
   ],
   [
      "Langren",
      "1644",
      "Origanus",
      "30.0597"
   ],
   [
      "Lelewel",
      "1851",
      "Iansonius",
      "17.432"
   ],
   [
      "Lelewel",
      "1851",
      "Mercator",
      "19.9006"
   ],
   [
      "Lelewel",
      "1851",
      "Schonerus",
      "20.6691"
   ],
   [
      "Lelewel",
      "1851",
      "Lantsbergius",
      "21.0527"
   ],
   [
      "Lelewel",
      "1851",
      "Brahe",
      "21.4362"
   ],
   [
      "Lelewel",
      "1851",
      "Regiomontanus",
      "25.6093"
   ],
   [
      "Lelewel",
      "1851",
      "Orontius",
      "25.9943"
   ],
   [
      "Lelewel",
      "1851",
      "Clavius",
      "26.3778"
   ],
   [
      "Lelewel",
      "1851",
      "Ptolomeus",
      "27.7841"
   ],
   [
      "Lelewel",
      "1851",
      "Argelius",
      "28.1661"
   ],
   [
      "Lelewel",
      "1851",
      "Maginus",
      "29.8295"
   ],
   [
      "Lelewel",
      "1851",
      "Origanus",
      "30.1689"
   ]
]
