var YeastInfo ={
   "parameters" : {
      "count" : "The number of yeast cells counted in a square",
      "sample" : "Sample identifier, a factor with levels A B C D",
      "freq" : "The number of squares with the given count"
   },
   "reference" : "Student considers the distribution of a total of Nm particles distributed over\nN unit areas with an average of m particles per unit area.\nWith uniform mixing, for a given particle, the probability of it falling on any one\narea is p = 1/N, and not falling on that area is q = 1 - 1/N.\nHe derives the probability distribution of 0, 1, 2, 3, ...\nparticles on a single unit area from the binomial expansion of (p + q)^{mN}.",
   "usage" : "data(Yeast)\n\tdata(YeastD.mat)",
   "description" : "Description\nCounts of the number of yeast cells were made each of 400 regions in a 20 x 20 grid on a microscope\nslide, comprising a 1 sq. mm. area.\nThis experiment was repeated four times, giving samples A, B, C and D.\nStudent (1906) used these data to investigate the errors in random sampling.\nHe says \"there are two sources of error: (a) the drop taken may not be representative\nof the bulk of the liquid; (b) the distribution of the cells over the area \nwhich is examined is never exactly uniform, so that there is an 'error of\nrandom sampling.'\"\nThe data in the paper are provided in the form of discrete frequency distributions\nfor the four samples.  Each shows the frequency distribution squares containing\na count of 0, 1, 2, ... yeast cells. These are combined here in Yeast. \nIn addition, he gives a table\n(Table I) showing the actual number of yeast cells counted in the 20 x 20\ngrid for sample D, given here as YeastD.mat.",
   "title" : "Student's (1906) Yeast Cell Counts",
   "format" : "Yeast: A frequency data frame with 36 observations on the following 3 variables,\ngiving the frequencies of"
}

var Yeast = [
   [
      "sample",
      "count",
      "freq"
   ],
   [
      "A",
      "0",
      "213"
   ],
   [
      "A",
      "1",
      "128"
   ],
   [
      "A",
      "2",
      "37"
   ],
   [
      "A",
      "3",
      "18"
   ],
   [
      "A",
      "4",
      "3"
   ],
   [
      "A",
      "5",
      "1"
   ],
   [
      "B",
      "0",
      "103"
   ],
   [
      "B",
      "1",
      "143"
   ],
   [
      "B",
      "2",
      "98"
   ],
   [
      "B",
      "3",
      "42"
   ],
   [
      "B",
      "4",
      "8"
   ],
   [
      "B",
      "5",
      "4"
   ],
   [
      "B",
      "6",
      "2"
   ],
   [
      "C",
      "0",
      "75"
   ],
   [
      "C",
      "1",
      "103"
   ],
   [
      "C",
      "2",
      "121"
   ],
   [
      "C",
      "3",
      "54"
   ],
   [
      "C",
      "4",
      "30"
   ],
   [
      "C",
      "5",
      "13"
   ],
   [
      "C",
      "6",
      "2"
   ],
   [
      "C",
      "7",
      "1"
   ],
   [
      "C",
      "8",
      "0"
   ],
   [
      "C",
      "9",
      "1"
   ],
   [
      "D",
      "0",
      "0"
   ],
   [
      "D",
      "1",
      "20"
   ],
   [
      "D",
      "2",
      "43"
   ],
   [
      "D",
      "3",
      "53"
   ],
   [
      "D",
      "4",
      "86"
   ],
   [
      "D",
      "5",
      "70"
   ],
   [
      "D",
      "6",
      "54"
   ],
   [
      "D",
      "7",
      "37"
   ],
   [
      "D",
      "8",
      "18"
   ],
   [
      "D",
      "9",
      "10"
   ],
   [
      "D",
      "10",
      "5"
   ],
   [
      "D",
      "11",
      "2"
   ],
   [
      "D",
      "12",
      "2"
   ]
]
