var greek_dataInfo ={
   "format" : "A data frame with 20 rows and 4 variables:",
   "usage" : "greek_data",
   "reference" : "HernÃ¡n and Robins. Causal Inference. https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/",
   "description" : "Description\ngreek_data is a fictional data set from Table 2.2 in Chapter 2 of Causal Inference. From the book: \"Table 2.2 shows the data from our heart transplant randomized study. Besides data on treatment A (1 if the individual received a transplant, 0 otherwise) and outcome Y (1 if the individual died, 0 otherwise), Table 2.2 also contains data on the prognostic factor L (1 if the individual was in critical condition, 0 otherwise), which we measured before treatment was assigned.\"",
   "title" : "Data from a fictional randomized heart transplant study",
   "parameters" : {
      "y" : "The outcome, death",
      "name" : "The name of a Greek god",
      "a" : "The treatment, a heart transplant",
      "l" : "A prognostic factor"
   }
}

var greek_data = [
   [
      "name",
      "l",
      "a",
      "y"
   ],
   [
      "Rheia",
      "0",
      "0",
      "0"
   ],
   [
      "Kronos",
      "0",
      "0",
      "1"
   ],
   [
      "Demeter",
      "0",
      "0",
      "0"
   ],
   [
      "Hades",
      "0",
      "0",
      "0"
   ],
   [
      "Hestia",
      "0",
      "1",
      "0"
   ],
   [
      "Poseidon",
      "0",
      "1",
      "0"
   ],
   [
      "Hera",
      "0",
      "1",
      "0"
   ],
   [
      "Zeus",
      "0",
      "1",
      "1"
   ],
   [
      "Artemis",
      "1",
      "0",
      "1"
   ],
   [
      "Apollo",
      "1",
      "0",
      "1"
   ],
   [
      "Leto",
      "1",
      "0",
      "0"
   ],
   [
      "Ares",
      "1",
      "1",
      "1"
   ],
   [
      "Athena",
      "1",
      "1",
      "1"
   ],
   [
      "Hephaestus",
      "1",
      "1",
      "1"
   ],
   [
      "Aphrodite",
      "1",
      "1",
      "1"
   ],
   [
      "Cyclope",
      "1",
      "1",
      "1"
   ],
   [
      "Persephone",
      "1",
      "1",
      "1"
   ],
   [
      "Hermes",
      "1",
      "1",
      "0"
   ],
   [
      "Hebe",
      "1",
      "1",
      "0"
   ],
   [
      "Dionysus",
      "1",
      "1",
      "0"
   ]
]
