var GleserInfo ={
   "title" : "Example data from Gleser, Cronbach and Rajaratnam (1965) to show basic principles of generalizability theory.",
   "format" : "A data frame with 12 observations on the following 12 variables. J item by judge:",
   "reference" : "Generalizability theory is the application of a components of variance approach to the analysis of reliability.  Given a G study (generalizability) the components are estimated and then may be used in a D study (Decision).  Different ratios are formed as appropriate for the particular D study.",
   "parameters" : {
      "J42" : "a numeric vector",
      "J12" : "a numeric vector",
      "J21" : "a numeric vector",
      "J11" : "a numeric vector",
      "J22" : "a numeric vector",
      "J41" : "a numeric vector",
      "J32" : "a numeric vector",
      "J52" : "a numeric vector",
      "J62" : "a numeric vector",
      "J51" : "a numeric vector",
      "J61" : "a numeric vector",
      "J31" : "a numeric vector"
   },
   "usage" : "data(Gleser)",
   "description" : "Description\nGleser, Cronbach and Rajaratnam (1965) discuss the estimation of variance components and their ratios as part of their introduction to generalizability theory.  This is a adaptation of their \"illustrative data for a completely matched G study\" (Table 3).  12 patients are rated on 6 symptoms by two judges.  Components of variance are derived from the ANOVA."
}

var Gleser = [
   [
      "J11",
      "J12",
      "J21",
      "J22",
      "J31",
      "J32",
      "J41",
      "J42",
      "J51",
      "J52",
      "J61",
      "J62"
   ],
   [
      "0",
      "0",
      "2",
      "1",
      "2",
      "0",
      "2",
      "1",
      "1",
      "1",
      "1",
      "2"
   ],
   [
      "0",
      "0",
      "2",
      "1",
      "2",
      "0",
      "1",
      "2",
      "2",
      "1",
      "2",
      "1"
   ],
   [
      "0",
      "0",
      "1",
      "1",
      "3",
      "3",
      "2",
      "1",
      "2",
      "1",
      "1",
      "2"
   ],
   [
      "2",
      "0",
      "2",
      "1",
      "2",
      "2",
      "2",
      "1",
      "2",
      "1",
      "4",
      "1"
   ],
   [
      "0",
      "0",
      "1",
      "2",
      "2",
      "0",
      "2",
      "3",
      "3",
      "3",
      "3",
      "3"
   ],
   [
      "2",
      "0",
      "2",
      "1",
      "2",
      "0",
      "4",
      "1",
      "3",
      "3",
      "3",
      "1"
   ],
   [
      "0",
      "1",
      "3",
      "1",
      "3",
      "1",
      "3",
      "4",
      "2",
      "2",
      "2",
      "3"
   ],
   [
      "0",
      "0",
      "0",
      "1",
      "4",
      "3",
      "3",
      "4",
      "2",
      "3",
      "3",
      "3"
   ],
   [
      "1",
      "2",
      "2",
      "1",
      "3",
      "6",
      "1",
      "3",
      "2",
      "3",
      "2",
      "1"
   ],
   [
      "0",
      "1",
      "2",
      "4",
      "3",
      "3",
      "2",
      "2",
      "3",
      "5",
      "3",
      "1"
   ],
   [
      "3",
      "4",
      "2",
      "2",
      "3",
      "2",
      "4",
      "5",
      "3",
      "3",
      "5",
      "5"
   ],
   [
      "1",
      "1",
      "2",
      "4",
      "4",
      "4",
      "3",
      "3",
      "4",
      "6",
      "6",
      "6"
   ]
]
