var AMSsurveyInfo ={
   "format" : "A data frame with 24 observations on the following 5 variables.",
   "reference" : "These data are produced yearly by the American Math Society.",
   "title" : "American Math Society Survey Data",
   "parameters" : {
      "sex" : "a factor with levels Female, Male of the\nrecipient",
      "type" : "a factor with levels I(Pu) for group I\npublic universities, I(Pr) for group I private universities, II\nand III for groups II and III, IV for statistics and\nbiostatistics programs, and Va for applied mathemeatics programs.",
      "count" : "The number of individuals of each type in 2008-09",
      "citizen" : "a factor with levels Non-US, US giving\ncitizenship status",
      "count11" : "The number of individuals of each type in 2011-12"
   },
   "usage" : "AMSsurvey",
   "description" : "Description\nCounts of new PhDs in the mathematical sciences for 2008-09 and 2011-12\ncategorized by type of institution, gender, and US citizenship status."
}

var AMSsurvey = [
   [
      "type",
      "sex",
      "citizen",
      "count",
      "count11"
   ],
   [
      "I(Pu)",
      "Male",
      "US",
      "132",
      "148"
   ],
   [
      "I(Pu)",
      "Female",
      "US",
      "35",
      "40"
   ],
   [
      "I(Pr)",
      "Male",
      "US",
      "87",
      "63"
   ],
   [
      "I(Pr)",
      "Female",
      "US",
      "20",
      "22"
   ],
   [
      "II",
      "Male",
      "US",
      "96",
      "161"
   ],
   [
      "II",
      "Female",
      "US",
      "47",
      "53"
   ],
   [
      "III",
      "Male",
      "US",
      "47",
      "71"
   ],
   [
      "III",
      "Female",
      "US",
      "32",
      "28"
   ],
   [
      "IV",
      "Male",
      "US",
      "71",
      "89"
   ],
   [
      "IV",
      "Female",
      "US",
      "54",
      "55"
   ],
   [
      "Va",
      "Male",
      "US",
      "34",
      "42"
   ],
   [
      "Va",
      "Female",
      "US",
      "14",
      "21"
   ],
   [
      "I(Pu)",
      "Male",
      "Non-US",
      "130",
      "136"
   ],
   [
      "I(Pu)",
      "Female",
      "Non-US",
      "29",
      "32"
   ],
   [
      "I(Pr)",
      "Male",
      "Non-US",
      "79",
      "82"
   ],
   [
      "I(Pr)",
      "Female",
      "Non-US",
      "25",
      "26"
   ],
   [
      "II",
      "Male",
      "Non-US",
      "89",
      "116"
   ],
   [
      "II",
      "Female",
      "Non-US",
      "50",
      "56"
   ],
   [
      "III",
      "Male",
      "Non-US",
      "53",
      "61"
   ],
   [
      "III",
      "Female",
      "Non-US",
      "39",
      "30"
   ],
   [
      "IV",
      "Male",
      "Non-US",
      "122",
      "153"
   ],
   [
      "IV",
      "Female",
      "Non-US",
      "105",
      "115"
   ],
   [
      "Va",
      "Male",
      "Non-US",
      "28",
      "27"
   ],
   [
      "Va",
      "Female",
      "Non-US",
      "12",
      "17"
   ]
]
