var BurtInfo ={
   "format" : "This data frame contains the following columns:",
   "reference" : "Burt, C. (1966) \nThe genetic determination of differences in intelligence: \nA study of monozygotic twins reared together and apart. \nBritish Journal of Psychology 57, 137&ndash;153.",
   "title" : "Fraudulent Data on IQs of Twins Raised Apart",
   "parameters" : {
      "IQbio" : "IQ of twin raised by biological parents",
      "class" : "A factor with levels (note: out of order):\nhigh;\nlow;\nmedium.",
      "IQfoster" : "IQ of twin raised by foster parents"
   },
   "usage" : "Burt",
   "description" : "Description\nThe Burt data frame has 27 rows and 4 columns.\nThe &ldquo;data&rdquo; were simply (and notoriously) manufactured.  The\nsame data are in the dataset &ldquo;twins\" in the alr3\npackage, but with different labels."
}

var Burt = [
   [
      "IQbio",
      "IQfoster",
      "class"
   ],
   [
      "82",
      "82",
      "high"
   ],
   [
      "80",
      "90",
      "high"
   ],
   [
      "88",
      "91",
      "high"
   ],
   [
      "108",
      "115",
      "high"
   ],
   [
      "116",
      "115",
      "high"
   ],
   [
      "117",
      "129",
      "high"
   ],
   [
      "132",
      "131",
      "high"
   ],
   [
      "71",
      "78",
      "medium"
   ],
   [
      "75",
      "79",
      "medium"
   ],
   [
      "93",
      "82",
      "medium"
   ],
   [
      "95",
      "97",
      "medium"
   ],
   [
      "88",
      "100",
      "medium"
   ],
   [
      "111",
      "107",
      "medium"
   ],
   [
      "63",
      "68",
      "low"
   ],
   [
      "77",
      "73",
      "low"
   ],
   [
      "86",
      "81",
      "low"
   ],
   [
      "83",
      "85",
      "low"
   ],
   [
      "93",
      "87",
      "low"
   ],
   [
      "97",
      "87",
      "low"
   ],
   [
      "87",
      "93",
      "low"
   ],
   [
      "94",
      "94",
      "low"
   ],
   [
      "96",
      "95",
      "low"
   ],
   [
      "112",
      "97",
      "low"
   ],
   [
      "113",
      "97",
      "low"
   ],
   [
      "106",
      "103",
      "low"
   ],
   [
      "107",
      "106",
      "low"
   ],
   [
      "98",
      "111",
      "low"
   ]
]
