var FriendlyInfo ={
   "parameters" : {
      "correct" : "Number of words correctly recalled, out of 40 on final trial of the experiment.",
      "condition" : "A factor with levels:\nBefore, Recalled words presented before others;\nMeshed, Recalled words meshed with others; \nSFR, Standard free recall."
   },
   "reference" : "Friendly, M. and Franklin, P. (1980) \nInteractive presentation in multitrial free recall. \nMemory and Cognition\n8 265&ndash;270 [Personal communication from M. Friendly].",
   "usage" : "Friendly",
   "title" : "Format Effects on Recall",
   "description" : "Description\nThe Friendly data frame has 30 rows and 2 columns.\nThe data are from an experiment on subjects' ability to remember words\nbased on the presentation format.",
   "format" : "This data frame contains the following columns:"
}

var Friendly = [
   [
      "condition",
      "correct"
   ],
   [
      "SFR",
      "39"
   ],
   [
      "SFR",
      "25"
   ],
   [
      "SFR",
      "37"
   ],
   [
      "SFR",
      "25"
   ],
   [
      "SFR",
      "29"
   ],
   [
      "SFR",
      "39"
   ],
   [
      "SFR",
      "21"
   ],
   [
      "SFR",
      "39"
   ],
   [
      "SFR",
      "24"
   ],
   [
      "SFR",
      "25"
   ],
   [
      "Before",
      "40"
   ],
   [
      "Before",
      "38"
   ],
   [
      "Before",
      "39"
   ],
   [
      "Before",
      "37"
   ],
   [
      "Before",
      "39"
   ],
   [
      "Before",
      "24"
   ],
   [
      "Before",
      "30"
   ],
   [
      "Before",
      "39"
   ],
   [
      "Before",
      "40"
   ],
   [
      "Before",
      "40"
   ],
   [
      "Meshed",
      "40"
   ],
   [
      "Meshed",
      "39"
   ],
   [
      "Meshed",
      "34"
   ],
   [
      "Meshed",
      "37"
   ],
   [
      "Meshed",
      "40"
   ],
   [
      "Meshed",
      "36"
   ],
   [
      "Meshed",
      "36"
   ],
   [
      "Meshed",
      "38"
   ],
   [
      "Meshed",
      "36"
   ],
   [
      "Meshed",
      "30"
   ]
]
