var CushingsInfo ={
   "parameters" : {
      "Type" : "underlying type of syndrome, coded a (adenoma) , b\n(bilateral hyperplasia), c (carcinoma) or u for unknown.",
      "Pregnanetriol" : "urinary excretion rate (mg/24hr) of Pregnanetriol.",
      "Tetrahydrocortisone" : "urinary excretion rate (mg/24hr) of Tetrahydrocortisone."
   },
   "reference" : "J. Aitchison and I. R. Dunsmore (1975)\nStatistical Prediction Analysis.\nCambridge University Press, Tables 11.1&ndash;3.",
   "usage" : "Cushings",
   "title" : "Diagnostic Tests on Patients with Cushing's Syndrome",
   "description" : "Description\nCushing's syndrome is a hypertensive disorder associated with\nover-secretion of cortisol by the adrenal gland. The observations\nare urinary excretion rates of two steroid metabolites.",
   "format" : "The Cushings data frame has 27 rows and 3 columns:"
}

var Cushings = [
   [
      "Tetrahydrocortisone",
      "Pregnanetriol",
      "Type"
   ],
   [
      "3.1",
      "11.7",
      "a"
   ],
   [
      "3",
      "1.3",
      "a"
   ],
   [
      "1.9",
      "0.1",
      "a"
   ],
   [
      "3.8",
      "0.04",
      "a"
   ],
   [
      "4.1",
      "1.1",
      "a"
   ],
   [
      "1.9",
      "0.4",
      "a"
   ],
   [
      "8.3",
      "1",
      "b"
   ],
   [
      "3.8",
      "0.2",
      "b"
   ],
   [
      "3.9",
      "0.6",
      "b"
   ],
   [
      "7.8",
      "1.2",
      "b"
   ],
   [
      "9.1",
      "0.6",
      "b"
   ],
   [
      "15.4",
      "3.6",
      "b"
   ],
   [
      "7.7",
      "1.6",
      "b"
   ],
   [
      "6.5",
      "0.4",
      "b"
   ],
   [
      "5.7",
      "0.4",
      "b"
   ],
   [
      "13.6",
      "1.6",
      "b"
   ],
   [
      "10.2",
      "6.4",
      "c"
   ],
   [
      "9.2",
      "7.9",
      "c"
   ],
   [
      "9.6",
      "3.1",
      "c"
   ],
   [
      "53.8",
      "2.5",
      "c"
   ],
   [
      "15.8",
      "7.6",
      "c"
   ],
   [
      "5.1",
      "0.4",
      "u"
   ],
   [
      "12.9",
      "5",
      "u"
   ],
   [
      "13",
      "0.8",
      "u"
   ],
   [
      "2.6",
      "0.1",
      "u"
   ],
   [
      "30",
      "0.1",
      "u"
   ],
   [
      "20.5",
      "0.8",
      "u"
   ]
]
