var farmsInfo ={
   "format" : "This data frame contains the following columns:",
   "parameters" : {
      "Use" : "Grassland use (U1 = hay production, U2 =\nintermediate, U3 = grazing).",
      "Mois" : "Five levels of soil moisture &ndash; level 3 does not occur at these 20 farms.",
      "Manag" : "Grassland management type (SF = standard,\nBF = biological, HF = hobby farming,\nNM = nature conservation).",
      "Manure" : "Manure usage &ndash; classes C0 to C4."
   },
   "description" : "Description\nThe farms data frame has 20 rows and 4 columns. The rows are farms\non the Dutch island of Terschelling and the columns are factors\ndescribing the management of grassland.",
   "title" : "Ecological Factors in Farm Management",
   "reference" : "J.C. Gower and D.J. Hand (1996) Biplots. Chapman & Hall, Table 4.6.",
   "usage" : "farms"
}

var farms = [
   [
      "Mois",
      "Manag",
      "Use",
      "Manure",
      "Row"
   ],
   [
      "M1",
      "SF",
      "U2",
      "C4",
      1
   ],
   [
      "M1",
      "BF",
      "U2",
      "C2",
      2
   ],
   [
      "M2",
      "SF",
      "U2",
      "C4",
      3
   ],
   [
      "M2",
      "SF",
      "U2",
      "C4",
      4
   ],
   [
      "M1",
      "HF",
      "U1",
      "C2",
      5
   ],
   [
      "M1",
      "HF",
      "U2",
      "C2",
      6
   ],
   [
      "M1",
      "HF",
      "U3",
      "C3",
      7
   ],
   [
      "M5",
      "HF",
      "U3",
      "C3",
      8
   ],
   [
      "M4",
      "HF",
      "U1",
      "C1",
      9
   ],
   [
      "M2",
      "BF",
      "U1",
      "C1",
      10
   ],
   [
      "M1",
      "BF",
      "U3",
      "C1",
      11
   ],
   [
      "M4",
      "SF",
      "U2",
      "C2",
      12
   ],
   [
      "M5",
      "SF",
      "U2",
      "C3",
      13
   ],
   [
      "M5",
      "NM",
      "U3",
      "C0",
      14
   ],
   [
      "M5",
      "NM",
      "U2",
      "C0",
      15
   ],
   [
      "M5",
      "SF",
      "U3",
      "C3",
      16
   ],
   [
      "M2",
      "NM",
      "U1",
      "C0",
      17
   ],
   [
      "M1",
      "NM",
      "U1",
      "C0",
      18
   ],
   [
      "M5",
      "NM",
      "U1",
      "C0",
      19
   ],
   [
      "M5",
      "NM",
      "U1",
      "C0",
      20
   ]
]
