var leukInfo ={
   "usage" : "leuk",
   "description" : "Description\nA data frame of data from 33 leukaemia patients.",
   "title" : "Survival Times and White Blood Counts for Leukaemia Patients",
   "format" : "A data frame with columns:",
   "reference" : "Survival times are given for 33 patients who died from acute\nmyelogenous leukaemia.  Also measured was the patient's white blood cell\ncount at the time of diagnosis.  The patients were also factored into 2\ngroups according to the presence or absence of a morphologic\ncharacteristic of white blood cells. Patients termed AG positive were\nidentified by the presence of Auer rods and/or significant granulation\nof the leukaemic cells in the bone marrow at the time of diagnosis.",
   "parameters" : {
      "ag" : "a test result, \"present\" or \"absent\".",
      "time" : "survival time in weeks.",
      "wbc" : "white blood count."
   }
}

var leuk = [
   [
      "wbc",
      "ag",
      "time"
   ],
   [
      "2300",
      "present",
      "65"
   ],
   [
      "750",
      "present",
      "156"
   ],
   [
      "4300",
      "present",
      "100"
   ],
   [
      "2600",
      "present",
      "134"
   ],
   [
      "6000",
      "present",
      "16"
   ],
   [
      "10500",
      "present",
      "108"
   ],
   [
      "10000",
      "present",
      "121"
   ],
   [
      "17000",
      "present",
      "4"
   ],
   [
      "5400",
      "present",
      "39"
   ],
   [
      "7000",
      "present",
      "143"
   ],
   [
      "9400",
      "present",
      "56"
   ],
   [
      "32000",
      "present",
      "26"
   ],
   [
      "35000",
      "present",
      "22"
   ],
   [
      "100000",
      "present",
      "1"
   ],
   [
      "100000",
      "present",
      "1"
   ],
   [
      "52000",
      "present",
      "5"
   ],
   [
      "100000",
      "present",
      "65"
   ],
   [
      "4400",
      "absent",
      "56"
   ],
   [
      "3000",
      "absent",
      "65"
   ],
   [
      "4000",
      "absent",
      "17"
   ],
   [
      "1500",
      "absent",
      "7"
   ],
   [
      "9000",
      "absent",
      "16"
   ],
   [
      "5300",
      "absent",
      "22"
   ],
   [
      "10000",
      "absent",
      "3"
   ],
   [
      "19000",
      "absent",
      "4"
   ],
   [
      "27000",
      "absent",
      "2"
   ],
   [
      "28000",
      "absent",
      "3"
   ],
   [
      "31000",
      "absent",
      "8"
   ],
   [
      "26000",
      "absent",
      "4"
   ],
   [
      "21000",
      "absent",
      "3"
   ],
   [
      "79000",
      "absent",
      "30"
   ],
   [
      "100000",
      "absent",
      "4"
   ],
   [
      "100000",
      "absent",
      "43"
   ]
]
