var rotiferInfo ={
   "parameters" : {
      "kc.tot" : "total number of K. cochlearis.",
      "density" : "specific density of fluid.",
      "kc.y" : "number falling out for K. cochlearis.",
      "pm.y" : "number falling out for P. major.",
      "pm.total" : "total number of P. major."
   },
   "reference" : "D. Collett (1991) Modelling Binary Data. Chapman & Hall. p. 217",
   "title" : "Numbers of Rotifers by Fluid Density",
   "format" : "density\nspecific density of fluid.\n\n\npm.y\nnumber falling out for P. major.\n\n\npm.total\ntotal number of P. major.\n\n\nkc.y\nnumber falling out for K. cochlearis.\n\n\nkc.tot\ntotal number of K. cochlearis.",
   "description" : "Description\nThe data give the numbers of rotifers falling out of suspension for\ndifferent fluid densities. There are two species, pm\nPolyartha major and kc, Keratella cochlearis and\nfor each species the number falling out and the total number are\ngiven.",
   "usage" : "rotifer"
}

var rotifer = [
   [
      "density",
      "pm.y",
      "pm.tot",
      "kc.y",
      "kc.tot"
   ],
   [
      "1.019",
      "11",
      "58",
      "13",
      "161"
   ],
   [
      "1.02",
      "7",
      "86",
      "14",
      "248"
   ],
   [
      "1.021",
      "10",
      "76",
      "30",
      "234"
   ],
   [
      "1.03",
      "19",
      "83",
      "10",
      "283"
   ],
   [
      "1.03",
      "9",
      "56",
      "14",
      "129"
   ],
   [
      "1.03",
      "21",
      "73",
      "35",
      "161"
   ],
   [
      "1.031",
      "13",
      "29",
      "26",
      "167"
   ],
   [
      "1.04",
      "34",
      "44",
      "32",
      "286"
   ],
   [
      "1.04",
      "10",
      "31",
      "22",
      "117"
   ],
   [
      "1.041",
      "36",
      "56",
      "23",
      "162"
   ],
   [
      "1.048",
      "20",
      "27",
      "7",
      "42"
   ],
   [
      "1.049",
      "54",
      "59",
      "22",
      "48"
   ],
   [
      "1.05",
      "20",
      "22",
      "9",
      "49"
   ],
   [
      "1.05",
      "9",
      "14",
      "34",
      "160"
   ],
   [
      "1.06",
      "14",
      "17",
      "71",
      "74"
   ],
   [
      "1.061",
      "10",
      "22",
      "25",
      "45"
   ],
   [
      "1.063",
      "64",
      "66",
      "94",
      "101"
   ],
   [
      "1.07",
      "68",
      "86",
      "63",
      "68"
   ],
   [
      "1.07",
      "488",
      "492",
      "178",
      "190"
   ],
   [
      "1.07",
      "88",
      "89",
      "154",
      "154"
   ]
]
