var carrotsInfo ={
   "format" : "A data frame with 24 observations on the following 4 variables.",
   "parameters" : {
      "logdose" : "a numeric vector giving log(dose) values (eight\ndifferent levels only).",
      "block" : "factor with levels B1 to B3",
      "total" : "integer giving the total number of carrots per\nexperimental unit.",
      "success" : "integer giving the number of carrots with insect damage."
   },
   "title" : "Insect Damages on Carrots",
   "description" : "Description\nThe damage carrots data set from Phelps (1982) was used by McCullagh\nand Nelder (1989) in order to illustrate diagnostic techniques because\nof the presence of an outlier. In a soil experiment trial with three\nblocks, eight levels of insecticide were applied and the carrots were\ntested for insect damage.",
   "reference" : "Phelps, K. (1982).\nUse of the complementary log-log function to describe doseresponse\nrelationships in insecticide evaluation field trials.\n\nIn R. Gilchrist (Ed.), Lecture Notes in Statistics, No. 14.\nGLIM.82: Proceedings of the International Conference on Generalized\nLinear Models; Springer-Verlag.",
   "usage" : "data(carrots, package=\"robustbase\")"
}

var carrots = [
   [
      "success",
      "total",
      "logdose",
      "block"
   ],
   [
      "10",
      "35",
      "1.52",
      "B1"
   ],
   [
      "16",
      "42",
      "1.64",
      "B1"
   ],
   [
      "8",
      "50",
      "1.76",
      "B1"
   ],
   [
      "6",
      "42",
      "1.88",
      "B1"
   ],
   [
      "9",
      "35",
      "2",
      "B1"
   ],
   [
      "9",
      "42",
      "2.12",
      "B1"
   ],
   [
      "1",
      "32",
      "2.24",
      "B1"
   ],
   [
      "2",
      "28",
      "2.36",
      "B1"
   ],
   [
      "17",
      "38",
      "1.52",
      "B2"
   ],
   [
      "10",
      "40",
      "1.64",
      "B2"
   ],
   [
      "8",
      "33",
      "1.76",
      "B2"
   ],
   [
      "8",
      "39",
      "1.88",
      "B2"
   ],
   [
      "5",
      "47",
      "2",
      "B2"
   ],
   [
      "17",
      "42",
      "2.12",
      "B2"
   ],
   [
      "6",
      "35",
      "2.24",
      "B2"
   ],
   [
      "4",
      "35",
      "2.36",
      "B2"
   ],
   [
      "10",
      "34",
      "1.52",
      "B3"
   ],
   [
      "10",
      "38",
      "1.64",
      "B3"
   ],
   [
      "5",
      "36",
      "1.76",
      "B3"
   ],
   [
      "3",
      "35",
      "1.88",
      "B3"
   ],
   [
      "2",
      "49",
      "2",
      "B3"
   ],
   [
      "1",
      "40",
      "2.12",
      "B3"
   ],
   [
      "3",
      "22",
      "2.24",
      "B3"
   ],
   [
      "2",
      "31",
      "2.36",
      "B3"
   ]
]
