var starsCYGInfo ={
   "parameters" : {
      "log.Te" : "Logarithm of the effective temperature at the\nsurface of the star (Te).",
      "log.light" : "Logarithm of its light intencity (L/L_0)"
   },
   "title" : "Hertzsprung-Russell Diagram Data of Star Cluster CYG OB1",
   "description" : "Description\nData for the Hertzsprung-Russell Diagram of the Star Cluster CYG OB1,\nwhich contains 47 stars in the direction of Cygnus, from C.Doom.  The\nfirst variable is the logarithm of the effective temperature at the\nsurface of the star (Te) and the second one is the logarithm of its\nlight intencity (L/L_0).\nIn the Hertzsprung-Russell diagram, which is the scatterplot of these\ndata points, where the log temperature is plotted from left to right,\ntwo groups of points are seen:\nthe majority which tend to follow a steep band and four stars in the\nupper corner.  In the astronomy the 43 stars are said to lie on the\nmain sequence and the four remaining stars are called &ldquo;giants&rdquo; (the\npoints 11, 20, 30, 34).",
   "usage" : "data(starsCYG, package=\"robustbase\")",
   "reference" : "P. J. Rousseeuw and A. M. Leroy (1987)\nRobust Regression and Outlier Detection;\nWiley, p.27, table 3.",
   "format" : "A data frame with 47 observations on the following 2 variables"
}

var starsCYG = [
   [
      "log.Te",
      "log.light"
   ],
   [
      "4.37",
      "5.23"
   ],
   [
      "4.56",
      "5.74"
   ],
   [
      "4.26",
      "4.93"
   ],
   [
      "4.56",
      "5.74"
   ],
   [
      "4.3",
      "5.19"
   ],
   [
      "4.46",
      "5.46"
   ],
   [
      "3.84",
      "4.65"
   ],
   [
      "4.57",
      "5.27"
   ],
   [
      "4.26",
      "5.57"
   ],
   [
      "4.37",
      "5.12"
   ],
   [
      "3.49",
      "5.73"
   ],
   [
      "4.43",
      "5.45"
   ],
   [
      "4.48",
      "5.42"
   ],
   [
      "4.01",
      "4.05"
   ],
   [
      "4.29",
      "4.26"
   ],
   [
      "4.42",
      "4.58"
   ],
   [
      "4.23",
      "3.94"
   ],
   [
      "4.42",
      "4.18"
   ],
   [
      "4.23",
      "4.18"
   ],
   [
      "3.49",
      "5.89"
   ],
   [
      "4.29",
      "4.38"
   ],
   [
      "4.29",
      "4.22"
   ],
   [
      "4.42",
      "4.42"
   ],
   [
      "4.49",
      "4.85"
   ],
   [
      "4.38",
      "5.02"
   ],
   [
      "4.42",
      "4.66"
   ],
   [
      "4.29",
      "4.66"
   ],
   [
      "4.38",
      "4.9"
   ],
   [
      "4.22",
      "4.39"
   ],
   [
      "3.48",
      "6.05"
   ],
   [
      "4.38",
      "4.42"
   ],
   [
      "4.56",
      "5.1"
   ],
   [
      "4.45",
      "5.22"
   ],
   [
      "3.49",
      "6.29"
   ],
   [
      "4.23",
      "4.34"
   ],
   [
      "4.62",
      "5.62"
   ],
   [
      "4.53",
      "5.1"
   ],
   [
      "4.45",
      "5.22"
   ],
   [
      "4.53",
      "5.18"
   ],
   [
      "4.43",
      "5.57"
   ],
   [
      "4.38",
      "4.62"
   ],
   [
      "4.45",
      "5.06"
   ],
   [
      "4.5",
      "5.34"
   ],
   [
      "4.45",
      "5.34"
   ],
   [
      "4.55",
      "5.54"
   ],
   [
      "4.45",
      "4.98"
   ],
   [
      "4.42",
      "4.5"
   ]
]
