var DiabeticDogsInfo ={
   "description" : "Description\nThe rate of lactic acid turnover was measured by two methods for normal and diabetic dogs.",
   "parameters" : {
      "Operation" : "Pancreas removed to make the dog diabetic? (no or yes)",
      "Method" : "Tracer method to measure response (infuse or inject)",
      "Dog" : "Code for individual dogs (d1 through d10)",
      "Response" : "Rate for biochemical turnover of lactic acid"
   },
   "usage" : "A data frame with 20 observations on the following 4 variables.",
   "reference" : "Five dogs had their pancreas removed to make them diabetic (Operation=yes), the other five were normal (Operation=no). The rate of turnover of lactic acid was measured for each dog by two methods, infusion and injection.",
   "title" : "Lactic Acid Turnover in Dogs"
}

var DiabeticDogs = [
   [
      "Dog",
      "Method",
      "Operation",
      "Response"
   ],
   [
      "d1",
      "inject",
      "yes",
      "44"
   ],
   [
      "d2",
      "inject",
      "yes",
      "33"
   ],
   [
      "d3",
      "inject",
      "yes",
      "38"
   ],
   [
      "d4",
      "inject",
      "yes",
      "59"
   ],
   [
      "d5",
      "inject",
      "yes",
      "46"
   ],
   [
      "d6",
      "inject",
      "no",
      "54"
   ],
   [
      "d7",
      "inject",
      "no",
      "43"
   ],
   [
      "d8",
      "inject",
      "no",
      "55"
   ],
   [
      "d9",
      "inject",
      "no",
      "71"
   ],
   [
      "d10",
      "inject",
      "no",
      "57"
   ],
   [
      "d1",
      "infuse",
      "yes",
      "28"
   ],
   [
      "d2",
      "infuse",
      "yes",
      "23"
   ],
   [
      "d3",
      "infuse",
      "yes",
      "34"
   ],
   [
      "d4",
      "infuse",
      "yes",
      "19"
   ],
   [
      "d5",
      "infuse",
      "yes",
      "26"
   ],
   [
      "d6",
      "infuse",
      "no",
      "42"
   ],
   [
      "d7",
      "infuse",
      "no",
      "23"
   ],
   [
      "d8",
      "infuse",
      "no",
      "23"
   ],
   [
      "d9",
      "infuse",
      "no",
      "27"
   ],
   [
      "d10",
      "infuse",
      "no",
      "35"
   ]
]
