var DinosaursInfo ={
   "parameters" : {
      "ID" : "Sample identifier",
      "Depth" : "Depth of the sample (in meters)",
      "Iridium" : "Iridium concentration (ppb)",
      "Source" : "Type of rock (Limestone Shale)"
   },
   "description" : "Description\nIridium levels in prehistoric rock layers",
   "usage" : "A data frame with 28 observations on the following 4 variables.",
   "reference" : "The question of interest is whether a volcanic eruption or asteroid strike had created a dust cloud that led to extinction of most dinosaurs.  Rock samples taken in Gubbio, Italy were measured for the concentration of iridium (a rare metal which is more common in asteroids).  The deeper the sample, the older the rocks are.  A sudden increase in iridium at some point in time would lend support for the asteroid hypothesis.",
   "title" : "Iridium Levels in Rock Layers to Investigate Dinosaur Extinction"
}

var Dinosaurs = [
   [
      "ID",
      "Source",
      "Depth",
      "Iridium"
   ],
   [
      "1",
      "Limestone",
      "345",
      "75"
   ],
   [
      "2",
      "Limestone",
      "345",
      "20"
   ],
   [
      "3",
      "Limestone",
      "346",
      "120"
   ],
   [
      "4",
      "Limestone",
      "346",
      "210"
   ],
   [
      "5",
      "Limestone",
      "347",
      "290"
   ],
   [
      "6",
      "Limestone",
      "347",
      "450"
   ],
   [
      "7",
      "Limestone",
      "347",
      "620"
   ],
   [
      "8",
      "Limestone",
      "348",
      "170"
   ],
   [
      "9",
      "Limestone",
      "348",
      "205"
   ],
   [
      "10",
      "Limestone",
      "348",
      "260"
   ],
   [
      "11",
      "Limestone",
      "349",
      "120"
   ],
   [
      "12",
      "Limestone",
      "349",
      "135"
   ],
   [
      "13",
      "Limestone",
      "350",
      "5"
   ],
   [
      "14",
      "Limestone",
      "350",
      "90"
   ],
   [
      "15",
      "Limestone",
      "350",
      "105"
   ],
   [
      "16",
      "Shale",
      "345",
      "110"
   ],
   [
      "17",
      "Shale",
      "345",
      "501"
   ],
   [
      "18",
      "Shale",
      "346",
      "315"
   ],
   [
      "19",
      "Shale",
      "347",
      "710"
   ],
   [
      "20",
      "Shale",
      "347",
      "875"
   ],
   [
      "21",
      "Shale",
      "348",
      "400"
   ],
   [
      "22",
      "Shale",
      "349",
      "120"
   ],
   [
      "23",
      "Shale",
      "349",
      "130"
   ],
   [
      "24",
      "Shale",
      "349",
      "135"
   ],
   [
      "25",
      "Shale",
      "349",
      "10"
   ],
   [
      "26",
      "Shale",
      "349",
      "290"
   ],
   [
      "27",
      "Shale",
      "350",
      "145"
   ],
   [
      "28",
      "Shale",
      "350",
      "215"
   ]
]
