var LewyDLBadInfo ={
   "parameters" : {
      "MMSE" : "Change in functional performance on the Mini Mental State Examination",
      "APC" : "Annualized Percentage Change from baseline volume of the brain",
      "group" : "DLB/AD=DLB and Alzheimer's Disease"
   },
   "usage" : "A data frame with 20 observations on the following 3 variables.",
   "reference" : "Brain MRIs were used to study the brains of patients with Dementia with Lewy Bodies. These are the cases that were also diagnosed with Alzheimer's Disease.  This is a subset of LewBody2Groups",
   "description" : "Description\nDementia Study with Lewy Bodies",
   "title" : "Lewy Bodies and Dimentia with Alzheimer's"
}

var LewyDLBad = [
   [
      "group",
      "APC",
      "MMSE"
   ],
   [
      "DLB/AD",
      "1.26",
      "-2.21"
   ],
   [
      "DLB/AD",
      "0.53",
      "-4.18"
   ],
   [
      "DLB/AD",
      "0.49",
      "-0.14"
   ],
   [
      "DLB/AD",
      "0.38",
      "-2.04"
   ],
   [
      "DLB/AD",
      "0.13",
      "0.62"
   ],
   [
      "DLB/AD",
      "-0.63",
      "-1.88"
   ],
   [
      "DLB/AD",
      "-0.85",
      "-3.68"
   ],
   [
      "DLB/AD",
      "-0.92",
      "-1.58"
   ],
   [
      "DLB/AD",
      "-1.02",
      "-5.48"
   ],
   [
      "DLB/AD",
      "-1.16",
      "-3.73"
   ],
   [
      "DLB/AD",
      "-1.39",
      "-5.8"
   ],
   [
      "DLB/AD",
      "-1.58",
      "-6.82"
   ],
   [
      "DLB/AD",
      "-1.63",
      "-2.67"
   ],
   [
      "DLB/AD",
      "-1.81",
      "-6.03"
   ],
   [
      "DLB/AD",
      "-2.15",
      "-1.93"
   ],
   [
      "DLB/AD",
      "-2.28",
      "-8.33"
   ],
   [
      "DLB/AD",
      "-2.37",
      "-7.4"
   ],
   [
      "DLB/AD",
      "-2.58",
      "-3.18"
   ],
   [
      "DLB/AD",
      "-2.57",
      "-9.07"
   ],
   [
      "DLB/AD",
      "-2.65",
      "-3.84"
   ]
]
