var MeniscusInfo ={
   "title" : "Meniscus Repair Methods",
   "description" : "Description\nComparing meniscus repair methods on cadaver knees",
   "reference" : "Eighteen, lightly embalmed, cadaveric knee specimens were used in a study to compare three different methods of meniscus repair.  The specimens were randomly assigned to one of the three treatments: vertical suture, meniscus arrow, FasT-Fix.  They were evaluated on three different response variables: load at failure, stiffness, and displacement.",
   "usage" : "A data frame with 18 observations on the following 4 variables.",
   "parameters" : {
      "FailureLoad" : "Load at failure (in Newtons)",
      "Displacement" : "Displacement (in mm)",
      "Method" : "Meniscus repair method (1 = Vertical Suture, 2 = Meniscus Arrow, 3 = FasT-Fix)",
      "Stiffness" : "Stiffness (Newtons/mm)"
   }
}

var Meniscus = [
   [
      "Method",
      "FailureLoad",
      "Displacement",
      "Stiffness"
   ],
   [
      "1",
      "97.3",
      "16.9",
      "8.3"
   ],
   [
      "1",
      "106.4",
      "20.2",
      "7.2"
   ],
   [
      "1",
      "118.2",
      "20.1",
      "6.3"
   ],
   [
      "1",
      "99.7",
      "15.7",
      "7.3"
   ],
   [
      "1",
      "106.5",
      "13.9",
      "8.7"
   ],
   [
      "1",
      "84.2",
      "14.9",
      "8.7"
   ],
   [
      "2",
      "44.9",
      "7.9",
      "4.7"
   ],
   [
      "2",
      "46.1",
      "12.5",
      "6.1"
   ],
   [
      "2",
      "59.3",
      "15.5",
      "5"
   ],
   [
      "2",
      "35.5",
      "10.2",
      "5.8"
   ],
   [
      "2",
      "50.7",
      "8.9",
      "6.6"
   ],
   [
      "2",
      "56.8",
      "13.3",
      "8.4"
   ],
   [
      "3",
      "88",
      "18",
      "8"
   ],
   [
      "3",
      "119.8",
      "18.5",
      "8.3"
   ],
   [
      "3",
      "65.8",
      "9.2",
      "7.6"
   ],
   [
      "3",
      "82.9",
      "18.8",
      "6.4"
   ],
   [
      "3",
      "149.9",
      "22.8",
      "8.2"
   ],
   [
      "3",
      "117.1",
      "17.5",
      "7.7"
   ]
]
