var PKUInfo ={
   "parameters" : {
      "DietControl" : "Ability to follow prescribed diet  (Good or Poor)",
      "Y" : "Concentration of dopamine (micrograms per milligram of creatinine)",
      "Subject" : "Initials to identify each subject",
      "Diet" : "Level of phenylalanine in diet (Low or Normal)"
   },
   "description" : "Description\nDopamine levels with different amounts of phenylalanine in diets",
   "reference" : "Phenylketonuria (PKU) is an enzyme deficiency that keeps a person from being able to synthesize enough dopamine. The amino acid phenylalanine inhibits the enzyme needed to synthesize dopamine, and so to some extent, a diet low in phenylalanine can moderate the symptoms of PKU. In short, less phenylalanine in the diet should lead to more dopamine in the brain. The dopamine level for each patient was measured after a normal diet and after a week on a low phenylalanine diet.",
   "title" : "Dopamine levels with PKU in diets",
   "usage" : "A data frame with 20 observations on the following 4 variables."
}

var PKU = [
   [
      "Subject",
      "Diet",
      "DietControl",
      "Y"
   ],
   [
      "BR",
      "Normal",
      "Poor",
      "87"
   ],
   [
      "WJ",
      "Normal",
      "Poor",
      "35"
   ],
   [
      "KK",
      "Normal",
      "Poor",
      "36"
   ],
   [
      "TK",
      "Normal",
      "Poor",
      "72"
   ],
   [
      "AS",
      "Normal",
      "Poor",
      "20"
   ],
   [
      "BR",
      "Low",
      "Poor",
      "166"
   ],
   [
      "WJ",
      "Low",
      "Poor",
      "27"
   ],
   [
      "KK",
      "Low",
      "Poor",
      "70"
   ],
   [
      "TK",
      "Low",
      "Poor",
      "94"
   ],
   [
      "AS",
      "Low",
      "Poor",
      "52"
   ],
   [
      "DA",
      "Normal",
      "Good",
      "50"
   ],
   [
      "MB",
      "Normal",
      "Good",
      "40"
   ],
   [
      "MF",
      "Normal",
      "Good",
      "117"
   ],
   [
      "MK",
      "Normal",
      "Good",
      "97"
   ],
   [
      "TW",
      "Normal",
      "Good",
      "36"
   ],
   [
      "DA",
      "Low",
      "Good",
      "192"
   ],
   [
      "MB",
      "Low",
      "Good",
      "158"
   ],
   [
      "MF",
      "Low",
      "Good",
      "103"
   ],
   [
      "MK",
      "Low",
      "Good",
      "197"
   ],
   [
      "TW",
      "Low",
      "Good",
      "150"
   ]
]
