var RadioactiveTwinsInfo ={
   "description" : "Description\nExperiment comparing twins (one urban, one rural) ability to clear airborne radioactive particles from their lungs",
   "parameters" : {
      "Env" : "Residential environment  (Rural or Urban)",
      "TwinPair" : "Identifies the twin pairs (1 to 15)",
      "Rate" : "Clearance rate (percentage radioactive particles remaining after one hour)"
   },
   "reference" : "To assess lung health, the scientists measured \"tracheobronchial clearance rate,\" that is, in English, \"How fast do your lungs get rid of nasty stuff?\"  Each subject agreed to inhale an aerosol of radioactive Teflon particles.  A Geiger counter held to the chest measured the radioactivity just after inhaling, and again one hour later.  The clearance rate was the percentage of radioactivity remaining &ndash; the lower the better.  Subjects were 15 sets of identical twins, each pair with one twin living in an urban environment and the other in a rural environment.",
   "title" : "Comparing Twins Ability to Clear Radioactive Particles",
   "usage" : "A data frame with 30 observations on the following 3 variables."
}

var RadioactiveTwins = [
   [
      "TwinPair",
      "Env",
      "Rate"
   ],
   [
      "1",
      "Rural",
      "10.1"
   ],
   [
      "2",
      "Rural",
      "51.8"
   ],
   [
      "3",
      "Rural",
      "33.5"
   ],
   [
      "4",
      "Rural",
      "32.8"
   ],
   [
      "5",
      "Rural",
      "69"
   ],
   [
      "6",
      "Rural",
      "38.8"
   ],
   [
      "7",
      "Rural",
      "54.6"
   ],
   [
      "8",
      "Rural",
      "42.8"
   ],
   [
      "9",
      "Rural",
      "15.2"
   ],
   [
      "10",
      "Rural",
      "72.2"
   ],
   [
      "11",
      "Rural",
      "23.7"
   ],
   [
      "12",
      "Rural",
      "38"
   ],
   [
      "13",
      "Rural",
      "84.8"
   ],
   [
      "14",
      "Rural",
      "12.5"
   ],
   [
      "15",
      "Rural",
      "52.2"
   ],
   [
      "1",
      "Urban",
      "28.1"
   ],
   [
      "2",
      "Urban",
      "36.2"
   ],
   [
      "3",
      "Urban",
      "40.7"
   ],
   [
      "4",
      "Urban",
      "38.8"
   ],
   [
      "5",
      "Urban",
      "71"
   ],
   [
      "6",
      "Urban",
      "47"
   ],
   [
      "7",
      "Urban",
      "57"
   ],
   [
      "8",
      "Urban",
      "65.9"
   ],
   [
      "9",
      "Urban",
      "20.1"
   ],
   [
      "10",
      "Urban",
      "61.6"
   ],
   [
      "11",
      "Urban",
      "16.4"
   ],
   [
      "12",
      "Urban",
      "52.3"
   ],
   [
      "13",
      "Urban",
      "78.6"
   ],
   [
      "14",
      "Urban",
      "22.3"
   ],
   [
      "15",
      "Urban",
      "39.7"
   ]
]
