var ethanolInfo ={
   "usage" : "ethanol",
   "description" : "Description\nExperiment where 3 different treatments of ethanol were tested on the\ntreatment of oral cancer tumors in hamsters.",
   "reference" : "The ethyl_cellulose and pure_ethanol treatments consisted of\nabout a quarter of the volume of the tumors, while the\npure_ethanol_16x treatment was 16x that, so about 4 times the size of\nthe tumors.",
   "title" : "Ethanol Treatment for Tumors Experiment",
   "format" : "A data frame with 24 observations, each representing one hamster, on\nthe following 2 variables.",
   "parameters" : {
      "regress" : "a factor with levels no\nyes",
      "treatment" : "Treatment\nthe hamster received."
   }
}

var ethanol = [
   [
      "treatment",
      "regress",
      "Row"
   ],
   [
      "pure_ethanol_16x",
      "yes",
      1
   ],
   [
      "pure_ethanol_16x",
      "yes",
      2
   ],
   [
      "pure_ethanol_16x",
      "yes",
      3
   ],
   [
      "pure_ethanol_16x",
      "yes",
      4
   ],
   [
      "pure_ethanol_16x",
      "no",
      5
   ],
   [
      "pure_ethanol_16x",
      "no",
      6
   ],
   [
      "pure_ethanol_16x",
      "no",
      7
   ],
   [
      "pure_ethanol_16x",
      "no",
      8
   ],
   [
      "pure_ethanol_16x",
      "no",
      9
   ],
   [
      "pure_ethanol_16x",
      "no",
      10
   ],
   [
      "pure_ethanol_16x",
      "no",
      11
   ],
   [
      "pure_ethanol_16x",
      "no",
      12
   ],
   [
      "pure_ethanol",
      "no",
      13
   ],
   [
      "pure_ethanol",
      "no",
      14
   ],
   [
      "pure_ethanol",
      "no",
      15
   ],
   [
      "pure_ethanol",
      "no",
      16
   ],
   [
      "pure_ethanol",
      "no",
      17
   ],
   [
      "ethyl_cellulose",
      "yes",
      18
   ],
   [
      "ethyl_cellulose",
      "yes",
      19
   ],
   [
      "ethyl_cellulose",
      "yes",
      20
   ],
   [
      "ethyl_cellulose",
      "yes",
      21
   ],
   [
      "ethyl_cellulose",
      "yes",
      22
   ],
   [
      "ethyl_cellulose",
      "yes",
      23
   ],
   [
      "ethyl_cellulose",
      "no",
      24
   ]
]
