var fish_oil_18Info ={
   "usage" : "fish_oil_18",
   "description" : "Description\nThe results summarize each of the health outcomes for an experiment where\n12,933 subjects received a 1g fish oil supplement daily and 12,938 received\na placebo daily.  The experiment's duration was 5-years.",
   "format" : "The format is a list of 24 matrices.  Each matrix is a 2x2 table,\nand below are the named items in the list, which also represent the\noutcomes.",
   "reference" : "Manson JE, et al. 2018. Marine n-3 Fatty Acids and Prevention of\nCardiovascular Disease and Cancer. NEJMoa1811403.\ndoi:10.1056/NEJMoa1811403.",
   "title" : "Findings on n-3 Fatty Acid Supplement Health Benefits",
   "parameters" : {
      "cardio_event_expanded" : "Cardiovascular event in expanded composite endpoint.",
      "major_cardio_event_after_2y" : "Major cardiovascular event, excluding the first 2 years of follow-up.",
      "ischemic_stroke" : "Ischemic stroke.",
      "cardio_death" : "Death from cardiovascular causes.",
      "breast_cancer" : "Breast cancer.",
      "cancer_death" : "Death from cancer.",
      "invasive_cancer" : "Invasive cancer of any type. (Primary end point.)",
      "death_after_2y" : "Death from any cause, excluding the first 2 years of follow-up.",
      "colorectal_cancer" : "Colorectal cancer.",
      "CABG" : "Coronary artery bypass graft.",
      "myocardial_infarction_after_2y" : "Total myocardial infarction, excluding the first 2 years of follow-up.",
      "chd_death" : "Death from coronary heart disease.",
      "hemorrhagic_stroke" : "Hemorrhagic stroke.",
      "PCI" : "Percutaneous coronary intervention.",
      "prostate_cancer" : "Prostate cancer.",
      "total_coronary_heart_disease" : "Total coronary heart disease.",
      "stroke" : "Total stroke.",
      "myocardial_infarction_death" : "Death from myocardial infraction.",
      "cancer_death_after_2y" : "Death from cancer, excluding the first 2 years of follow-up.",
      "myocardioal_infarction" : "Total myocardial infarction. (Heart attack.)",
      "invasive_cancer_after_2y" : "Invasive cancer of any type, excluding the first 2 years of follow-up.",
      "stroke_death" : "Death from stroke.",
      "major_cardio_event" : "Major cardiovascular event. (Primary end point.)",
      "death" : "Death from any cause."
   }
}

var fish_oil_18 = [
   [
      "major_cardio_event.major_cardio_event",
      "major_cardio_event.no_event",
      "cardio_event_expanded.cardio_event_expanded",
      "cardio_event_expanded.no_event",
      "myocardioal_infarction.myocardioal_infarction",
      "myocardioal_infarction.no_event",
      "stroke.stroke",
      "stroke.no_event",
      "cardio_death.cardio_death",
      "cardio_death.no_event",
      "PCI.PCI",
      "PCI.not_performed",
      "CABG.CABG",
      "CABG.not_performed",
      "total_coronary_heart_disease.total_coronary_heart_disease",
      "total_coronary_heart_disease.not_present",
      "ischemic_stroke.ischemic_stroke",
      "ischemic_stroke.not_present",
      "hemorrhagic_stroke.hemorrhagic_stroke",
      "hemorrhagic_stroke.not_present",
      "chd_death.chd_death",
      "chd_death.not_present",
      "myocardial_infarction_death.myocardial_infarction_death",
      "myocardial_infarction_death.not_present",
      "stroke_death.stroke_death",
      "stroke_death.not_present",
      "invasive_cancer.invasive_cancer",
      "invasive_cancer.not_present",
      "breast_cancer.breast_cancer",
      "breast_cancer.not_present",
      "prostate_cancer.prostate_cancer",
      "prostate_cancer.not_present",
      "colorectal_cancer.colorectal_cancer",
      "colorectal_cancer.not_present",
      "cancer_death.cancer_death",
      "cancer_death.no_cancer_death",
      "death.death",
      "death.alive",
      "major_cardio_event_after_2y.major_cardio_event_after_2y",
      "major_cardio_event_after_2y.no_event",
      "myocardial_infarction_after_2y.myocardial_infarction_after_2y",
      "myocardial_infarction_after_2y.no_event",
      "invasive_cancer_after_2y.invasive_cancer_after_2y",
      "invasive_cancer_after_2y.no_event",
      "cancer_death_after_2y.cancer_death_after_2y",
      "cancer_death_after_2y.no_event",
      "death_after_2y.death_after_2y",
      "death_after_2y.remained_alive"
   ],
   [
      "386",
      "12547",
      "527",
      "12406",
      "145",
      "12788",
      "148",
      "12785",
      "142",
      "12791",
      "162",
      "12771",
      "85",
      "12848",
      "308",
      "12625",
      "111",
      "12822",
      "25",
      "12908",
      "37",
      "12896",
      "13",
      "12920",
      "22",
      "12911",
      "820",
      "12113",
      "117",
      "12816",
      "219",
      "12714",
      "54",
      "12879",
      "168",
      "12765",
      "493",
      "12440",
      "269",
      "12664",
      "94",
      "12839",
      "536",
      "12397",
      "126",
      "12807",
      "371",
      "12562"
   ],
   [
      "419",
      "12519",
      "567",
      "12371",
      "200",
      "12738",
      "142",
      "12796",
      "148",
      "12790",
      "208",
      "12730",
      "86",
      "12852",
      "370",
      "12568",
      "116",
      "12822",
      "19",
      "12919",
      "49",
      "12889",
      "26",
      "12912",
      "20",
      "12918",
      "797",
      "12141",
      "129",
      "12809",
      "192",
      "12746",
      "44",
      "12894",
      "173",
      "12765",
      "485",
      "12453",
      "301",
      "12637",
      "131",
      "12807",
      "476",
      "12462",
      "135",
      "12803",
      "381",
      "12557"
   ]
]
