var oringsInfo ={
   "usage" : "orings",
   "reference" : "https://archive.ics.uci.edu/dataset/92/challenger+usa+space+shuttle+o+ring",
   "description" : "Description\nOn January 28, 1986, a routine launch was anticipated for the Challenger\nspace shuttle. Seventy-three seconds into the flight, disaster happened: the\nshuttle broke apart, killing all seven crew members on board. An\ninvestigation into the cause of the disaster focused on a critical seal\ncalled an O-ring, and it is believed that damage to these O-rings during a\nshuttle launch may be related to the ambient temperature during the launch.\nThe table below summarizes observational data on O-rings for 23 shuttle\nmissions, where the mission order is based on the temperature at the time of\nthe launch.",
   "title" : "1986 Challenger disaster and O-rings",
   "parameters" : {
      "damaged" : "Number of damaged O-rings (out of 6).",
      "undamaged" : "Number of undamaged O-rings (out of 6).",
      "temperature" : "Temperature, in Fahrenheit.",
      "mission" : "Shuttle mission number."
   },
   "format" : "A data frame with 23 observations on the following 4 variables."
}

var orings = [
   [
      "mission",
      "temperature",
      "damaged",
      "undamaged"
   ],
   [
      "1",
      "53",
      "5",
      "1"
   ],
   [
      "2",
      "57",
      "1",
      "5"
   ],
   [
      "3",
      "58",
      "1",
      "5"
   ],
   [
      "4",
      "63",
      "1",
      "5"
   ],
   [
      "5",
      "66",
      "0",
      "6"
   ],
   [
      "6",
      "67",
      "0",
      "6"
   ],
   [
      "7",
      "67",
      "0",
      "6"
   ],
   [
      "8",
      "67",
      "0",
      "6"
   ],
   [
      "9",
      "68",
      "0",
      "6"
   ],
   [
      "10",
      "69",
      "0",
      "6"
   ],
   [
      "11",
      "70",
      "1",
      "5"
   ],
   [
      "12",
      "70",
      "0",
      "6"
   ],
   [
      "13",
      "70",
      "1",
      "5"
   ],
   [
      "14",
      "70",
      "0",
      "6"
   ],
   [
      "15",
      "72",
      "0",
      "6"
   ],
   [
      "16",
      "73",
      "0",
      "6"
   ],
   [
      "17",
      "75",
      "0",
      "6"
   ],
   [
      "18",
      "75",
      "1",
      "5"
   ],
   [
      "19",
      "76",
      "0",
      "6"
   ],
   [
      "20",
      "76",
      "0",
      "6"
   ],
   [
      "21",
      "78",
      "0",
      "6"
   ],
   [
      "22",
      "79",
      "0",
      "6"
   ],
   [
      "23",
      "81",
      "0",
      "6"
   ]
]
