var agefatInfo ={
   "parameters" : {
      "sex" : "a factor with levels female and male.",
      "fat" : "the body fat percentage.",
      "age" : "the age of the subject."
   },
   "usage" : "data(\"agefat\")",
   "reference" : "The data come from a study investigating a new methods of measuring body \ncomposition (see Mazess et al, 1984), and give the body fat percentage \n(percent fat), age and sex for 25 normal adults aged between 23 and 61 years.  \nThe questions of interest are how are age and percent fat related, and is \nthere any evidence that the relationship is different for males and females.",
   "description" : "Description\nAge and body fat percentage of 25 normal adults.",
   "title" : "Total Body Composision Data",
   "format" : "A data frame with 25 observations on the following 3 variables."
}

var agefat = [
   [
      "age",
      "fat",
      "sex"
   ],
   [
      "24",
      "15.5",
      "male"
   ],
   [
      "37",
      "20.9",
      "male"
   ],
   [
      "41",
      "18.6",
      "male"
   ],
   [
      "60",
      "28",
      "male"
   ],
   [
      "31",
      "34.7",
      "female"
   ],
   [
      "39",
      "30.2",
      "female"
   ],
   [
      "58",
      "21.3",
      "male"
   ],
   [
      "23",
      "9.5",
      "male"
   ],
   [
      "23",
      "27.9",
      "female"
   ],
   [
      "27",
      "7.8",
      "male"
   ],
   [
      "27",
      "17.8",
      "male"
   ],
   [
      "39",
      "31.4",
      "female"
   ],
   [
      "41",
      "25.9",
      "male"
   ],
   [
      "45",
      "27.4",
      "male"
   ],
   [
      "49",
      "25.2",
      "female"
   ],
   [
      "50",
      "31.1",
      "female"
   ],
   [
      "53",
      "34.7",
      "female"
   ],
   [
      "53",
      "42",
      "female"
   ],
   [
      "54",
      "29.1",
      "female"
   ],
   [
      "56",
      "32.5",
      "female"
   ],
   [
      "57",
      "30.3",
      "female"
   ],
   [
      "58",
      "33",
      "female"
   ],
   [
      "58",
      "33.8",
      "female"
   ],
   [
      "60",
      "41.1",
      "female"
   ],
   [
      "61",
      "34.5",
      "female"
   ]
]
