var cloudsInfo ={
   "format" : "A data frame with 24 observations on the following 7 variables.",
   "parameters" : {
      "seeding" : "a factor indicating whether seeding action occured (no\nor yes).",
      "sne" : "suitability criterion.",
      "prewetness" : "the total rainfall in the target area one hour before\nseeding (in cubic metres times 1e+8).",
      "rainfall" : "the amount of rain in cubic metres times 1e+8.",
      "time" : "number of days after the first day of the experiment.",
      "echomotion" : "a factor showing whether the radar echo was\nmoving or stationary.",
      "cloudcover" : "the percentage cloud cover in the experimental area,\nmeasured using radar."
   },
   "reference" : "Weather modification, or cloud seeding, is the treatment of individual\nclouds or storm systems with various inorganic and organic materials\nin the hope of achieving an increase in rainfall. Introduction\nof such material into a cloud that contains supercooled water,\nthat is, liquid water colder than zero Celsius, has the aim of \ninducing freezing, with the consequent ice particles growing  \nat the expense of liquid droplets and becoming heavy enough to\nfall as rain from clouds that otherwise would produce none.",
   "usage" : "data(\"clouds\")",
   "title" : "Cloud Seeding Data",
   "description" : "Description\nData from an experiment investigating the use of massive \namounts of silver iodide (100 to 1000 grams per cloud) in cloud\nseeding to increase rainfall."
}

var clouds = [
   [
      "seeding",
      "time",
      "sne",
      "cloudcover",
      "prewetness",
      "echomotion",
      "rainfall"
   ],
   [
      "no",
      "0",
      "1.75",
      "13.4",
      "0.274",
      "stationary",
      "12.85"
   ],
   [
      "yes",
      "1",
      "2.7",
      "37.9",
      "1.267",
      "moving",
      "5.52"
   ],
   [
      "yes",
      "3",
      "4.1",
      "3.9",
      "0.198",
      "stationary",
      "6.29"
   ],
   [
      "no",
      "4",
      "2.35",
      "5.3",
      "0.526",
      "moving",
      "6.11"
   ],
   [
      "yes",
      "6",
      "4.25",
      "7.1",
      "0.25",
      "moving",
      "2.45"
   ],
   [
      "no",
      "9",
      "1.6",
      "6.9",
      "0.018",
      "stationary",
      "3.61"
   ],
   [
      "no",
      "18",
      "1.3",
      "4.6",
      "0.307",
      "moving",
      "0.47"
   ],
   [
      "no",
      "25",
      "3.35",
      "4.9",
      "0.194",
      "moving",
      "4.56"
   ],
   [
      "no",
      "27",
      "2.85",
      "12.1",
      "0.751",
      "moving",
      "6.35"
   ],
   [
      "yes",
      "28",
      "2.2",
      "5.2",
      "0.084",
      "moving",
      "5.06"
   ],
   [
      "yes",
      "29",
      "4.4",
      "4.1",
      "0.236",
      "moving",
      "2.76"
   ],
   [
      "yes",
      "32",
      "3.1",
      "2.8",
      "0.214",
      "moving",
      "4.05"
   ],
   [
      "no",
      "33",
      "3.95",
      "6.8",
      "0.796",
      "moving",
      "5.74"
   ],
   [
      "yes",
      "35",
      "2.9",
      "3",
      "0.124",
      "moving",
      "4.84"
   ],
   [
      "yes",
      "38",
      "2.05",
      "7",
      "0.144",
      "moving",
      "11.86"
   ],
   [
      "no",
      "39",
      "4",
      "11.3",
      "0.398",
      "moving",
      "4.45"
   ],
   [
      "no",
      "53",
      "3.35",
      "4.2",
      "0.237",
      "stationary",
      "3.66"
   ],
   [
      "yes",
      "55",
      "3.7",
      "3.3",
      "0.96",
      "moving",
      "4.22"
   ],
   [
      "no",
      "56",
      "3.8",
      "2.2",
      "0.23",
      "moving",
      "1.16"
   ],
   [
      "yes",
      "59",
      "3.4",
      "6.5",
      "0.142",
      "stationary",
      "5.45"
   ],
   [
      "yes",
      "65",
      "3.15",
      "3.1",
      "0.073",
      "moving",
      "2.02"
   ],
   [
      "no",
      "68",
      "3.15",
      "2.6",
      "0.136",
      "moving",
      "0.82"
   ],
   [
      "yes",
      "82",
      "4.01",
      "8.3",
      "0.123",
      "moving",
      "1.09"
   ],
   [
      "no",
      "83",
      "4.65",
      "7.4",
      "0.168",
      "moving",
      "0.28"
   ]
]
