var polyps3Info ={
   "usage" : "data(\"polyps3\")",
   "description" : "Description\nData from a placebo-controlled trial of a non-steroidal anti-inflammatory\ndrug in the treatment of familial andenomatous polyposis (FAP).",
   "title" : "Familial Andenomatous Polyposis",
   "reference" : "The data arise from the same study as the polyps data. Here, \nthe number of polyps after three months are given.",
   "format" : "A data frame with 22 observations on the following 5 variables.",
   "parameters" : {
      "age" : "the age of the patient.",
      "baseline" : "the baseline number of polyps.",
      "sex" : "a factor with levels female and male.",
      "treatment" : "a factor with levels placebo and active.",
      "number3m" : "the number of polyps after three month."
   }
}

var polyps3 = [
   [
      "sex",
      "treatment",
      "baseline",
      "age",
      "number3m"
   ],
   [
      "female",
      "active",
      "7",
      "17",
      "6"
   ],
   [
      "female",
      "placebo",
      "77",
      "20",
      "67"
   ],
   [
      "male",
      "active",
      "7",
      "16",
      "4"
   ],
   [
      "female",
      "placebo",
      "5",
      "18",
      "5"
   ],
   [
      "male",
      "active",
      "23",
      "22",
      "16"
   ],
   [
      "female",
      "placebo",
      "35",
      "13",
      "31"
   ],
   [
      "female",
      "active",
      "11",
      "23",
      "6"
   ],
   [
      "male",
      "placebo",
      "12",
      "34",
      "20"
   ],
   [
      "male",
      "placebo",
      "7",
      "50",
      "7"
   ],
   [
      "male",
      "placebo",
      "318",
      "19",
      "347"
   ],
   [
      "male",
      "active",
      "160",
      "17",
      "142"
   ],
   [
      "female",
      "active",
      "8",
      "23",
      "1"
   ],
   [
      "male",
      "placebo",
      "20",
      "22",
      "16"
   ],
   [
      "male",
      "placebo",
      "11",
      "30",
      "20"
   ],
   [
      "male",
      "placebo",
      "24",
      "27",
      "26"
   ],
   [
      "male",
      "active",
      "34",
      "23",
      "27"
   ],
   [
      "female",
      "placebo",
      "54",
      "22",
      "45"
   ],
   [
      "male",
      "active",
      "16",
      "13",
      "10"
   ],
   [
      "male",
      "placebo",
      "30",
      "34",
      "30"
   ],
   [
      "female",
      "active",
      "10",
      "23",
      "6"
   ],
   [
      "female",
      "active",
      "20",
      "22",
      "5"
   ],
   [
      "male",
      "active",
      "12",
      "42",
      "8"
   ]
]
