var smokingInfo ={
   "parameters" : {
      "tc" : "the total number of subject not being treated.",
      "tt" : "the totla number of treated subjects.",
      "qt" : "the number of treated subjetcs who stopped\nsmoking.",
      "qc" : "the number of  subjetcs who stopped\nsmoking without being treated."
   },
   "title" : "Nicotine Gum and Smoking Cessation",
   "reference" : "Cigarette smoking is the leading cause of preventable death in\nthe United States and kills more Americans than AIDS, alcohol,\nillegal drug use, car accidents, fires, murders and suicides\ncombined. It has been estimated that 430,000 Americans die from\nsmoking every year. Fighting tobacco use is, consequently, one\nof the major public health goals of our time and there are now\nmany programs available designed to help smokers quit. One of\nthe major aids used in these programs is nicotine chewing gum,\nwhich acts as a substitute oral activity and provides a source\nof nicotine that reduces the withdrawal symptoms experienced\nwhen smoking is stopped. But separate randomized clinical trials\nof nicotine gum have been largely inconclusive, leading\nSilagy (2003) to consider combining the results studies\nfound from an extensive literature search. The results of these\ntrials in terms of numbers of people in the treatment arm and\nthe control arm who stopped smoking for at least 6 months after\ntreatment are given here.",
   "format" : "A data frame with 26 observations (studies) on the following 4 variables.",
   "description" : "Description\nData from a meta-analysis on nicotine gum and smoking cessation",
   "usage" : "data(\"smoking\")"
}

var smoking = [
   [
      "qt",
      "tt",
      "qc",
      "tc"
   ],
   [
      "37",
      "92",
      "24",
      "90"
   ],
   [
      "21",
      "107",
      "21",
      "105"
   ],
   [
      "30",
      "50",
      "23",
      "50"
   ],
   [
      "23",
      "180",
      "15",
      "172"
   ],
   [
      "21",
      "68",
      "5",
      "38"
   ],
   [
      "75",
      "405",
      "17",
      "203"
   ],
   [
      "37",
      "131",
      "6",
      "46"
   ],
   [
      "18",
      "41",
      "10",
      "36"
   ],
   [
      "30",
      "71",
      "14",
      "68"
   ],
   [
      "24",
      "98",
      "28",
      "103"
   ],
   [
      "31",
      "106",
      "16",
      "100"
   ],
   [
      "31",
      "54",
      "11",
      "60"
   ],
   [
      "22",
      "58",
      "9",
      "58"
   ],
   [
      "90",
      "211",
      "28",
      "82"
   ],
   [
      "16",
      "44",
      "6",
      "20"
   ],
   [
      "129",
      "600",
      "112",
      "617"
   ],
   [
      "6",
      "73",
      "3",
      "121"
   ],
   [
      "51",
      "146",
      "40",
      "127"
   ],
   [
      "13",
      "30",
      "5",
      "30"
   ],
   [
      "5",
      "84",
      "4",
      "89"
   ],
   [
      "75",
      "206",
      "50",
      "211"
   ],
   [
      "29",
      "116",
      "21",
      "113"
   ],
   [
      "9",
      "30",
      "6",
      "30"
   ],
   [
      "23",
      "60",
      "12",
      "53"
   ],
   [
      "11",
      "21",
      "10",
      "26"
   ],
   [
      "23",
      "58",
      "18",
      "58"
   ]
]
