var waterInfo ={
   "reference" : "The data were collected in an investigation\nof environmental causes of disease. They show the annual mortality\nper 100,000 for males, averaged over the years 1958-1964, and\nthe calcium concentration (in parts per million) in the drinking\nwater for 61 large towns in England and Wales. The higher the \ncalcium concentration, the harder the water. Towns at least   \nas far north as Derby are identified in the table. Here there\nare several questions that might be of interest including, are\nmortality and water hardness related, and do either or both variables\ndiffer between northern and southern towns?",
   "usage" : "data(\"water\")",
   "title" : "Mortality and Water Hardness",
   "description" : "Description\nThe mortality and drinking water hardness for 61 cities in England and\nWales.",
   "parameters" : {
      "town" : "the name of the town.",
      "hardness" : "calcium concentration (in parts per million).",
      "location" : "a factor with levels North and South indicating\nwhether the town is as north as Derby.",
      "mortality" : "averaged annual mortality per 100.000 male inhabitants."
   },
   "format" : "A data frame with 61 observations on the following 4 variables."
}

var water = [
   [
      "location",
      "town",
      "mortality",
      "hardness"
   ],
   [
      "South",
      "Bath",
      "1247",
      "105"
   ],
   [
      "North",
      "Birkenhead",
      "1668",
      "17"
   ],
   [
      "South",
      "Birmingham",
      "1466",
      "5"
   ],
   [
      "North",
      "Blackburn",
      "1800",
      "14"
   ],
   [
      "North",
      "Blackpool",
      "1609",
      "18"
   ],
   [
      "North",
      "Bolton",
      "1558",
      "10"
   ],
   [
      "North",
      "Bootle",
      "1807",
      "15"
   ],
   [
      "South",
      "Bournemouth",
      "1299",
      "78"
   ],
   [
      "North",
      "Bradford",
      "1637",
      "10"
   ],
   [
      "South",
      "Brighton",
      "1359",
      "84"
   ],
   [
      "South",
      "Bristol",
      "1392",
      "73"
   ],
   [
      "North",
      "Burnley",
      "1755",
      "12"
   ],
   [
      "South",
      "Cardiff",
      "1519",
      "21"
   ],
   [
      "South",
      "Coventry",
      "1307",
      "78"
   ],
   [
      "South",
      "Croydon",
      "1254",
      "96"
   ],
   [
      "North",
      "Darlington",
      "1491",
      "20"
   ],
   [
      "North",
      "Derby",
      "1555",
      "39"
   ],
   [
      "North",
      "Doncaster",
      "1428",
      "39"
   ],
   [
      "South",
      "East Ham",
      "1318",
      "122"
   ],
   [
      "South",
      "Exeter",
      "1260",
      "21"
   ],
   [
      "North",
      "Gateshead",
      "1723",
      "44"
   ],
   [
      "North",
      "Grimsby",
      "1379",
      "94"
   ],
   [
      "North",
      "Halifax",
      "1742",
      "8"
   ],
   [
      "North",
      "Huddersfield",
      "1574",
      "9"
   ],
   [
      "North",
      "Hull",
      "1569",
      "91"
   ],
   [
      "South",
      "Ipswich",
      "1096",
      "138"
   ],
   [
      "North",
      "Leeds",
      "1591",
      "16"
   ],
   [
      "South",
      "Leicester",
      "1402",
      "37"
   ],
   [
      "North",
      "Liverpool",
      "1772",
      "15"
   ],
   [
      "North",
      "Manchester",
      "1828",
      "8"
   ],
   [
      "North",
      "Middlesbrough",
      "1704",
      "26"
   ],
   [
      "North",
      "Newcastle",
      "1702",
      "44"
   ],
   [
      "South",
      "Newport",
      "1581",
      "14"
   ],
   [
      "South",
      "Northampton",
      "1309",
      "59"
   ],
   [
      "South",
      "Norwich",
      "1259",
      "133"
   ],
   [
      "North",
      "Nottingham",
      "1427",
      "27"
   ],
   [
      "North",
      "Oldham",
      "1724",
      "6"
   ],
   [
      "South",
      "Oxford",
      "1175",
      "107"
   ],
   [
      "South",
      "Plymouth",
      "1486",
      "5"
   ],
   [
      "South",
      "Portsmouth",
      "1456",
      "90"
   ],
   [
      "North",
      "Preston",
      "1696",
      "6"
   ],
   [
      "South",
      "Reading",
      "1236",
      "101"
   ],
   [
      "North",
      "Rochdale",
      "1711",
      "13"
   ],
   [
      "North",
      "Rotherham",
      "1444",
      "14"
   ],
   [
      "North",
      "St Helens",
      "1591",
      "49"
   ],
   [
      "North",
      "Salford",
      "1987",
      "8"
   ],
   [
      "North",
      "Sheffield",
      "1495",
      "14"
   ],
   [
      "South",
      "Southampton",
      "1369",
      "68"
   ],
   [
      "South",
      "Southend",
      "1257",
      "50"
   ],
   [
      "North",
      "Southport",
      "1587",
      "75"
   ],
   [
      "North",
      "South Shields",
      "1713",
      "71"
   ],
   [
      "North",
      "Stockport",
      "1557",
      "13"
   ],
   [
      "North",
      "Stoke",
      "1640",
      "57"
   ],
   [
      "North",
      "Sunderland",
      "1709",
      "71"
   ],
   [
      "South",
      "Swansea",
      "1625",
      "13"
   ],
   [
      "North",
      "Wallasey",
      "1625",
      "20"
   ],
   [
      "South",
      "Walsall",
      "1527",
      "60"
   ],
   [
      "South",
      "West Bromwich",
      "1627",
      "53"
   ],
   [
      "South",
      "West Ham",
      "1486",
      "122"
   ],
   [
      "South",
      "Wolverhampton",
      "1485",
      "81"
   ],
   [
      "North",
      "York",
      "1378",
      "71"
   ]
]
