var rpdr_epInfo ={
   "usage" : "rpdr_ep",
   "format" : "A data frame with the following 22 variables.",
   "title" : "RuPaul's Drag Race Episode Data",
   "parameters" : {
      "lipsyncsong" : "a character vector for the lip-sync artist's song",
      "bottom6" : "a character vector for the sixth queen in the bottom of that episode. Thanks, Season 11.",
      "bottom3" : "a character vector for the third queen in the bottom of that episode. Thanks, Season 11.",
      "bottom7" : "a character vector for the seventh queen in the bottom of that episode. Thanks, Season 14.",
      "minicw2" : "a character vector for a second mini-challenge winner, where applicable",
      "special" : "Is the episode a special (e.g. a reunited or clip show)",
      "bottom4" : "a character vector for the fourth queen in the bottom of that episode. Thanks, Season 11.",
      "bottom5" : "a character vector for the fifth queen in the bottom of that episode. Thanks, Season 11.",
      "minicw1" : "a character vector for a mini-challenge winner",
      "season" : "a character vector for season",
      "bottom2" : "a character vector for queen in the bottom 2 of that episode",
      "eliminated1" : "a character vector for the queen eliminated after the lip-sync",
      "runwaytheme" : "a character vector for runway theme, where applicable/available",
      "nickname" : "Name of the episode",
      "minicw3" : "a character vector for a third mini-challenge winner, where applicable",
      "bottom1" : "a character vector for queen in the bottom 2 of that episode",
      "minicw4" : "a character vector for a fourth mini-challenge winner, where applicable",
      "episode" : "a numeric vector for the episode number",
      "numqueens" : "a numeric vector for number of queens at the start of the episode",
      "finale" : "Is the episode the finale",
      "eliminated2" : "a character vector for the queen eliminated after the lip-sync, if there was a double-sashay that episode.",
      "airdate" : "a date for the episode air date",
      "minic" : "a character vector describing the mini-challenge",
      "lipsyncartist" : "a character vector for the lip-sync artist"
   },
   "description" : "Description\nThese are episode-level data for RuPaul's Drag Race for all available seasons\n(currently through Season 14). Data include all sorts of information."
}

var rpdr_ep = [
   [
      "season",
      "episode",
      "airdate",
      "special",
      "finale",
      "nickname",
      "runwaytheme",
      "numqueens",
      "minic",
      "minicw1",
      "minicw2",
      "minicw3",
      "minicw4",
      "bottom1",
      "bottom2",
      "bottom3",
      "bottom4",
      "bottom5",
      "bottom6",
      "bottom7",
      "lipsyncartist",
      "lipsyncsong",
      "eliminated1",
      "eliminated2"
   ],
   [
      "S01",
      "1",
      "2009-02-02",
      "0",
      "0",
      "Drag on a Dime",
      "",
      "9",
      "",
      "",
      "",
      "",
      "",
      "Akashia",
      "Victoria (Porkchop) Parker",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Supermodel",
      "Victoria (Porkchop) Parker",
      ""
   ],
   [
      "S01",
      "2",
      "2009-02-09",
      "0",
      "0",
      "Girl Group Challenge",
      "",
      "8",
      "Act out emotions",
      "Ongina",
      "Akashia",
      "",
      "",
      "Akashia",
      "Tammie Brown",
      "",
      "",
      "",
      "",
      "",
      "Michelle Williams",
      "We Break the Dawn",
      "Tammie Brown",
      ""
   ],
   [
      "S01",
      "3",
      "2009-02-16",
      "0",
      "0",
      "Queens of All Media",
      "",
      "7",
      "",
      "",
      "",
      "",
      "",
      "Akashia",
      "Shannel",
      "",
      "",
      "",
      "",
      "",
      "Whitney Houston",
      "The Greatest Love of All",
      "Akashia",
      ""
   ],
   [
      "S01",
      "4",
      "2009-02-23",
      "0",
      "0",
      "Mac Viva-Glam Challenge",
      "",
      "6",
      "30 Minutes to do partner's makeup",
      "Jade",
      "",
      "",
      "",
      "Jade",
      "Rebecca Glasscock",
      "",
      "",
      "",
      "",
      "",
      "The Eurythmics",
      "Would I Lie to You?",
      "Jade",
      ""
   ],
   [
      "S01",
      "5",
      "2009-03-02",
      "0",
      "0",
      "Drag School of Charm",
      "",
      "5",
      "Exercise/endurance challenge",
      "Rebecca Glasscock",
      "",
      "",
      "",
      "Bebe Zahara Benet",
      "Ongina",
      "",
      "",
      "",
      "",
      "",
      "Britney Spears",
      "Stronger",
      "Ongina",
      ""
   ],
   [
      "S01",
      "6",
      "2009-03-09",
      "0",
      "0",
      "Absolut Drag Ball",
      "",
      "4",
      "Vogue posing challenge",
      "Nina Flowers",
      "",
      "",
      "",
      "Rebecca Glasscock",
      "Shannel",
      "",
      "",
      "",
      "",
      "",
      "Mary Mary",
      "Praise You",
      "Shannel",
      ""
   ],
   [
      "S01",
      "7",
      "2009-03-16",
      "1",
      "0",
      "Extra Special Edition",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S01",
      "8",
      "2009-03-23",
      "0",
      "1",
      "Grande Finale",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "Rebecca Glasscock",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Cover Girl (Put the Bass in Your Walk)",
      "Rebecca Glasscock",
      ""
   ],
   [
      "S01",
      "9",
      "2009-03-23",
      "1",
      "0",
      "Re-United!",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S02",
      "1",
      "2010-02-01",
      "0",
      "0",
      "Gone with the Windows",
      "Curtain Couture",
      "12",
      "Gone with the Wind photo shoot",
      "Raven",
      "",
      "",
      "",
      "Sahara Davenport",
      "Shangela",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Cover Girl (Put the Bass in Your Walk)",
      "Shangela",
      ""
   ],
   [
      "S02",
      "2",
      "2010-02-08",
      "0",
      "0",
      "Starbootylicious",
      "High-Class Drag",
      "11",
      "Turn RuPaul doll from lady to a tramp",
      "Sahara Davenport",
      "Pandora Boxx",
      "",
      "",
      "Raven",
      "Nicole Paige Brooks",
      "",
      "",
      "",
      "",
      "",
      "En Vogue",
      "My Lovin' (You're Never Gonna Get It)",
      "Nicole Paige Brooks",
      ""
   ],
   [
      "S02",
      "3",
      "2010-02-15",
      "0",
      "0",
      "Country Queens",
      "Denim and Diamond Couture",
      "10",
      " Chicken or what?  eating contest",
      "Mystique Summers Madison",
      "Morgan McMichaels",
      "",
      "",
      "Mystique Summers Madison",
      "Raven",
      "",
      "",
      "",
      "",
      "",
      "Wynonna Judd",
      "I Hear You Knockin'",
      "Mystique Summers Madison",
      ""
   ],
   [
      "S02",
      "4",
      "2010-02-22",
      "0",
      "0",
      "The Snatch Game",
      "Personal Style",
      "9",
      "The Queen is Right",
      "Raven",
      "",
      "",
      "",
      "Sonique",
      "Morgan McMichaels",
      "",
      "",
      "",
      "",
      "",
      "Stacey Q",
      "Two of Hearts",
      "Sonique",
      ""
   ],
   [
      "S02",
      "5",
      "2010-03-01",
      "0",
      "0",
      "Here Comes the Bride",
      "",
      "8",
      "Decorate a box in your drag style",
      "Raven",
      "",
      "",
      "",
      "Morgan McMichaels",
      "Sahara Davenport",
      "",
      "",
      "",
      "",
      "",
      "Martha Wash",
      "Carry On",
      "Morgan McMichaels",
      ""
   ],
   [
      "S02",
      "6",
      "2010-03-08",
      "0",
      "0",
      "Rocker Chicks",
      "",
      "7",
      "Give a wig a glam rock makeover",
      "Pandora Boxx",
      "",
      "",
      "",
      "Jujubee",
      "Sahara Davenport",
      "",
      "",
      "",
      "",
      "",
      "Alannah Myles",
      "Black Velvet",
      "Sahara Davenport",
      ""
   ],
   [
      "S02",
      "7",
      "2010-03-22",
      "0",
      "0",
      "Once Upon a Queen",
      "",
      "6",
      "Reading is Fundamental",
      "Jujubee",
      "",
      "",
      "",
      "Jessica Wild",
      "Tatianna",
      "",
      "",
      "",
      "",
      "",
      "Sister Sledge",
      "He's the Greatest Dancer",
      "Jessica Wild",
      ""
   ],
   [
      "S02",
      "8",
      "2010-03-29",
      "0",
      "0",
      "Golden Gals",
      "",
      "5",
      "Match contestants with their baby pictures",
      "Tatianna",
      "",
      "",
      "",
      "Jujubee",
      "Pandora Boxx",
      "",
      "",
      "",
      "",
      "",
      "Debbie Gibson",
      "Shake Your Love",
      "Pandora Boxx",
      ""
   ],
   [
      "S02",
      "9",
      "2010-04-12",
      "0",
      "0",
      "The Diva Awards",
      "",
      "4",
      "Style/accessorize one of four identical dresses",
      "Tyra Sanchez",
      "",
      "",
      "",
      "Jujubee",
      "Tatianna",
      "",
      "",
      "",
      "",
      "",
      "Aretha Franklin",
      "Something He Can Feel",
      "Tatianna",
      ""
   ],
   [
      "S02",
      "10",
      "2010-04-19",
      "1",
      "0",
      "The Main Event Clip Show",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S02",
      "11",
      "2010-04-26",
      "0",
      "1",
      "Grand Finale",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "Jujubee",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Jealous Of My Boogie (Gomi & RasJek Edit)",
      "Jujubee",
      ""
   ],
   [
      "S02",
      "12",
      "2010-04-26",
      "1",
      "0",
      "Reunion",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S03",
      "1",
      "2011-01-24",
      "1",
      "0",
      "Casting Extravaganza",
      "",
      "13",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S03",
      "2",
      "2011-01-24",
      "0",
      "0",
      "The Queen Who Mopped Xmas",
      "",
      "13",
      "Christmas Card Photo Shoot",
      "Raja",
      "",
      "",
      "",
      "Shangela",
      "Venus D-Lite",
      "",
      "",
      "",
      "",
      "",
      "Vanessa Williams",
      "The Right Stuff",
      "Venus D-Lite",
      ""
   ],
   [
      "S03",
      "3",
      "2011-01-31",
      "0",
      "0",
      "Queens in Space",
      "",
      "12",
      "Psychic Challenge",
      "Mariah",
      "Phoenix",
      "",
      "",
      "Phoenix",
      "Delta Work",
      "",
      "",
      "",
      "",
      "",
      "Lady Gaga",
      "Romance",
      "Phoenix",
      ""
   ],
   [
      "S03",
      "4",
      "2011-02-07",
      "0",
      "0",
      "Totally Leotarded",
      "",
      "11",
      "Making Letoards from Duct Tapes",
      "Carmen Carrera",
      "Manila Luzon",
      "",
      "",
      "India Ferrah",
      "Mimi Imfurst",
      "",
      "",
      "",
      "",
      "",
      "Thelma Houston",
      "Don't Leave Me This Way",
      "Mimi Imfurst",
      ""
   ],
   [
      "S03",
      "5",
      "2011-02-14",
      "0",
      "0",
      "QNN News",
      "",
      "10",
      "Scandalous Red Carpet Photo",
      "Carmen Carrera",
      "Stacy Layne Matthews",
      "",
      "",
      "India Ferrah",
      "Stacy Layne Matthews",
      "",
      "",
      "",
      "",
      "",
      "Klymaxx",
      "Meeting in the Ladies Room",
      "India Ferrah",
      ""
   ],
   [
      "S03",
      "6",
      "2011-02-21",
      "0",
      "0",
      "The Snatch Game",
      "",
      "9",
      "Shit Rupaul Says",
      "Delta Work",
      "",
      "",
      "",
      "Delta Work",
      "Mariah",
      "",
      "",
      "",
      "",
      "",
      "Jody Watley",
      "Looking for a New Love",
      "Mariah",
      ""
   ],
   [
      "S03",
      "7",
      "2011-02-28",
      "0",
      "0",
      "Face, Face, Face of Cakes",
      "",
      "8",
      "Nude photo shoot with Deborah Anderson",
      "Carmen Carrera",
      "",
      "",
      "",
      "Alexis Mateo",
      "Stacy Layne Matthews",
      "",
      "",
      "",
      "",
      "",
      "Amii Stewart",
      "Knock on Wood",
      "Stacy Layne Matthews",
      ""
   ],
   [
      "S03",
      "8",
      "2011-03-07",
      "0",
      "0",
      "Ru Ha Ha",
      "",
      "7",
      "Reading is Fundamental",
      "Shangela",
      "",
      "",
      "",
      "Delta Work",
      "Manila Luzon",
      "",
      "",
      "",
      "",
      "",
      "Donna Summer",
      "MacArthur Park",
      "Delta Work",
      ""
   ],
   [
      "S03",
      "9",
      "2011-03-14",
      "0",
      "0",
      "Life, Liberty & the Pursuit of Style",
      "",
      "6",
      "Decorate bras using rhinestones",
      "Manila Luzon",
      "",
      "",
      "",
      "Yara Sofia",
      "Carmen Carrera",
      "",
      "",
      "",
      "",
      "",
      "Toni Basil",
      "Mickey (Spanish Version)",
      "",
      ""
   ],
   [
      "S03",
      "10",
      "2011-03-21",
      "0",
      "0",
      "RuPaul-a-Palooza",
      "",
      "6",
      "Ru-sical chairs",
      "Manila Luzon",
      "",
      "",
      "",
      "Shangela",
      "Carmen Carrera",
      "",
      "",
      "",
      "",
      "",
      "Cher",
      "Believe",
      "Carmen Carrera",
      ""
   ],
   [
      "S03",
      "11",
      "2011-03-28",
      "0",
      "0",
      "RuPaul's Hair Extravaganza",
      "",
      "5",
      "Beach-themed headpiece",
      "Raja",
      "",
      "",
      "",
      "Alexis Mateo",
      "Shangela",
      "",
      "",
      "",
      "",
      "",
      "Fantasia",
      "Even Angels",
      "Shangela",
      ""
   ],
   [
      "S03",
      "12",
      "2011-04-04",
      "0",
      "0",
      "Jocks in Frocks",
      "",
      "5",
      "Dunk-a-Queen",
      "Alexis Mateo",
      "",
      "",
      "",
      "Raja",
      "Carmen Carrera",
      "",
      "",
      "",
      "",
      "",
      "Paula Abdul",
      "Straight Up",
      "Carmen Carrera",
      ""
   ],
   [
      "S03",
      "13",
      "2011-04-11",
      "0",
      "0",
      "Make Dat Money",
      "",
      "4",
      "Create/market a drag product",
      "Yara Sofia",
      "",
      "",
      "",
      "Alexis Mateo",
      "Yara Sofia",
      "",
      "",
      "",
      "",
      "",
      "Patti LaBelle",
      "I Think About You",
      "Yara Sofia",
      ""
   ],
   [
      "S03",
      "14",
      "2011-04-18",
      "1",
      "0",
      "Superstar Edition",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S03",
      "15",
      "2011-04-25",
      "0",
      "1",
      "Grand Finale",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "Alexis Mateo",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Champion (DJ BunJoe's Olympic Mix)",
      "Alexis Mateo",
      ""
   ],
   [
      "S03",
      "16",
      "2011-05-02",
      "1",
      "0",
      "Reunited!",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S04",
      "1",
      "2012-01-30",
      "0",
      "0",
      "RuPocalypse Now!",
      "",
      "13",
      "Photoshoot with Mike Ruiz",
      "Jiggly Caliente",
      "",
      "",
      "",
      "Alisa Summers",
      "Jiggly Caliente",
      "",
      "",
      "",
      "",
      "",
      "Britney Spears",
      "Toxic",
      "Alisa Summers",
      ""
   ],
   [
      "S04",
      "2",
      "2012-02-06",
      "0",
      "0",
      "WTF!: Wrestling's Trashiest Fighters",
      "Girly Girl Couture",
      "12",
      "Create “badonkadonk” with padding in 30 minutes",
      "Chad Michaels",
      "Willam",
      "Phi Phi O'Hara",
      "",
      "The Princess",
      "Lashauwn Beyond",
      "",
      "",
      "",
      "",
      "",
      "Donna Summer",
      "Bad Girls",
      "Lashauwn Beyond",
      ""
   ],
   [
      "S04",
      "3",
      "2012-02-13",
      "0",
      "0",
      "Glamazons vs Champions",
      "Platinum and Gold",
      "11",
      "Create hats with butterfly-shaped accessories",
      "Phi Phi O'Hara",
      "Kenya Michaels",
      "Jiggly Caliente",
      "",
      "DiDa Ritz",
      "The Princess",
      "",
      "",
      "",
      "",
      "",
      "Natalie Cole",
      "This Will Be (An Everlasting Love)",
      "The Princess",
      ""
   ],
   [
      "S04",
      "4",
      "2012-02-20",
      "0",
      "0",
      "Queens Behind Bars",
      "",
      "10",
      "Paint a partner's face, while handcuffed",
      "Willam",
      "Madame LaQueer",
      "",
      "",
      "Milan",
      "Madame LaQueer",
      "",
      "",
      "",
      "",
      "",
      "Pink",
      "Trouble",
      "Madame LaQueer",
      ""
   ],
   [
      "S04",
      "5",
      "2012-02-27",
      "0",
      "0",
      "Snatch Game",
      "Best Drag",
      "9",
      "Beat the Clock",
      "Phi Phi O'Hara",
      "",
      "",
      "",
      "Kenya Michaels",
      "Milan",
      "",
      "",
      "",
      "",
      "",
      "Madonna",
      "Vogue",
      "Kenya Michaels",
      ""
   ],
   [
      "S04",
      "6",
      "2012-03-05",
      "0",
      "0",
      "Float Your Boat",
      "",
      "8",
      "Wet t-shirt contest",
      "Willam",
      "",
      "",
      "",
      "Milan",
      "Jiggly Caliente",
      "",
      "",
      "",
      "",
      "",
      "Lady Gaga",
      "Born This Way",
      "Milan",
      ""
   ],
   [
      "S04",
      "7",
      "2012-03-12",
      "0",
      "0",
      "Dragazines",
      "",
      "7",
      "Reading is Fundamental",
      "Latrice Royale",
      "",
      "",
      "",
      "Jiggly Caliente",
      "Willam",
      "",
      "",
      "",
      "",
      "",
      "Pam Tillis",
      "Mi Vida Loca",
      "Jiggly Caliente",
      ""
   ],
   [
      "S04",
      "8",
      "2012-03-19",
      "0",
      "0",
      "Frenemies",
      "",
      "6",
      "Polygraph test",
      "",
      "",
      "",
      "",
      "Phi Phi O'Hara",
      "Sharon Needles",
      "",
      "",
      "",
      "",
      "",
      "Martha Wash and RuPaul",
      "It's Raining Men (The Sequel)",
      "Willam",
      ""
   ],
   [
      "S04",
      "9",
      "2012-03-26",
      "0",
      "0",
      "Frock the Vote!",
      "Inaugural Drag",
      "5",
      "Design Absolut Vodka-inspired shoe",
      "Phi Phi O'Hara",
      "",
      "",
      "",
      "Latrice Royale",
      "DiDa Ritz",
      "",
      "",
      "",
      "",
      "",
      "Gladys Knight",
      "I've Got to Use My Imagination",
      "DiDa Ritz",
      ""
   ],
   [
      "S04",
      "10",
      "2012-04-02",
      "0",
      "0",
      "DILFs: Dads I'd Like To Frock",
      "",
      "5",
      "Give a teddy bear a makeover",
      "Kenya Michaels",
      "",
      "",
      "",
      "Latrice Royale",
      "Kenya Michaels",
      "",
      "",
      "",
      "",
      "",
      "Aretha Franklin",
      "(You Make Me Feel Like) A Natural Woman",
      "Kenya Michaels",
      ""
   ],
   [
      "S04",
      "11",
      "2012-04-09",
      "0",
      "0",
      "The Fabulous Bitch Ball",
      "",
      "4",
      "Everybody Loves Puppets",
      "Chad Michaels",
      "",
      "",
      "",
      "Chad Michaels",
      "Latrice Royale",
      "",
      "",
      "",
      "",
      "",
      "Wynonna Judd",
      "No One Else on Earth",
      "Latrice Royale",
      ""
   ],
   [
      "S04",
      "12",
      "2012-04-16",
      "1",
      "0",
      "RuPaul Rewind",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S04",
      "13",
      "2012-04-23",
      "1",
      "0",
      "The Final Three",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S04",
      "14",
      "2012-04-30",
      "0",
      "1",
      "Reunited!",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S05",
      "1",
      "2013-01-28",
      "0",
      "0",
      "RuPaullywood or Bust",
      "",
      "14",
      "Underwater photoshoot",
      "Detox",
      "",
      "",
      "",
      "Serena ChaCha",
      "Penny Tration",
      "",
      "",
      "",
      "",
      "",
      "Miley Cyrus",
      "Party in the U.S.A.",
      "Penny Tration",
      ""
   ],
   [
      "S05",
      "2",
      "2013-02-04",
      "0",
      "0",
      "Lip Synch Eleganza Extravaganza",
      "",
      "13",
      "Lip-synch with only your mouth visible",
      "Serena Cha Cha",
      "Detox",
      "Ivy Winters",
      "",
      "Monica Beverly Hillz",
      "Serena ChaCha",
      "",
      "",
      "",
      "",
      "",
      "Rihanna",
      "Only Girl (In the World)",
      "Serena ChaCha",
      ""
   ],
   [
      "S05",
      "3",
      "2013-02-11",
      "0",
      "0",
      "Draggle Rock",
      "",
      "12",
      "Create mannequin dolls",
      "Alaska",
      "Lineysha Sparx",
      "",
      "",
      "Monica Beverly Hillz",
      "Coco Montrese",
      "",
      "",
      "",
      "",
      "",
      "The Pussycat Dolls",
      "When I Grow Up",
      "Monica Beverly Hillz",
      ""
   ],
   [
      "S05",
      "4",
      "2013-02-18",
      "0",
      "0",
      "Black Swan: Why It Gotta Be Black?",
      "",
      "11",
      "Soul Train dance-off",
      "Jinkx Monsoon",
      "Coco Montrese",
      "",
      "",
      "Honey Mahogany",
      "Vivienne Pinay",
      "",
      "",
      "",
      "",
      "",
      "Britney Spears",
      "Oops!… I Did It Again",
      "Honey Mahogany",
      "Vivienne Pinay"
   ],
   [
      "S05",
      "5",
      "2013-02-25",
      "0",
      "0",
      "Snatch Game",
      "",
      "9",
      "Style a cuddler into a red-carpet look",
      "Alyssa Edwards",
      "Detox",
      "Roxxxy Andrews",
      "",
      "Detox",
      "Lineysha Sparx",
      "",
      "",
      "",
      "",
      "",
      "Cher",
      "Take Me Home",
      "Lineysha Sparx",
      ""
   ],
   [
      "S05",
      "6",
      "2013-03-04",
      "0",
      "0",
      "Can I Get An Amen?",
      "",
      "8",
      "Apply drag makeup in the dark",
      "Detox",
      "",
      "",
      "",
      "Coco Montrese",
      "Jade Jolie",
      "",
      "",
      "",
      "",
      "",
      "The Pointer Sisters",
      "I'm So Excited",
      "Jade Jolie",
      ""
   ],
   [
      "S05",
      "7",
      "2013-03-11",
      "0",
      "0",
      "RuPaul Roast",
      "",
      "7",
      "Reading is Fundamental",
      "Alaska",
      "",
      "",
      "",
      "Alyssa Edwards",
      "Roxxxy Andrews",
      "",
      "",
      "",
      "",
      "",
      "Willow Smith",
      "Whip My Hair",
      "",
      ""
   ],
   [
      "S05",
      "8",
      "2013-03-18",
      "0",
      "0",
      "Scent of a Drag Queen",
      "",
      "7",
      "Whatcha Packin'",
      "Ivy Winters",
      "",
      "",
      "",
      "Alyssa Edwards",
      "Ivy Winters",
      "",
      "",
      "",
      "",
      "",
      "Gwen Guthrie",
      "Ain't Nothin' Goin' on But the Rent",
      "Ivy Winters",
      ""
   ],
   [
      "S05",
      "9",
      "2013-04-01",
      "0",
      "0",
      "Drama Queens",
      "",
      "6",
      "Create fake sob stories, cry in front of RuPaul",
      "Detox",
      "Alyssa Edwards",
      "",
      "",
      "Alyssa Edwards",
      "Coco Montrese",
      "",
      "",
      "",
      "",
      "",
      "Paula Abdul",
      "Cold Hearted",
      "Alyssa Edwards",
      ""
   ],
   [
      "S05",
      "10",
      "2013-04-08",
      "0",
      "0",
      "Super Troopers",
      "",
      "5",
      "Drag booty camp with fitness trainer",
      "Alaska",
      "",
      "",
      "",
      "Coco Montrese",
      "Detox",
      "",
      "",
      "",
      "",
      "",
      "Seduction",
      "(It Takes) Two to Make It Right",
      "Coco Montrese",
      ""
   ],
   [
      "S05",
      "11",
      "2013-04-15",
      "0",
      "0",
      "Sugar Ball",
      "",
      "4",
      "Everybody Loves Puppets",
      "Alaska",
      "",
      "",
      "",
      "Jinkx Monsoon",
      "Detox",
      "",
      "",
      "",
      "",
      "",
      "Yma Sumac",
      "Malambo No. 1",
      "Detox",
      ""
   ],
   [
      "S05",
      "12",
      "2013-04-22",
      "1",
      "0",
      "The Final Three, Hunty",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S05",
      "13",
      "2013-04-29",
      "1",
      "0",
      "Countdown to the Crown",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S05",
      "14",
      "2013-05-06",
      "0",
      "1",
      "Reunited!",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S06",
      "1",
      "2014-02-24",
      "0",
      "0",
      "RuPauls Big Opening",
      "",
      "7",
      "Jumping off a platform photoshoot",
      "Laganja Estranja",
      "",
      "",
      "",
      "Vivacious",
      "Kelly Mantle",
      "",
      "",
      "",
      "",
      "",
      "Madonna",
      "Express Yourself",
      "Kelly Mantle",
      ""
   ],
   [
      "S06",
      "2",
      "2014-03-03",
      "0",
      "0",
      "RuPauls Big Opening Part2",
      "",
      "7",
      "Boudoir pillow fight with the Pit Crew",
      "Trinity K. Bonet",
      "",
      "",
      "",
      "Darienne Lake",
      "Magnolia Crawford",
      "",
      "",
      "",
      "",
      "",
      "Vicki Sue Robinson",
      "Turn the Beat Around",
      "Magnolia Crawford",
      ""
   ],
   [
      "S06",
      "3",
      "2014-03-10",
      "0",
      "0",
      "Scream Queens",
      "",
      "12",
      "Create beach-themed lip sync in pairs",
      "Milk",
      "Adore Delano",
      "",
      "",
      "April Carrión",
      "Vivacious",
      "",
      "",
      "",
      "",
      "",
      "Selena Gomez",
      "Shake It Up",
      "Vivacious",
      ""
   ],
   [
      "S06",
      "4",
      "2014-03-17",
      "0",
      "0",
      "Shade: The Rusical",
      "",
      "11",
      "Female or She-male?",
      "Adore Delano",
      "BenDeLaCreme",
      "",
      "",
      "April Carrión",
      "Trinity K. Bonet",
      "",
      "",
      "",
      "",
      "",
      "Chaka Khan",
      "I'm Every Woman",
      "April Carrión",
      ""
   ],
   [
      "S06",
      "5",
      "2014-03-24",
      "0",
      "0",
      "Snatch Game",
      "",
      "10",
      "",
      "",
      "",
      "",
      "",
      "Gia Gunn",
      "Laganja Estranja",
      "",
      "",
      "",
      "",
      "",
      "Lisa Lisa & Cult Jam",
      "Head to Toe",
      "Gia Gunn",
      ""
   ],
   [
      "S06",
      "6",
      "2014-03-31",
      "0",
      "0",
      "Oh No She Betta Don't",
      "",
      "9",
      "Reading is Fundamental",
      "Darienne Lake",
      "",
      "",
      "",
      "Milk",
      "Trinity K. Bonet",
      "",
      "",
      "",
      "",
      "",
      "Salt-N-Pepa with En Vogue",
      "Whatta Man",
      "Milk",
      ""
   ],
   [
      "S06",
      "7",
      "2014-04-07",
      "0",
      "0",
      "Glamazon by Colorevolution",
      "",
      "8",
      "Design nails and hand modeling fruits",
      "Laganja Estranja",
      "",
      "",
      "",
      "BenDeLaCreme",
      "Darienne Lake",
      "",
      "",
      "",
      "",
      "",
      "Expose",
      "Point of No Return",
      "",
      ""
   ],
   [
      "S06",
      "8",
      "2014-04-07",
      "0",
      "0",
      "Drag Queens of Comedy",
      "",
      "8",
      "Lip-sync to a RuPaul song upside down",
      "Joslyn Fox",
      "",
      "",
      "",
      "Laganja Estranja",
      "Joslyn Fox",
      "",
      "",
      "",
      "",
      "",
      "P!nk",
      "Stupid Girls",
      "Laganja Estranja",
      ""
   ],
   [
      "S06",
      "9",
      "2014-04-14",
      "0",
      "0",
      "Drag Queens of Talk",
      "",
      "7",
      "“Hung Men” hangman challenge",
      "BenDeLaCreme",
      "",
      "",
      "",
      "Adore Delano",
      "Trinity K. Bonet",
      "",
      "",
      "",
      "",
      "",
      "Paul Abdul",
      "Vibeology",
      "Trinity K. Bonet",
      ""
   ],
   [
      "S06",
      "10",
      "2014-04-21",
      "0",
      "0",
      "Drag My Wedding",
      "",
      "6",
      "Abstract painting with bodies for marriage equality",
      "Bianca Del Rio",
      "",
      "",
      "",
      "Joslyn Fox",
      "Adore Delano",
      "",
      "",
      "",
      "",
      "",
      "Aretha Franklin",
      "Think",
      "Joslyn Fox",
      ""
   ],
   [
      "S06",
      "11",
      "2014-04-28",
      "0",
      "0",
      "Glitter Ball",
      "",
      "5",
      "Everybody Loves Puppets",
      "BenDeLaCreme",
      "",
      "",
      "",
      "BenDeLaCreme",
      "Darienne Lake",
      "",
      "",
      "",
      "",
      "",
      "Kelly Clarkson",
      "Stronger (What Doesn't Kill You)",
      "BenDeLaCreme",
      ""
   ],
   [
      "S06",
      "12",
      "2014-05-05",
      "0",
      "0",
      "Sissy That Walk!",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Sissy That Walk",
      "Darienne Lake",
      ""
   ],
   [
      "S06",
      "13",
      "2014-05-12",
      "1",
      "0",
      "Countdown to the Crown",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S06",
      "14",
      "2014-05-19",
      "0",
      "1",
      "The Finale",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S07",
      "1",
      "2015-03-02",
      "0",
      "0",
      "Born Naked",
      "",
      "14",
      "Model 2 looks",
      "",
      "",
      "",
      "",
      "Tempest DuJour",
      "Kandy Ho",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Geronimo",
      "Tempest DuJour",
      ""
   ],
   [
      "S07",
      "2",
      "2015-03-09",
      "0",
      "0",
      "Glamazonian Airways",
      "",
      "13",
      "Keep fish face as Pit Crew blow jets of air into queens faces",
      "Ginger Minj",
      "Trixie Mattel",
      "",
      "",
      "Katya",
      "Sasha Belle",
      "",
      "",
      "",
      "",
      "",
      "Olivia Newton-John",
      "Twist of Fate",
      "Sasha Belle",
      ""
   ],
   [
      "S07",
      "3",
      "2015-03-16",
      "0",
      "0",
      "Shakesqueer",
      "",
      "12",
      "Soul Train dance-off",
      "Max",
      "Kennedy Davenport",
      "",
      "",
      "Jasmine Masters",
      "Kennedy Davenport",
      "",
      "",
      "",
      "",
      "",
      "Kylie Minogue",
      "I Was Gonna Cancel",
      "Jasmine Masters",
      ""
   ],
   [
      "S07",
      "4",
      "2015-03-23",
      "0",
      "0",
      "Spoof! (There It Is)",
      "Green",
      "11",
      "",
      "",
      "",
      "",
      "",
      "Pearl",
      "Trixie Mattel",
      "",
      "",
      "",
      "",
      "",
      "Blondie",
      "Dreaming",
      "Trixie Mattel",
      ""
   ],
   [
      "S07",
      "5",
      "2015-03-30",
      "0",
      "0",
      "The DESPY Awards",
      "",
      "10",
      "Make paper versions of classic red carpet outfits",
      "Katya",
      "Mrs. Kasha Davis",
      "",
      "",
      "Kandy Ho",
      "Mrs. Kasha Davis",
      "",
      "",
      "",
      "",
      "",
      "Teena Marie",
      "Lover Girl",
      "Mrs. Kasha Davis",
      ""
   ],
   [
      "S07",
      "6",
      "2015-04-06",
      "0",
      "0",
      "Ru Hollywood Stories",
      "Death Becomes Her",
      "9",
      "Pull cards out of Pit Crews' underpants to earn points",
      "Ginger Minj",
      "",
      "",
      "",
      "Jaidynn Diore Fierce",
      "Kandy Ho",
      "",
      "",
      "",
      "",
      "",
      "Ariana Grande",
      "Break Free",
      "Kandy Ho",
      ""
   ],
   [
      "S07",
      "7",
      "2015-04-13",
      "0",
      "0",
      "Snatch Game",
      "Leather & Lace",
      "8",
      "",
      "",
      "",
      "",
      "",
      "Jaidynn Diore Fierce",
      "Max",
      "",
      "",
      "",
      "",
      "",
      "Michel'le",
      "No More Lies",
      "Max",
      ""
   ],
   [
      "S07",
      "8",
      "2015-04-20",
      "0",
      "0",
      "Conjoined Queens",
      "",
      "14",
      "Create prison uniform look",
      "Kennedy Davenport",
      "",
      "",
      "",
      "Jaidynn Diore Fierce",
      "Ginger Minj",
      "",
      "",
      "",
      "",
      "",
      "Tiffany",
      "I Think We're Alone Now",
      "Jaidynn Diore Fierce",
      ""
   ],
   [
      "S07",
      "9",
      "2015-04-27",
      "0",
      "0",
      "Divine Inspiration",
      "Ugliest dress ever",
      "7",
      "Reading is Fundamental",
      "Trixie Mattel",
      "",
      "",
      "",
      "Pearl",
      "Miss Fame",
      "",
      "",
      "",
      "",
      "",
      "Demi Lovato ft. Cher Lloyd",
      "Really Don't Care",
      "Miss Fame",
      ""
   ],
   [
      "S07",
      "10",
      "2015-05-04",
      "0",
      "0",
      "Prancing Queens",
      "Half man, half woman",
      "6",
      "Create “Fake Housewives of Drag Race” look using tape",
      "Violet Chachki",
      "",
      "",
      "",
      "Trixie Mattel",
      "Ginger Minj",
      "",
      "",
      "",
      "",
      "",
      "Robin S.",
      "Show Me Love",
      "Trixie Mattel",
      ""
   ],
   [
      "S07",
      "11",
      "2015-05-11",
      "0",
      "0",
      "Hello, Kitty Girls!",
      "",
      "5",
      "Everybody Loves Puppets",
      "Ginger Minj",
      "",
      "",
      "",
      "Kennedy Davenport",
      "Katya",
      "",
      "",
      "",
      "",
      "",
      "Katy Perry",
      "Roar",
      "Katya",
      ""
   ],
   [
      "S07",
      "12",
      "2015-05-18",
      "0",
      "0",
      "And The Rest Is Drag",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Born Naked",
      "Kennedy Davenport",
      ""
   ],
   [
      "S07",
      "13",
      "2015-05-25",
      "1",
      "0",
      "Countdown to the Crown",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S07",
      "14",
      "2015-06-01",
      "0",
      "1",
      "The Grand Finale",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S08",
      "1",
      "2016-03-07",
      "0",
      "0",
      "Keeping it 100!",
      "",
      "12",
      "Photoshoot with past winners",
      "Robbie Turner",
      "",
      "",
      "",
      "Laila McQueen",
      "Naysha Lopez",
      "",
      "",
      "",
      "",
      "",
      "Lady Gaga",
      "Applause",
      "Naysha Lopez",
      ""
   ],
   [
      "S08",
      "2",
      "2016-03-14",
      "0",
      "0",
      "Bitch Perfect",
      "",
      "11",
      "Latin dance-off to RuPaul's “Cha Cha Bitch”",
      "Chi Chi DeVayne",
      "Cynthia Lee Fontaine",
      "",
      "",
      "Dax ExclamationPoint",
      "Laila McQueen",
      "",
      "",
      "",
      "",
      "",
      "Gloria Gaynor",
      "I Will Survive",
      "Dax ExclamationPoint",
      "Laila McQueen"
   ],
   [
      "S08",
      "3",
      "2016-03-21",
      "0",
      "0",
      "RuCo's Empire",
      "Rollergirl Realness",
      "9",
      "Drag up supreme court robes",
      "Naomi Smalls",
      "",
      "",
      "",
      "Robbie Turner",
      "Cynthia Lee Fontaine",
      "",
      "",
      "",
      "",
      "",
      "Faith Evans",
      "Mesmerized",
      "Cynthia Lee Fontaine",
      ""
   ],
   [
      "S08",
      "4",
      "2016-03-28",
      "0",
      "0",
      "New Wave Queens",
      "Neon Realness",
      "9",
      "",
      "",
      "",
      "",
      "",
      "Naysha Lopez",
      "Chi Chi DeVayne",
      "",
      "",
      "",
      "",
      "",
      "Blondie",
      "Call Me",
      "Naysha Lopez",
      ""
   ],
   [
      "S08",
      "5",
      "2016-04-04",
      "0",
      "0",
      "Supermodel Snatch Game",
      "Iconic Madonna Looks",
      "8",
      "",
      "",
      "",
      "",
      "",
      "Acid Betty",
      "Naomi Smalls",
      "",
      "",
      "",
      "",
      "",
      "Madonna",
      "Causing a Commotion",
      "Acid Betty",
      ""
   ],
   [
      "S08",
      "6",
      "2016-04-11",
      "0",
      "0",
      "Wizards of Drag",
      "Wizard of Oz couture",
      "7",
      "Reading is Fundamental",
      "Bob the Drag Queen",
      "",
      "",
      "",
      "Derrick Barry",
      "Robbie Turner",
      "",
      "",
      "",
      "",
      "",
      "Icona Pop",
      "I Love It",
      "Robbie Turner",
      ""
   ],
   [
      "S08",
      "7",
      "2016-04-18",
      "0",
      "0",
      "Shady Politics",
      "",
      "6",
      "True/False guessing game with Pit Crew",
      "Derrick Barry",
      "",
      "",
      "",
      "Chi Chi DeVayne",
      "Thorgy Thor",
      "",
      "",
      "",
      "",
      "",
      "Jennifer Hudson",
      "And I Am Telling You I'm Not Going",
      "Thorgy Thor",
      ""
   ],
   [
      "S08",
      "8",
      "2016-04-25",
      "0",
      "0",
      "RuPaul Look Ball",
      "",
      "5",
      "Everybody Loves Puppets",
      "Chi Chi DeVayne",
      "",
      "",
      "",
      "Bob the Drag Queen",
      "Derrick Barry",
      "",
      "",
      "",
      "",
      "",
      "Sylvester",
      "You Make Me Feel (Mighty Real)",
      "Derrick Barry",
      ""
   ],
   [
      "S08",
      "9",
      "2016-05-02",
      "0",
      "0",
      "The Realness",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "The Realness",
      "Chi Chi DeVayne",
      ""
   ],
   [
      "S08",
      "10",
      "2016-05-16",
      "0",
      "1",
      "The Grand Finale",
      "",
      "3",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S09",
      "1",
      "2017-03-24",
      "0",
      "0",
      "Oh. My. Gaga!",
      "",
      "13",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S09",
      "2",
      "2017-03-31",
      "0",
      "0",
      "She Done Already Done Brought It On",
      "",
      "14",
      "",
      "",
      "",
      "",
      "",
      "Jaymes Mansfield",
      "Kimora Blac",
      "",
      "",
      "",
      "",
      "",
      "The B-52's",
      "Love Shack",
      "Jaymes Mansfield",
      ""
   ],
   [
      "S09",
      "3",
      "2017-04-07",
      "0",
      "0",
      "Draggily Ever After",
      "",
      "13",
      "",
      "",
      "",
      "",
      "",
      "Kimora Blac",
      "Aja",
      "",
      "",
      "",
      "",
      "",
      "Bonnie Taylor",
      "Holding Out For A Hero",
      "Kimora Blac",
      ""
   ],
   [
      "S09",
      "4",
      "2017-04-14",
      "0",
      "0",
      "Good Morning Bitches!",
      "Naughty nighties",
      "12",
      "",
      "",
      "",
      "",
      "",
      "Trinity Taylor",
      "Charlie Hides",
      "",
      "",
      "",
      "",
      "",
      "Britney Spears",
      "I Wanna Go",
      "Charlie Hides",
      ""
   ],
   [
      "S09",
      "5",
      "2017-04-21",
      "0",
      "0",
      "Reality Stars: The Musical",
      "Faux Fur Realness",
      "11",
      "",
      "",
      "",
      "",
      "",
      "Farrah Moan",
      "Cynthia Lee Fontaine",
      "",
      "",
      "",
      "",
      "",
      "Meghan Trainor",
      "Woman Up",
      "Eureka O'Hara",
      ""
   ],
   [
      "S09",
      "6",
      "2017-04-28",
      "0",
      "0",
      "Snatch Game",
      "Night of 1,000 Madonnas: The Shequel",
      "10",
      "",
      "",
      "",
      "",
      "",
      "Cynthia Lee Fontaine",
      "Peppermint",
      "",
      "",
      "",
      "",
      "",
      "Madonna",
      "Music",
      "Cynthia Lee Fontaine",
      ""
   ],
   [
      "S09",
      "7",
      "2017-05-05",
      "0",
      "0",
      "9021-HO",
      "",
      "9",
      "",
      "",
      "",
      "",
      "",
      "Nina Bo'nina Brown",
      "Aja",
      "",
      "",
      "",
      "",
      "",
      "CeCe Peniston",
      "Finally",
      "Aja",
      ""
   ],
   [
      "S09",
      "8",
      "2017-05-12",
      "0",
      "0",
      "RuPaul Roast",
      "",
      "8",
      "Reading is Fundamental",
      "Valentina",
      "",
      "",
      "",
      "Alexis Michelle",
      "Farrah Moan",
      "",
      "",
      "",
      "",
      "",
      "Dolly Parton",
      "Baby I'm Burnin'",
      "Farrah Moan",
      ""
   ],
   [
      "S09",
      "9",
      "2017-05-19",
      "0",
      "0",
      "Your Pilot's On Fire",
      "Club Kid Couture",
      "7",
      "",
      "",
      "",
      "",
      "",
      "Valentina",
      "Nina Bo'nina Brown",
      "",
      "",
      "",
      "",
      "",
      "Ariana Grande",
      "Greedy",
      "Valentina",
      ""
   ],
   [
      "S09",
      "10",
      "2017-05-26",
      "0",
      "0",
      "Makeovers: Crew Better Work",
      "",
      "6",
      "",
      "",
      "",
      "",
      "",
      "Shea Couleé",
      "Nina Bo'nina Brown",
      "",
      "",
      "",
      "",
      "",
      "Demi Lovato",
      "Cool for the Summer",
      "Nina Bo'nina Brown",
      ""
   ],
   [
      "S09",
      "11",
      "2017-06-02",
      "0",
      "0",
      "Gayest Ball Ever",
      "",
      "5",
      "Everybody Loves Puppets",
      "Sasha Velour",
      "",
      "",
      "",
      "Alexis Michelle",
      "Peppermint",
      "",
      "",
      "",
      "",
      "",
      "The Village People",
      "Macho Man",
      "Alexis Michelle",
      ""
   ],
   [
      "S09",
      "12",
      "2017-06-09",
      "1",
      "0",
      "Category Is",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "U Wear It Well",
      "",
      ""
   ],
   [
      "S09",
      "13",
      "2017-06-16",
      "1",
      "0",
      "Reunited",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S09",
      "14",
      "2017-06-23",
      "0",
      "1",
      "Grand Finale",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Trinity Taylor",
      "Shea Couleé",
      "",
      "",
      "",
      "",
      "",
      "Whitney Houston",
      "It's Not Right, but It's Okay",
      "",
      ""
   ],
   [
      "S10",
      "1",
      "2018-03-22",
      "0",
      "0",
      "10s Across The Board",
      "",
      "14",
      "Stand out on runway in a sea of queens",
      "Monét X Change",
      "",
      "",
      "",
      "Kalorie Karbdashian Williams",
      "Vanessa Vanjie Mateo",
      "",
      "",
      "",
      "",
      "",
      "Christina Aguilera",
      "Ain't No Other Man",
      "Vanessa Vanjie Mateo",
      ""
   ],
   [
      "S10",
      "2",
      "2018-03-29",
      "0",
      "0",
      "PharmaRusical",
      "",
      "13",
      "Hay Girl Hay dance competition",
      "Asia O'Hara",
      "The Vixen",
      "",
      "",
      "Kalorie Karbdashian Williams",
      "Eureka O'Hara",
      "",
      "",
      "",
      "",
      "",
      "The Emotions",
      "Best of My Love",
      "Kalorie Karbdashian Williams",
      ""
   ],
   [
      "S10",
      "3",
      "2018-04-05",
      "0",
      "0",
      "Tap That App",
      "",
      "12",
      "Screen tests for Ru's chocolate bar campaign",
      "Blair St. Clair",
      "Monét X Change",
      "Monique Heart",
      "",
      "Yuhua Hamasaki",
      "Mayhem Miller",
      "",
      "",
      "",
      "",
      "",
      "Hole",
      "Celebrity Skin",
      "Yuhua Hamasaki",
      ""
   ],
   [
      "S10",
      "4",
      "2018-04-12",
      "0",
      "0",
      "The Last Ball on Earth",
      "",
      "11",
      "Photobomb celebrity photographs",
      "Aquaria",
      "",
      "",
      "",
      "Monét X Change",
      "Dusty Ray Bottoms",
      "",
      "",
      "",
      "",
      "",
      "Nicki Minaj",
      "Pound the Alarm",
      "Dusty Ray Bottoms",
      ""
   ],
   [
      "S10",
      "5",
      "2018-04-19",
      "0",
      "0",
      "The Bossy Rossy Show",
      "",
      "10",
      "Drag up army duffel bag contents",
      "The Vixen",
      "",
      "",
      "",
      "Monét X Change",
      "Mayhem Miller",
      "",
      "",
      "",
      "",
      "",
      "Shania Twain",
      "Man! I Feel Like a Woman",
      "Mayhem Miller",
      ""
   ],
   [
      "S10",
      "6",
      "2018-04-26",
      "0",
      "0",
      "Drag Con Panel Extravaganza",
      "",
      "9",
      "Identify objects by sitting on them",
      "Asia O'Hara",
      "",
      "",
      "",
      "Blair St. Clair",
      "The Vixen",
      "",
      "",
      "",
      "",
      "",
      "Diana Ross",
      "I'm Coming Out",
      "Blair St. Clair",
      ""
   ],
   [
      "S10",
      "7",
      "2018-05-03",
      "0",
      "0",
      "Snatch Game",
      "",
      "8",
      "Reading is Fundamental",
      "Eureka O'Hara",
      "",
      "",
      "",
      "Monique Heart",
      "The Vixen",
      "",
      "",
      "",
      "",
      "",
      "Carly Rae Jepsen",
      "Cut To The Feeling",
      "Monique Heart",
      ""
   ],
   [
      "S10",
      "8",
      "2018-05-10",
      "0",
      "0",
      "The Unauthorized Rusical",
      "",
      "7",
      "Slap Out Of It",
      "Asia O'Hara",
      "",
      "",
      "",
      "Asia O'Hara",
      "The Vixen",
      "",
      "",
      "",
      "",
      "",
      "Deee-Lite",
      "Groove is in the Heart",
      "The Vixen",
      ""
   ],
   [
      "S10",
      "9",
      "2018-05-17",
      "0",
      "0",
      "Breastworld",
      "Silver Foxy",
      "6",
      "Pants down, bottoms up",
      "Aquaria",
      "",
      "",
      "",
      "Eureka O'Hara",
      "Kameron Michaels",
      "",
      "",
      "",
      "",
      "",
      "Patti Labelle",
      "New Attitude",
      "",
      ""
   ],
   [
      "S10",
      "10",
      "2018-05-24",
      "0",
      "0",
      "Social Media Kings Into Queens",
      "Drag Family Values",
      "6",
      "Create a super macho character and pose for a man's body spray",
      "Eureka O'Hara",
      "",
      "",
      "",
      "Monét X Change",
      "Kameron Michaels",
      "",
      "",
      "",
      "",
      "",
      "Lizzo",
      "Good As Hell",
      "Monét X Change",
      ""
   ],
   [
      "S10",
      "11",
      "2018-06-07",
      "0",
      "0",
      "Evil Twins",
      "",
      "5",
      "Resting Brunch Face",
      "Asia O'Hara",
      "",
      "",
      "",
      "Kameron Michaels",
      "Miz Cracker",
      "",
      "",
      "",
      "",
      "",
      "Vanity 6",
      "Nasty Girl",
      "",
      ""
   ],
   [
      "S10",
      "12",
      "2018-06-14",
      "1",
      "0",
      "American",
      "Final Four Eleganza Extravaganza",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "RuPaul",
      "Call Me Mother",
      "",
      ""
   ],
   [
      "S10",
      "13",
      "2018-06-21",
      "1",
      "0",
      "Queens Reunited",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S10",
      "14",
      "2018-06-28",
      "0",
      "1",
      "Grand Finale",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Jessie J, Ariana Grande, and Nicki Minaj",
      "Bang Bang",
      "",
      ""
   ],
   [
      "S11",
      "1",
      "2019-02-28",
      "0",
      "0",
      "Whatcha Unpackin?",
      "",
      "15",
      "Photo Shoot with Drag Race Legends",
      "Silky Nutmeg Ganache",
      "",
      "",
      "",
      "Kahanna Montrese",
      "Soju",
      "",
      "",
      "",
      "",
      "",
      "Hannah Montana",
      "Best of Both Worlds",
      "Soju",
      ""
   ],
   [
      "S11",
      "2",
      "2019-03-07",
      "0",
      "0",
      "Good God Girl, Get Out",
      "",
      "14",
      "Celebrity Photo Bomb",
      "Brooke Lynn Hytes",
      "Silky Nutmeg Ganache",
      "",
      "",
      "Kahanna Montrese",
      "Mercedes Iman Diamond",
      "",
      "",
      "",
      "",
      "",
      "Britney Spears",
      "Work Bitch",
      "Kahanna Montrese",
      ""
   ],
   [
      "S11",
      "3",
      "2019-03-14",
      "0",
      "0",
      "Diva Worship",
      "",
      "13",
      "Seduce Your Way Into a Seduction Concert",
      "Nina West",
      "Ra’Jah O’Hara",
      "",
      "",
      "A’keria Chanel Davenport",
      "Honey Davenport",
      "Plastique Tiara",
      "Ra’jah O’Hara",
      "Scarlet Envy",
      "Shuga Cain",
      "",
      "Jennifer Lopez",
      "Waiting for Tonight (Hex Rector Remix)",
      "Honey Davenport",
      ""
   ],
   [
      "S11",
      "4",
      "2019-03-21",
      "0",
      "0",
      "Trump: The Rusical",
      "",
      "12",
      "Why You Maddow Tho?",
      "Scarlet Envy",
      "",
      "",
      "",
      "Mercedes Iman Diamond",
      "Ra’Jah O’Hara",
      "",
      "",
      "",
      "",
      "",
      "James Brown",
      "Living In America",
      "Mercedes Iman Diamond",
      ""
   ],
   [
      "S11",
      "5",
      "2019-03-28",
      "0",
      "0",
      "Monster Ball",
      "",
      "11",
      "Transform yourself into living doll",
      "Ra’Jah O’Hara",
      "",
      "",
      "",
      "Shuga Cain",
      "Ariel Versace",
      "",
      "",
      "",
      "",
      "",
      "Whitney Houston",
      "I’m Your Baby Tonight",
      "Ariel Versace",
      ""
   ],
   [
      "S11",
      "6",
      "2019-04-04",
      "0",
      "0",
      "The Draglympics",
      "",
      "10",
      "Galisthenics",
      "A’keria Chanel Davenport",
      "Plastique Tiara",
      "",
      "",
      "Ra’Jah O’Hara",
      "Scarlet Envy",
      "",
      "",
      "",
      "",
      "",
      "Donna Summer",
      "Last Dance",
      "Scarlet Envy",
      ""
   ],
   [
      "S11",
      "7",
      "2019-04-11",
      "0",
      "0",
      "From Farm to Runway",
      "",
      "9",
      "Potato sack race",
      "Nina West",
      "Shuga Cain",
      "",
      "",
      "A’keria Chanel Davenport",
      "Ra’Jah O’Hara",
      "",
      "",
      "",
      "",
      "",
      "Sheena Easton",
      "Strut",
      "Ra’Jah O’Hara",
      ""
   ],
   [
      "S11",
      "8",
      "2019-04-18",
      "0",
      "0",
      "Snatch Game at Sea",
      "",
      "8",
      "Pitch your own self-help book",
      "Silky Nutmeg Ganache",
      "",
      "",
      "",
      "Brooke Lynn Hytes",
      "Yvie Oddly",
      "",
      "",
      "",
      "",
      "",
      "Demi Lovato",
      "Sorry Not Sorry",
      "",
      ""
   ],
   [
      "S11",
      "9",
      "2019-04-25",
      "0",
      "0",
      "L.A.D.P.!",
      "",
      "8",
      "Reading is Fundamental",
      "Brooke Lynn Hytes",
      "",
      "",
      "",
      "Plastique Tiara",
      "Vanessa Vanjie Mateo",
      "",
      "",
      "",
      "",
      "",
      "Fantasia Barrino",
      "Hood Boy",
      "Plastique Tiara",
      ""
   ],
   [
      "S11",
      "10",
      "2019-05-02",
      "0",
      "0",
      "Dragracadabra",
      "",
      "7",
      "Balls to the Wall",
      "Vanessa Vanjie Mateo",
      "",
      "",
      "",
      "Shuga Cain",
      "Vanessa Vanjie Mateo",
      "",
      "",
      "",
      "",
      "",
      "Mary J. Blige",
      "No More Drama",
      "Shuga Cain",
      ""
   ],
   [
      "S11",
      "11",
      "2019-05-09",
      "0",
      "0",
      "Bring Back My Queens!",
      "",
      "6",
      "Slap Out Of It",
      "Brooke Lynn Hytes",
      "",
      "",
      "",
      "Nina West",
      "Silky Nutmeg Ganache",
      "",
      "",
      "",
      "",
      "",
      "TLC",
      "No Scrubs",
      "Nina West",
      ""
   ],
   [
      "S11",
      "12",
      "2019-05-16",
      "0",
      "0",
      "Queens Everywhere",
      "",
      "5",
      "",
      "",
      "",
      "",
      "",
      "Brooke Lynn Hytes",
      "Vanessa Vanjie Mateo",
      "",
      "",
      "",
      "",
      "",
      "Aretha Franklin",
      "Pride: A Deeper Love",
      "Vanessa Vanjie Mateo",
      ""
   ],
   [
      "S11",
      "13",
      "2019-05-23",
      "1",
      "0",
      "Reunited",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S11",
      "14",
      "2019-05-30",
      "0",
      "1",
      "Grand Finale",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lady Gaga",
      "Edge of Glory",
      "",
      ""
   ],
   [
      "S12",
      "1",
      "2020-02-28",
      "0",
      "0",
      "I’m That Bitch",
      "Sparkle",
      "7",
      "Model 2 looks",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Nicki Minaj",
      "Starships",
      "",
      ""
   ],
   [
      "S12",
      "2",
      "2020-03-06",
      "0",
      "0",
      "You Don’t Know Me",
      "Tulle",
      "6",
      "Model 2 looks",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Robyn",
      "Call Your Girlfriend",
      "",
      ""
   ],
   [
      "S12",
      "3",
      "2020-03-13",
      "0",
      "0",
      "World’s Worst",
      "Buttons and Bows",
      "13",
      "Queer-Peer Assessment",
      "",
      "",
      "",
      "",
      "Dahlia Sin",
      "Nicky Doll",
      "",
      "",
      "",
      "",
      "",
      "Ariana Grande ft. Iggy Azalea",
      "Problem",
      "Dahlia Sin",
      ""
   ],
   [
      "S12",
      "4",
      "2020-03-20",
      "0",
      "0",
      "The Ball Ball",
      "Lady Baller, Basketball Wife Realess, and Balls to the Wall Eleganza",
      "12",
      "“The Beehive Jive”",
      "Gigi Goode",
      "",
      "",
      "",
      "Brita",
      "Rock M. Sakura",
      "",
      "",
      "",
      "",
      "",
      "Rihanna",
      "S&M",
      "Rock M. Sakura",
      ""
   ],
   [
      "S12",
      "5",
      "2020-03-27",
      "0",
      "0",
      "Gay’s Anataomy",
      "",
      "11",
      "Pink Pill or Silver Pill",
      "Gigi Goode",
      "Nicky Doll",
      "",
      "",
      "Nicky Doll",
      "Heidi N Closet",
      "",
      "",
      "",
      "",
      "",
      "Kim Petras",
      "Heart to Break",
      "Nicky Doll",
      ""
   ],
   [
      "S12",
      "6",
      "2020-04-03",
      "0",
      "0",
      "Snatch Game",
      "Frozen Eleganza",
      "10",
      "",
      "",
      "",
      "",
      "",
      "Aiden Zhane",
      "Brita",
      "",
      "",
      "",
      "",
      "",
      "Cassie Levy",
      "Let it Go",
      "Aiden Zhane",
      ""
   ],
   [
      "S12",
      "7",
      "2020-04-10",
      "0",
      "0",
      "Madonna: The Unauthorized Rusical",
      "Night of a 1000 Michelle Visages",
      "9",
      "",
      "",
      "",
      "",
      "",
      "Brita",
      "Heidi N Closet",
      "",
      "",
      "",
      "",
      "",
      "Madonna",
      "Burning Up",
      "Brita",
      ""
   ],
   [
      "S12",
      "8",
      "2020-04-17",
      "0",
      "0",
      "Droop",
      "Black Wedding",
      "8",
      "",
      "Jackie Cox",
      "Gigi Goode",
      "",
      "",
      "Jan",
      "Widow Von’Du",
      "",
      "",
      "",
      "",
      "",
      "Chaka Khan",
      "This Is My Night",
      "Jan",
      ""
   ],
   [
      "S12",
      "9",
      "2020-04-24",
      "0",
      "0",
      "Choices 2020",
      "Stars and Stripes Forever",
      "7",
      "",
      "Jackie Cox",
      "",
      "",
      "",
      "Jackie Cox",
      "Widow Von’Du",
      "",
      "",
      "",
      "",
      "",
      "Katy Perry",
      "Firework",
      "Widow Von’Du",
      ""
   ],
   [
      "S12",
      "10",
      "2020-05-01",
      "0",
      "0",
      "Superfan Makeover",
      "Drag Family Resemblance",
      "6",
      "",
      "",
      "",
      "",
      "",
      "Heidi N Closet",
      "Jackie Cox",
      "",
      "",
      "",
      "",
      "",
      "Alex Newell and DJ Cassidy ft. Nile Rodgers",
      "Kill the Lights",
      "",
      ""
   ],
   [
      "S12",
      "11",
      "2020-05-08",
      "0",
      "0",
      "One-Queen Show",
      "The Color Purple",
      "6",
      "",
      "Jackie Cox",
      "",
      "",
      "",
      "Heidi N Closet",
      "Jaida Essence Hall",
      "",
      "",
      "",
      "",
      "",
      "Prince",
      "1999",
      "Heidi N Closet",
      ""
   ],
   [
      "S12",
      "12",
      "2020-05-15",
      "0",
      "0",
      "Viva Drag Vegas",
      "Eleganza Extravaganza",
      "5",
      "",
      "Gigi Goode",
      "",
      "",
      "",
      "Crystal Methyd",
      "Jackie Cox",
      "",
      "",
      "",
      "",
      "",
      "Jennifer Lopez ft. Pitbull",
      "On The Floor",
      "Jackie Cox",
      ""
   ],
   [
      "S12",
      "13",
      "2020-05-22",
      "1",
      "0",
      "Alone Together",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S12",
      "14",
      "2020-05-29",
      "0",
      "1",
      "Grand Finale",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Destiny’s Child",
      "Survivor",
      "",
      ""
   ],
   [
      "S13",
      "1",
      "2021-01-01",
      "1",
      "0",
      "The Pork Chop",
      "",
      "13",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S13",
      "2",
      "2021-01-08",
      "1",
      "0",
      "Condragulations",
      "Lamé you Stay",
      "13",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Dua Lipa",
      "Break My Heart",
      "",
      ""
   ],
   [
      "S13",
      "3",
      "2021-01-15",
      "1",
      "0",
      "Phenomenon",
      "We’re Here, We’re Sheer, Get Used To It",
      "13",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Britney Spears",
      "If U Seek Amy",
      "",
      ""
   ],
   [
      "S13",
      "4",
      "2021-01-22",
      "0",
      "0",
      "RuPaulmark Channel",
      "Trains for Days",
      "13",
      "",
      "",
      "",
      "",
      "",
      "Denali",
      "Kahmora Hall",
      "",
      "",
      "",
      "",
      "",
      "Crystal Waters",
      "100% Pure Love",
      "Kahmora Hall",
      ""
   ],
   [
      "S13",
      "5",
      "2021-01-29",
      "0",
      "0",
      "The Bag Ball",
      "Mixed Bag, Money Bags, Bag Ball Extravaganza",
      "12",
      "Baby Got Back: Who Is the Most Misbehaved Baby?",
      "LaLa Ri",
      "",
      "",
      "",
      "Joey Jay",
      "LaLa Ri",
      "",
      "",
      "",
      "",
      "",
      "Iggy Azalea feat. Charli XCX",
      "Fancy",
      "Joey Jay",
      ""
   ],
   [
      "S13",
      "6",
      "2021-02-05",
      "0",
      "0",
      "Disco-Mentary",
      "Little Black Dress",
      "11",
      "Create eye-popping dresses from wallpaper",
      "Elliott with 2 Ts",
      "Tamisha Iman",
      "",
      "",
      "Kandy Muse",
      "Tamisha Iman",
      "",
      "",
      "",
      "",
      "",
      "Blu Cantrell",
      "Hit ‘Em Up Style (Oops!)",
      "Tamisha Iman",
      ""
   ],
   [
      "S13",
      "7",
      "2021-02-12",
      "0",
      "0",
      "Bossy Bossy Ruboot",
      "Bead It",
      "10",
      "Reading is Fundamental",
      "Gottmik",
      "",
      "",
      "",
      "Elliott with 2 Ts",
      "LaLa Ri",
      "",
      "",
      "",
      "",
      "",
      "Kelly Clarkson",
      "Whole Lotta Woman",
      "LaLa Ri",
      ""
   ],
   [
      "S13",
      "8",
      "2021-02-19",
      "0",
      "0",
      "Social Media: The Unverified Rusical",
      "Yellow, Gorgeous!",
      "9",
      "",
      "",
      "",
      "",
      "",
      "Kandy Muse",
      "Symone",
      "",
      "",
      "",
      "",
      "",
      "Fifth Harmony",
      "BO$$",
      "",
      ""
   ],
   [
      "S13",
      "9",
      "2021-03-05",
      "0",
      "0",
      "The Snatch Game",
      "Fascinating Fascinators",
      "9",
      "Quick drag",
      "Tina Burner",
      "",
      "",
      "",
      "Utica Queen",
      "Elliott with 2 Ts",
      "",
      "",
      "",
      "",
      "",
      "Company B",
      "Fascinated",
      "Elliott with 2 Ts",
      ""
   ],
   [
      "S13",
      "10",
      "2021-03-12",
      "0",
      "0",
      "Freaky Friday Queens",
      "Drag Dopplegangers",
      "8",
      "",
      "",
      "",
      "",
      "",
      "Denali",
      "Olivia Lux",
      "",
      "",
      "",
      "",
      "",
      "Mary Mary",
      "Shackles (Praise You)",
      "Denali",
      ""
   ],
   [
      "S13",
      "11",
      "2021-03-19",
      "0",
      "0",
      "Pop! Goes the Queens",
      "BEAST Couture",
      "7",
      "Are You Smarter Than The Pit Crew?",
      "Kandy Muse",
      "",
      "",
      "",
      "Tina Burner",
      "Utica Queen",
      "",
      "",
      "",
      "",
      "",
      "Black Eyed Peas",
      "My Humps",
      "Tina Burner",
      ""
   ],
   [
      "S13",
      "12",
      "2021-03-26",
      "0",
      "0",
      "Nice Girls Roast",
      "",
      "6",
      "Comedy makeup",
      "Kandy Muse",
      "Rosé",
      "",
      "",
      "Symone",
      "Utica Queen",
      "",
      "",
      "",
      "",
      "",
      "Ariana Grande",
      "No Tears Left To Cry",
      "Utica Queen",
      ""
   ],
   [
      "S13",
      "13",
      "2021-04-02",
      "0",
      "0",
      "Henny, I Shrunk The Drag Queens!",
      "Haute Pockets",
      "5",
      "",
      "",
      "",
      "",
      "",
      "Kandy Muse",
      "Olivia Lux",
      "",
      "",
      "",
      "",
      "",
      "Cher",
      "Strong Enough",
      "Olivia Lux",
      ""
   ],
   [
      "S13",
      "14",
      "2021-04-09",
      "0",
      "0",
      "Gettin’ Lucky",
      "Drag Excellence",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S13",
      "15",
      "2021-04-16",
      "1",
      "0",
      "Reunited",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S13",
      "16",
      "2021-04-23",
      "0",
      "1",
      "Grand Finale",
      "",
      "4",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S14",
      "1",
      "2022-01-07",
      "0",
      "0",
      "Big Opening No. 1",
      "Signature Show-Stopping Drag",
      "7",
      "Pose for a photo while spinned around on the Lipsync for the Crown wheel",
      "Kerri Colby",
      "",
      "",
      "",
      "June Jambalaya",
      "Orion Story",
      "",
      "",
      "",
      "",
      "",
      "Lizzo",
      "Water Me",
      "Orion Story",
      ""
   ],
   [
      "S14",
      "2",
      "2022-01-14",
      "0",
      "0",
      "Big Opening No. 2",
      "Sickening Signature Drag",
      "7",
      "Pose for a photo in a giant bowl of Tic-Tacs",
      "Angeria Paris VanMicheals",
      "",
      "",
      "",
      "Daya Betty",
      "DeJa Skye",
      "",
      "",
      "",
      "",
      "",
      "Alicia Keys",
      "Fallin",
      "Daya Betty",
      ""
   ],
   [
      "S14",
      "3",
      "2022-01-21",
      "0",
      "0",
      "A Pair of Balls",
      "Group 1) Hide & Chic; Group 2) Red, White, and Blue Ball",
      "14",
      "",
      "",
      "",
      "",
      "",
      "June Jambalaya",
      "Maddy Morphosis",
      "",
      "",
      "",
      "",
      "",
      "Kylie Minogue",
      "I Love It",
      "June Jambalaya",
      ""
   ],
   [
      "S14",
      "4",
      "2022-01-28",
      "0",
      "0",
      "She's A Super Tease",
      "Night of 1000 Jlo’s",
      "13",
      "",
      "",
      "",
      "",
      "",
      "Alyssa Hunter",
      "Kerri Colby",
      "",
      "",
      "",
      "",
      "",
      "Jennifer Lopez",
      "Play",
      "Alyssa Hunter",
      ""
   ],
   [
      "S14",
      "5",
      "2022-02-04",
      "0",
      "0",
      "Save A Queen",
      "Spring Has Sprung",
      "12",
      "",
      "",
      "",
      "",
      "",
      "Jorgeous",
      "Orion Story",
      "",
      "",
      "",
      "",
      "",
      "Ava Max",
      "My Head & My Heart",
      "Orion Story",
      ""
   ],
   [
      "S14",
      "6",
      "2022-02-11",
      "0",
      "0",
      "Glamazon Prime",
      "Glamazon Primetime",
      "10",
      "",
      "",
      "",
      "",
      "",
      "Jasmine Kennedie",
      "Maddy Morphosis",
      "",
      "",
      "",
      "",
      "",
      "Beyonce",
      "Suga Mama",
      "Maddy Morphosis",
      ""
   ],
   [
      "S14",
      "7",
      "2022-02-18",
      "0",
      "0",
      "The Daytona Wind",
      "Chaps on the Runway",
      "9",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S14",
      "8",
      "2022-02-25",
      "0",
      "0",
      "60s Girl Groups",
      "Heart On",
      "9",
      "Reading is Fundamental",
      "Bosco",
      "",
      "",
      "",
      "Jasmine Kennedie",
      "Kerri Colby",
      "",
      "",
      "",
      "",
      "",
      "Toni Braxton",
      "Un-Break My Heart (Sou-Hex Anthem Vocal)",
      "Kerri Colby",
      ""
   ],
   [
      "S14",
      "9",
      "2022-03-04",
      "0",
      "0",
      "Menzeses",
      "Shoulder Pads",
      "8",
      "Photobomb celebrity photographs",
      "Willow Pill",
      "",
      "",
      "",
      "Jasmine Kennedie",
      "Jorgeous",
      "",
      "",
      "",
      "",
      "",
      "Etta James",
      "Something’s Got A Hold On Me",
      "",
      ""
   ],
   [
      "S14",
      "10",
      "2022-03-11",
      "0",
      "0",
      "Snatch Game",
      "Holy Couture",
      "8",
      "Make a look out of bubble wrap",
      "Bosco",
      "",
      "",
      "",
      "Angeria Paris VanMichaels",
      "Bosco",
      "Daya Betty",
      "Jasmine Kennedie",
      "Jorgeous",
      "Lady Camden",
      "Willow Pill",
      "",
      "",
      "",
      ""
   ],
   [
      "S14",
      "11",
      "2022-03-18",
      "1",
      "0",
      "An Extra Special Episode",
      "",
      "8",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S14",
      "12",
      "2022-03-25",
      "0",
      "0",
      "Moulin Ru: The Rusical",
      "Mirror, Mirror",
      "7",
      "",
      "",
      "",
      "",
      "",
      "Bosco",
      "Jorgeous",
      "",
      "",
      "",
      "",
      "",
      "Whitney Houston",
      "Heartbreak Hotel (Hex Rector Remix)",
      "",
      ""
   ],
   [
      "S14",
      "13",
      "2022-04-01",
      "0",
      "0",
      "The Ross Mathews Roast",
      "Tutu Much",
      "7",
      "Paint a mural of RuPaul and Dolly Parton",
      "Bosco",
      "Daya Betty",
      "Lady Camden",
      "Willow Pill",
      "Daya Betty",
      "DeJa Skye",
      "Jorgeous",
      "",
      "",
      "",
      "",
      "Olivia Rodrigo",
      "good 4 u",
      "DeJa Skye",
      "Jorgeous"
   ],
   [
      "S14",
      "14",
      "2022-04-08",
      "0",
      "0",
      "Catwalk",
      "You’re a Winner, Baby",
      "5",
      "",
      "",
      "",
      "",
      "",
      "Angeria Paris VanMichaels",
      "Willow Pill",
      "",
      "",
      "",
      "",
      "",
      "Lady Gaga ft. Beyonce",
      "Telephone",
      "",
      ""
   ],
   [
      "S14",
      "15",
      "2022-04-15",
      "1",
      "0",
      "Reunited!",
      "",
      "5",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ],
   [
      "S14",
      "16",
      "2022-04-22",
      "0",
      "1",
      "Grand Finale",
      "",
      "5",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
   ]
]
