var BrokenMarriageInfo ={
   "usage" : "data(\"BrokenMarriage\")",
   "description" : "Description\nData from the Danish Welfare Study about broken marriages or permanent\nrelationships depending on gender and social rank.",
   "title" : "Broken Marriage Data",
   "format" : "A data frame with 20 observations and 4 variables.",
   "reference" : "E. B. Andersen (1991),\nThe Statistical Analysis of Categorical Data, page 177.",
   "parameters" : {
      "Freq" : "frequency.",
      "broken" : "factor indicating whether the marriage or permanent\nrelationship was broken (yes, no).",
      "rank" : "factor indicating social rank (I, II, III, IV, V).",
      "gender" : "factor indicating gender (male, female)."
   }
}

var BrokenMarriage = [
   [
      "Freq",
      "gender",
      "rank",
      "broken"
   ],
   [
      "14",
      "male",
      "I",
      "yes"
   ],
   [
      "102",
      "male",
      "I",
      "no"
   ],
   [
      "39",
      "male",
      "II",
      "yes"
   ],
   [
      "151",
      "male",
      "II",
      "no"
   ],
   [
      "42",
      "male",
      "III",
      "yes"
   ],
   [
      "292",
      "male",
      "III",
      "no"
   ],
   [
      "79",
      "male",
      "IV",
      "yes"
   ],
   [
      "293",
      "male",
      "IV",
      "no"
   ],
   [
      "66",
      "male",
      "V",
      "yes"
   ],
   [
      "261",
      "male",
      "V",
      "no"
   ],
   [
      "12",
      "female",
      "I",
      "yes"
   ],
   [
      "25",
      "female",
      "I",
      "no"
   ],
   [
      "23",
      "female",
      "II",
      "yes"
   ],
   [
      "79",
      "female",
      "II",
      "no"
   ],
   [
      "37",
      "female",
      "III",
      "yes"
   ],
   [
      "151",
      "female",
      "III",
      "no"
   ],
   [
      "102",
      "female",
      "IV",
      "yes"
   ],
   [
      "557",
      "female",
      "IV",
      "no"
   ],
   [
      "58",
      "female",
      "V",
      "yes"
   ],
   [
      "321",
      "female",
      "V",
      "no"
   ]
]
