var chickweed0Info ={
   "format" : "A data frame with 35 observations on the following 3 variables.",
   "usage" : "data(chickweed)",
   "reference" : "The germination tests of chickweed seeds from chlorsulfuron resistant and sensitive biotypes in central Zealand were \ndone in petri dishes (diameter: 9.0cm) in a dark growth cabinet at a temperature of 5 degrees Celsius. The seeds were incubated for \n24 hours in a 0.3% solution of potassium nitrate in order to imbibe seeds prior to the test. A total of 200 seeds were placed on filter plate. \nAfter initialization of the tests, the number of germinated seeds was recorded and removed at 34 consecutive inspection times. \nDefinition of a germinated seed was the breakthrough of the seed testa by the radicle.",
   "description" : "Description\nGermination data from tests of chickweed seeds from chlorsulfuron resistant and sensitive biotypes",
   "title" : "Germination of common chickweed (Stellaria media)",
   "parameters" : {
      "start" : "a numeric vector of left endpoints of the monitoring intervals",
      "time" : "a numeric vector of the non-zero left endpoints of the monitoring intervals (often used for recording in practice)",
      "end" : "a numeric vector of right endpoints of the monitoring intervals",
      "count" : "a numeric vector of the number of seeds germinated in the interval between start and end"
   }
}

var chickweed0 = [
   [
      "time",
      "count"
   ],
   [
      "12",
      "0"
   ],
   [
      "22",
      "0"
   ],
   [
      "30",
      "0"
   ],
   [
      "36",
      "0"
   ],
   [
      "46",
      "0"
   ],
   [
      "54",
      "0"
   ],
   [
      "60",
      "0"
   ],
   [
      "71",
      "0"
   ],
   [
      "78",
      "0"
   ],
   [
      "84",
      "0"
   ],
   [
      "95",
      "0"
   ],
   [
      "103",
      "0"
   ],
   [
      "109",
      "0"
   ],
   [
      "120",
      "0"
   ],
   [
      "129",
      "0"
   ],
   [
      "133",
      "0"
   ],
   [
      "143",
      "2"
   ],
   [
      "151",
      "2"
   ],
   [
      "158.5",
      "2"
   ],
   [
      "169.5",
      "2"
   ],
   [
      "176.5",
      "2"
   ],
   [
      "182.5",
      "5"
   ],
   [
      "192.5",
      "15"
   ],
   [
      "200.5",
      "26"
   ],
   [
      "206.5",
      "32"
   ],
   [
      "216.5",
      "37"
   ],
   [
      "224.5",
      "39"
   ],
   [
      "230.5",
      "39"
   ],
   [
      "241.5",
      "39"
   ],
   [
      "249.5",
      "39"
   ],
   [
      "254.5",
      "39"
   ],
   [
      "266.5",
      "39"
   ],
   [
      "276.5",
      "40"
   ],
   [
      "281.5",
      "40"
   ]
]
