var earthwormsInfo ={
   "format" : "A data frame with 35 observations on the following 3 variables.",
   "reference" : "At dose 0 around half of the earthworms is expected be in each of the two containers. Thus it is not \nappropriate to fit an ordinary logistic regression with log(dose) as explanatory variable to these data\nas it implies an upper limit of 1 at dose 0 and in fact this model does not utilise the observations\nat dose 0 (see the example section below).",
   "title" : "Earthworm toxicity test",
   "parameters" : {
      "dose" : "a numeric vector of dose values",
      "total" : "a numeric vector containing total number of earthworms put in the containers",
      "number" : "a numeric vector containing counts of remaining earthworms in the container"
   },
   "usage" : "data(earthworms)",
   "description" : "Description\nThe dataset was obtained from a toxicity test using earthworms, and it contains the number of earthworms \nremaining in a container that was contaminated with a toxic substance (not disclosed) at various doses; so the number of earthworms not migrating to the neighbouring uncontaminated container."
}

var earthworms = [
   [
      "dose",
      "number",
      "total"
   ],
   [
      "0",
      "3",
      "5"
   ],
   [
      "0",
      "3",
      "5"
   ],
   [
      "0",
      "3",
      "4"
   ],
   [
      "0",
      "5",
      "8"
   ],
   [
      "0",
      "4",
      "8"
   ],
   [
      "0.19",
      "4",
      "11"
   ],
   [
      "0.19",
      "4",
      "9"
   ],
   [
      "0.19",
      "2",
      "8"
   ],
   [
      "0.19",
      "3",
      "8"
   ],
   [
      "0.19",
      "2",
      "4"
   ],
   [
      "0.38",
      "2",
      "9"
   ],
   [
      "0.38",
      "0",
      "4"
   ],
   [
      "0.38",
      "6",
      "11"
   ],
   [
      "0.38",
      "4",
      "11"
   ],
   [
      "0.38",
      "4",
      "15"
   ],
   [
      "0.76",
      "0",
      "11"
   ],
   [
      "0.76",
      "1",
      "6"
   ],
   [
      "0.76",
      "1",
      "8"
   ],
   [
      "0.76",
      "0",
      "9"
   ],
   [
      "0.76",
      "0",
      "8"
   ],
   [
      "1.53",
      "0",
      "6"
   ],
   [
      "1.53",
      "1",
      "10"
   ],
   [
      "1.53",
      "0",
      "10"
   ],
   [
      "1.53",
      "0",
      "10"
   ],
   [
      "1.53",
      "0",
      "8"
   ],
   [
      "3.05",
      "0",
      "5"
   ],
   [
      "3.05",
      "0",
      "9"
   ],
   [
      "3.05",
      "0",
      "7"
   ],
   [
      "3.05",
      "0",
      "8"
   ],
   [
      "3.05",
      "1",
      "8"
   ],
   [
      "6.11",
      "0",
      "3"
   ],
   [
      "6.11",
      "0",
      "7"
   ],
   [
      "6.11",
      "0",
      "11"
   ],
   [
      "6.11",
      "0",
      "10"
   ],
   [
      "6.11",
      "1",
      "7"
   ]
]
