var table2Info ={
   "usage" : "table1\n\ntable2\n\ntable3\n\ntable4a\n\ntable4b\n\ntable5",
   "format" : "table1, table2, table3, table4a, table4b,\nand table5 all display the number of TB cases documented by the World\nHealth Organization in Afghanistan, Brazil, and China between 1999 and 2000.\nThe data contains values associated with four variables (country, year,\ncases, and population), but each table organizes the values in a different\nlayout.",
   "title" : "Example tabular representations",
   "description" : "Description\nData sets that demonstrate multiple ways to layout the same tabular data."
}

var table2 = [
   [
      "country",
      "year",
      "type",
      "count"
   ],
   [
      "Afghanistan",
      "1999",
      "cases",
      "745"
   ],
   [
      "Afghanistan",
      "1999",
      "population",
      "19987071"
   ],
   [
      "Afghanistan",
      "2000",
      "cases",
      "2666"
   ],
   [
      "Afghanistan",
      "2000",
      "population",
      "20595360"
   ],
   [
      "Brazil",
      "1999",
      "cases",
      "37737"
   ],
   [
      "Brazil",
      "1999",
      "population",
      "172006362"
   ],
   [
      "Brazil",
      "2000",
      "cases",
      "80488"
   ],
   [
      "Brazil",
      "2000",
      "population",
      "174504898"
   ],
   [
      "China",
      "1999",
      "cases",
      "212258"
   ],
   [
      "China",
      "1999",
      "population",
      "1272915272"
   ],
   [
      "China",
      "2000",
      "cases",
      "213766"
   ],
   [
      "China",
      "2000",
      "population",
      "1280428583"
   ]
]
