var orob2Info ={
   "parameters" : {
      "n" : "a numeric vector: the number of seeds exposed to germination.",
      "seed" : "a factor with 2 levels: O73 and O75.",
      "y" : "a numeric vector: the number of seeds which actually germinated.",
      "root" : "a factor with 2 levels BEAN and CUCUMBER."
   },
   "description" : "Description\n&ldquo;A 2 x 2 factorial experiment comparing 2 types of seed and 2 root extracts. There are 5 or 6 replicates in each \nof the 4 treatment groups, and each replicate comprises a number of seeds varying between 4 and 81. The response \nvariable is the proportion of seeds germinating in each replicate.&rdquo; (Crowder, 1978, Table 3).",
   "usage" : "data(orob2)",
   "format" : "A data frame with 21 observations on the following 4 variables.",
   "title" : "Germination Data"
}

var orob2 = [
   [
      "seed",
      "root",
      "n",
      "y"
   ],
   [
      "O75",
      "BEAN",
      "39",
      "10"
   ],
   [
      "O75",
      "BEAN",
      "62",
      "23"
   ],
   [
      "O75",
      "BEAN",
      "81",
      "23"
   ],
   [
      "O75",
      "BEAN",
      "51",
      "26"
   ],
   [
      "O75",
      "BEAN",
      "39",
      "17"
   ],
   [
      "O75",
      "CUCUMBER",
      "6",
      "5"
   ],
   [
      "O75",
      "CUCUMBER",
      "74",
      "53"
   ],
   [
      "O75",
      "CUCUMBER",
      "72",
      "55"
   ],
   [
      "O75",
      "CUCUMBER",
      "51",
      "32"
   ],
   [
      "O75",
      "CUCUMBER",
      "79",
      "46"
   ],
   [
      "O75",
      "CUCUMBER",
      "13",
      "10"
   ],
   [
      "O73",
      "BEAN",
      "16",
      "8"
   ],
   [
      "O73",
      "BEAN",
      "30",
      "10"
   ],
   [
      "O73",
      "BEAN",
      "28",
      "8"
   ],
   [
      "O73",
      "BEAN",
      "45",
      "23"
   ],
   [
      "O73",
      "BEAN",
      "4",
      "0"
   ],
   [
      "O73",
      "CUCUMBER",
      "12",
      "3"
   ],
   [
      "O73",
      "CUCUMBER",
      "41",
      "22"
   ],
   [
      "O73",
      "CUCUMBER",
      "30",
      "15"
   ],
   [
      "O73",
      "CUCUMBER",
      "51",
      "32"
   ],
   [
      "O73",
      "CUCUMBER",
      "7",
      "3"
   ]
]
