var ratsInfo ={
   "parameters" : {
      "y" : "A numeric vector: the number of pups that survived the 21 day lactation.",
      "n" : "A numeric vector: the number of pups alive at 4 days.",
      "group" : "A factor with levels CTRL and TREAT"
   },
   "description" : "Description\n&ldquo;Weil (1970) in Table 1 gives the results from an experiment comprising two treatments. One group of \n16 pregnant female rats was fed a control diet during pregnancy and lactation, the diet of a second group of 16 pregnant \nfemales was treated with a chemical. For each litter the number n of pups alive at 4 days and the number x \nof pups that survived the 21 day lactation period were recorded.&rdquo; (Williams, 1975, p. 951).",
   "title" : "Rats Diet Experiment",
   "usage" : "data(rats)",
   "reference" : "Williams, D.A., 1975. The analysis of binary responses from toxicological experiments\ninvolving reproduction and teratogenicity. Biometrics 31, 949-952.",
   "format" : "A data frame with 32 observations on the following 3 variables."
}

var rats = [
   [
      "group",
      "n",
      "y"
   ],
   [
      "CTRL",
      "13",
      "13"
   ],
   [
      "CTRL",
      "12",
      "12"
   ],
   [
      "CTRL",
      "9",
      "9"
   ],
   [
      "CTRL",
      "9",
      "9"
   ],
   [
      "CTRL",
      "8",
      "8"
   ],
   [
      "CTRL",
      "8",
      "8"
   ],
   [
      "CTRL",
      "13",
      "12"
   ],
   [
      "CTRL",
      "12",
      "11"
   ],
   [
      "CTRL",
      "10",
      "9"
   ],
   [
      "CTRL",
      "10",
      "9"
   ],
   [
      "CTRL",
      "9",
      "8"
   ],
   [
      "CTRL",
      "13",
      "11"
   ],
   [
      "CTRL",
      "5",
      "4"
   ],
   [
      "CTRL",
      "7",
      "5"
   ],
   [
      "CTRL",
      "10",
      "7"
   ],
   [
      "CTRL",
      "10",
      "7"
   ],
   [
      "TREAT",
      "12",
      "12"
   ],
   [
      "TREAT",
      "11",
      "11"
   ],
   [
      "TREAT",
      "10",
      "10"
   ],
   [
      "TREAT",
      "9",
      "9"
   ],
   [
      "TREAT",
      "11",
      "10"
   ],
   [
      "TREAT",
      "10",
      "9"
   ],
   [
      "TREAT",
      "10",
      "9"
   ],
   [
      "TREAT",
      "9",
      "8"
   ],
   [
      "TREAT",
      "9",
      "8"
   ],
   [
      "TREAT",
      "5",
      "4"
   ],
   [
      "TREAT",
      "9",
      "7"
   ],
   [
      "TREAT",
      "7",
      "4"
   ],
   [
      "TREAT",
      "10",
      "5"
   ],
   [
      "TREAT",
      "6",
      "3"
   ],
   [
      "TREAT",
      "10",
      "3"
   ],
   [
      "TREAT",
      "7",
      "0"
   ]
]
