var cuckoohostsInfo ={
   "usage" : "cuckoohosts",
   "description" : "Description\nThese data compare mean length, mean breadth, and egg color,\nbetween cuckoos and their hosts.",
   "format" : "A data frame with 10 observations on the following 12 variables.",
   "title" : "Comparison of cuckoo eggs with host eggs",
   "reference" : "Although from the same study that generated data in the data frame\ncuckoos, the data do not match precisely.  The cuckoo egg\nlengths and breadths are from the tables on page 168, the host egg\nlengths and breadths from Appendix IV on page 176, and the color\nmatch counts from the table on page 171.",
   "parameters" : {
      "cb.sd" : "standard deviation of cuckoo egg breadths",
      "cbreadth" : "mean breadth of cuckoo eggs in given host's nest",
      "nomatch" : "number where color did not match",
      "hbreadth" : "breadth of host eggs",
      "hb.sd" : "standard deviation of host egg breadths",
      "match" : "number of eggs where color matched",
      "hlength" : "length of host eggs",
      "cnum" : "number of cuckoo eggs",
      "hl.sd" : "standard deviation of host egg lengths",
      "hnum" : "number of host eggs",
      "clength" : "mean length of cuckoo eggs in given host's nest",
      "cl.sd" : "standard deviation of cuckoo egg lengths"
   }
}

var cuckoohosts = [
   [
      "clength",
      "cl.sd",
      "cbreadth",
      "cb.sd",
      "cnum",
      "hlength",
      "hl.sd",
      "hbreadth",
      "hb.sd",
      "hnum",
      "match",
      "nomatch"
   ],
   [
      "22.3",
      "0.89",
      "16.7",
      "0.38",
      "45",
      "19.7",
      "1.25",
      "14.6",
      "0.56",
      "74",
      "56",
      "6"
   ],
   [
      "23.1",
      "1.01",
      "16.8",
      "0.52",
      "14",
      "20.1",
      "0.81",
      "14.7",
      "14.7",
      "26",
      "1",
      "19"
   ],
   [
      "22.5",
      "0.66",
      "16.4",
      "0.53",
      "16",
      "20.2",
      "0.86",
      "15.4",
      "15.4",
      "57",
      "7",
      "11"
   ],
   [
      "22.6",
      "0.9",
      "16.6",
      "0.45",
      "26",
      "20.75",
      "1.44",
      "14.67",
      "0.37",
      "16",
      "26",
      "3"
   ],
   [
      "23.1",
      "0.85",
      "16.6",
      "0.44",
      "15",
      "20",
      "0.7",
      "15.1",
      "0.48",
      "27",
      "11",
      "4"
   ],
   [
      "21.1",
      "0.76",
      "15.8",
      "0.3",
      "15",
      "17.7",
      "17.7",
      "12.7",
      "0.37",
      "",
      "0",
      "17"
   ],
   [
      "22.2",
      "0.65",
      "16.7",
      "0.57",
      "10",
      "",
      "",
      "",
      "0.45",
      "",
      "7",
      "13"
   ],
   [
      "22.6",
      "0.74",
      "16.6",
      "0.48",
      "9",
      "21.55",
      "0.68",
      "16.04",
      "0.4",
      "32",
      "0",
      "12"
   ],
   [
      "23.05",
      "0.13",
      "16.5",
      "0.48",
      "4",
      "",
      "",
      "",
      "",
      "",
      "4",
      "4"
   ],
   [
      "22.9",
      "1.26",
      "16.6",
      "0.87",
      "4",
      "",
      "",
      "",
      "",
      "",
      "1",
      "7"
   ]
]
