var humanpower1Info ={
   "format" : "A data frame with 28 observations on the following 3 variables.",
   "parameters" : {
      "id" : "a factor with levels 1 - 5 (humanpower1)\nor 1 - 4 (humanpower2), identifying the different athletes",
      "wattsPerKg" : "a numeric vector: watts per kilogram of body weight",
      "o2" : "a numeric vector: ml/min/kg"
   },
   "title" : "Oxygen uptake versus mechanical power, for humans",
   "description" : "Description\nData are from Daedalus project; see the reference below.",
   "reference" : "Data in humanpower1 are from investigations (Bussolari 1987)\ndesigned to assess the feasibility of a proposed 119 kilometer human\npowered flight from the island of Crete &ndash; in the initial phase of the\nDaedalus project.  Data are for five athletes\n&ndash; a female hockey player, a male amateur tri-athlete, a female\namateur triathlete, a male wrestler and a male cyclist &ndash; who were\nselected from volunteers who were recruited through the news media,\nData in humanpower2) are for four out of the 25 applicants who\n    were selected for further testing, in the lead-up to the eventual\n    selection of a pilot for the Daedalus project (Nadel and Bussolari 1988).",
   "usage" : "data(humanpower1)"
}

var humanpower1 = [
   [
      "wattsPerKg",
      "o2",
      "id"
   ],
   [
      "2.02",
      "28.56",
      "1"
   ],
   [
      "2.45",
      "36.22",
      "1"
   ],
   [
      "2.83",
      "46.04",
      "1"
   ],
   [
      "3.24",
      "45.9",
      "1"
   ],
   [
      "3.64",
      "55.14",
      "1"
   ],
   [
      "4.04",
      "62.21",
      "1"
   ],
   [
      "4.23",
      "63.42",
      "1"
   ],
   [
      "4.44",
      "66.08",
      "1"
   ],
   [
      "2.12",
      "30.81",
      "2"
   ],
   [
      "2.64",
      "35.45",
      "2"
   ],
   [
      "3.18",
      "46.17",
      "2"
   ],
   [
      "3.45",
      "51.98",
      "2"
   ],
   [
      "3.71",
      "52.88",
      "2"
   ],
   [
      "3.96",
      "58.38",
      "2"
   ],
   [
      "4.23",
      "55.59",
      "2"
   ],
   [
      "2.51",
      "35.18",
      "3"
   ],
   [
      "3.06",
      "45",
      "3"
   ],
   [
      "3.62",
      "57.84",
      "3"
   ],
   [
      "3.89",
      "59.95",
      "3"
   ],
   [
      "2.14",
      "31.8",
      "4"
   ],
   [
      "2.49",
      "38.38",
      "4"
   ],
   [
      "2.85",
      "44.32",
      "4"
   ],
   [
      "3.21",
      "44.64",
      "4"
   ],
   [
      "3.38",
      "47.48",
      "4"
   ],
   [
      "2.31",
      "35.99",
      "5"
   ],
   [
      "2.87",
      "41.17",
      "5"
   ],
   [
      "3.46",
      "46.17",
      "5"
   ],
   [
      "4.03",
      "54.19",
      "5"
   ]
]
