var humanpower2Info ={
   "title" : "Oxygen uptake versus mechanical power, for humans",
   "format" : "A data frame with 28 observations on the following 3 variables.",
   "reference" : "Data in humanpower1 are from investigations (Bussolari 1987)\ndesigned to assess the feasibility of a proposed 119 kilometer human\npowered flight from the island of Crete &ndash; in the initial phase of the\nDaedalus project.  Data are for five athletes\n&ndash; a female hockey player, a male amateur tri-athlete, a female\namateur triathlete, a male wrestler and a male cyclist &ndash; who were\nselected from volunteers who were recruited through the news media,\nData in humanpower2) are for four out of the 25 applicants who\n    were selected for further testing, in the lead-up to the eventual\n    selection of a pilot for the Daedalus project (Nadel and Bussolari 1988).",
   "parameters" : {
      "o2" : "a numeric vector: ml/min/kg",
      "wattsPerKg" : "a numeric vector: watts per kilogram of body weight",
      "id" : "a factor with levels 1 - 5 (humanpower1)\nor 1 - 4 (humanpower2), identifying the different athletes"
   },
   "usage" : "data(humanpower1)",
   "description" : "Description\nData are from Daedalus project; see the reference below."
}

var humanpower2 = [
   [
      "wattsPerKg",
      "o2",
      "id"
   ],
   [
      "2.72",
      "41.09",
      "1"
   ],
   [
      "3.2",
      "46.61",
      "1"
   ],
   [
      "3.66",
      "52.22",
      "1"
   ],
   [
      "4.1",
      "59.51",
      "1"
   ],
   [
      "4.56",
      "67.32",
      "1"
   ],
   [
      "5.03",
      "69.05",
      "1"
   ],
   [
      "2.91",
      "33.75",
      "2"
   ],
   [
      "3.48",
      "41.22",
      "2"
   ],
   [
      "4.07",
      "48.86",
      "2"
   ],
   [
      "4.65",
      "53.91",
      "2"
   ],
   [
      "5.23",
      "59.86",
      "2"
   ],
   [
      "5.86",
      "66.12",
      "2"
   ],
   [
      "6.43",
      "69.48",
      "2"
   ],
   [
      "3.18",
      "41.83",
      "3"
   ],
   [
      "3.65",
      "45.79",
      "3"
   ],
   [
      "4.12",
      "50.62",
      "3"
   ],
   [
      "4.56",
      "55.48",
      "3"
   ],
   [
      "5.02",
      "59.96",
      "3"
   ],
   [
      "5.47",
      "67.04",
      "3"
   ],
   [
      "5.93",
      "68.17",
      "3"
   ],
   [
      "2.59",
      "37.27",
      "4"
   ],
   [
      "3.1",
      "45.18",
      "4"
   ],
   [
      "3.62",
      "51.08",
      "4"
   ],
   [
      "4.14",
      "57.4",
      "4"
   ],
   [
      "4.67",
      "64.15",
      "4"
   ],
   [
      "4.81",
      "67.63",
      "4"
   ]
]
