var kiwishadeInfo ={
   "usage" : "kiwishade",
   "description" : "Description\nThe kiwishade data frame has 48 rows and 4 columns.\nThe data are from a designed experiment that\ncompared different kiwifruit shading treatments.\nThere are four vines in each plot, and four plots (one for each of four\ntreatments: none, Aug2Dec, Dec2Feb, and Feb2May) in each of three blocks\n(locations: west, north, east). Each\nplot has the same number of vines, each block has the same number of\nplots, with each treatment occurring the same number of times.",
   "reference" : "The northernmost plots were grouped together because they\nwere similarly affected by shading from the sun in the north.\nFor the remaining two blocks shelter effects, whether from the\nwest or from the east, were thought more important.",
   "format" : "This data frame contains the following columns:",
   "title" : "Kiwi Shading Data",
   "parameters" : {
      "yield" : "Total yield (in kg)",
      "plot" : "a factor with levels    east.Aug2Dec,\neast.Dec2Feb,    east.Feb2May,\neast.none,    north.Aug2Dec,\nnorth.Dec2Feb,    north.Feb2May,\nnorth.none,    west.Aug2Dec,\nwest.Dec2Feb,    west.Feb2May,\nwest.none",
      "block" : "a factor indicating the location of the plot with levels\neast, north, west",
      "shade" : "a factor representing the period for which\nthe experimenter placed shading over the vines; with levels:\nnone no shading,    Aug2Dec August - December,\nDec2Feb December - February,    Feb2May February - May"
   }
}

var kiwishade = [
   [
      "yield",
      "block",
      "shade",
      "plot"
   ],
   [
      "101.11",
      "north",
      "none",
      "north.none"
   ],
   [
      "108.02",
      "north",
      "none",
      "north.none"
   ],
   [
      "106.67",
      "north",
      "none",
      "north.none"
   ],
   [
      "100.3",
      "north",
      "none",
      "north.none"
   ],
   [
      "92.64",
      "west",
      "none",
      "west.none"
   ],
   [
      "103.49",
      "west",
      "none",
      "west.none"
   ],
   [
      "100.68",
      "west",
      "none",
      "west.none"
   ],
   [
      "93.42",
      "west",
      "none",
      "west.none"
   ],
   [
      "100.31",
      "east",
      "none",
      "east.none"
   ],
   [
      "97",
      "east",
      "none",
      "east.none"
   ],
   [
      "98.05",
      "east",
      "none",
      "east.none"
   ],
   [
      "100.74",
      "east",
      "none",
      "east.none"
   ],
   [
      "105.77",
      "west",
      "Aug2Dec",
      "west.Aug2Dec"
   ],
   [
      "101.41",
      "west",
      "Aug2Dec",
      "west.Aug2Dec"
   ],
   [
      "97.6",
      "west",
      "Aug2Dec",
      "west.Aug2Dec"
   ],
   [
      "97.42",
      "west",
      "Aug2Dec",
      "west.Aug2Dec"
   ],
   [
      "103.1",
      "north",
      "Aug2Dec",
      "north.Aug2Dec"
   ],
   [
      "102.52",
      "north",
      "Aug2Dec",
      "north.Aug2Dec"
   ],
   [
      "104.02",
      "north",
      "Aug2Dec",
      "north.Aug2Dec"
   ],
   [
      "104.74",
      "north",
      "Aug2Dec",
      "north.Aug2Dec"
   ],
   [
      "108.87",
      "east",
      "Aug2Dec",
      "east.Aug2Dec"
   ],
   [
      "103.14",
      "east",
      "Aug2Dec",
      "east.Aug2Dec"
   ],
   [
      "108.32",
      "east",
      "Aug2Dec",
      "east.Aug2Dec"
   ],
   [
      "101.89",
      "east",
      "Aug2Dec",
      "east.Aug2Dec"
   ],
   [
      "86.65",
      "west",
      "Dec2Feb",
      "west.Dec2Feb"
   ],
   [
      "90.75",
      "west",
      "Dec2Feb",
      "west.Dec2Feb"
   ],
   [
      "87.06",
      "west",
      "Dec2Feb",
      "west.Dec2Feb"
   ],
   [
      "84.12",
      "west",
      "Dec2Feb",
      "west.Dec2Feb"
   ],
   [
      "92.17",
      "north",
      "Dec2Feb",
      "north.Dec2Feb"
   ],
   [
      "93.81",
      "north",
      "Dec2Feb",
      "north.Dec2Feb"
   ],
   [
      "94.76",
      "north",
      "Dec2Feb",
      "north.Dec2Feb"
   ],
   [
      "94.05",
      "north",
      "Dec2Feb",
      "north.Dec2Feb"
   ],
   [
      "85.4",
      "east",
      "Dec2Feb",
      "east.Dec2Feb"
   ],
   [
      "81.43",
      "east",
      "Dec2Feb",
      "east.Dec2Feb"
   ],
   [
      "93.94",
      "east",
      "Dec2Feb",
      "east.Dec2Feb"
   ],
   [
      "94.91",
      "east",
      "Dec2Feb",
      "east.Dec2Feb"
   ],
   [
      "92.58",
      "north",
      "Feb2May",
      "north.Feb2May"
   ],
   [
      "93.45",
      "north",
      "Feb2May",
      "north.Feb2May"
   ],
   [
      "90.29",
      "north",
      "Feb2May",
      "north.Feb2May"
   ],
   [
      "91.82",
      "north",
      "Feb2May",
      "north.Feb2May"
   ],
   [
      "87.27",
      "west",
      "Feb2May",
      "west.Feb2May"
   ],
   [
      "94.99",
      "west",
      "Feb2May",
      "west.Feb2May"
   ],
   [
      "89.06",
      "west",
      "Feb2May",
      "west.Feb2May"
   ],
   [
      "90.31",
      "west",
      "Feb2May",
      "west.Feb2May"
   ],
   [
      "92.45",
      "east",
      "Feb2May",
      "east.Feb2May"
   ],
   [
      "97.57",
      "east",
      "Feb2May",
      "east.Feb2May"
   ],
   [
      "97.15",
      "east",
      "Feb2May",
      "east.Feb2May"
   ],
   [
      "96.35",
      "east",
      "Feb2May",
      "east.Feb2May"
   ]
]
